#Project generated by Animated Java (https://animated-java.dev/)

schedule function boat:animation_loop 1t
scoreboard players set .aj.anim_loop aj.boat.animating 1
scoreboard players set .aj.animation aj.boat.animating 0
execute as @e[type=minecraft:marker,tag=aj.boat.root] run function boat:zzz/execute/11
execute if score .aj.animation aj.boat.animating matches 0 run function boat:zzz/execute/12