#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.cobblestone.anim.new
execute if score .aj.cobblestone.framerate aj.i matches ..-1 run scoreboard players set @s aj.frame 20
execute if score .aj.cobblestone.framerate aj.i matches 1.. run scoreboard players set @s aj.frame 0
scoreboard players add .noScripts aj.i 0
execute if score .aj.anim_loop aj.cobblestone.animating matches 0 run function cobblestone:animation_loop
scoreboard players set #execute aj.i 1