#Project generated by Animated Java (https://animated-java.dev/)

schedule function amirkaka:animation_loop 1t
scoreboard players set .aj.anim_loop aj.amirkaka.animating 1
scoreboard players set .aj.animation aj.amirkaka.animating 0
execute as @e[type=minecraft:marker,tag=aj.amirkaka.root] run function amirkaka:zzz/execute/26
execute if score .aj.animation aj.amirkaka.animating matches 0 run function amirkaka:zzz/execute/27