#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['new','aj.glare','aj.glare.root']}
execute as @e[type=minecraft:marker,tag=aj.glare.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function glare:summon/zzz/execute/2
function glare:assert_animation_flags