#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.boat.anim.new
execute if score .aj.anim_loop aj.boat.animating matches 0 run function boat:animation_loop
scoreboard players set #execute aj.i 1