#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#wheelguy:bone_entities,tag=aj.wheelguy.bone,distance=..1.752] if score @s aj.id = .this aj.id run function wheelguy:animations/idle/tree/trunk
scoreboard players operation @s aj.frame += .aj.wheelguy.framerate aj.i
scoreboard players set .aj.animation aj.wheelguy.animating 1
execute unless score @s aj.frame matches 0..240 run function wheelguy:animations/idle/edge