#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.094 ^-1.688 ^-0.375 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.094 ^-1.678 ^-0.375 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.094 ^-1.665 ^-0.374 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.094 ^-1.648 ^-0.374 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.094 ^-1.629 ^-0.373 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.094 ^-1.61 ^-0.372 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.094 ^-1.591 ^-0.371 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.094 ^-1.574 ^-0.371 ~ ~