#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [2.1112f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [2.3159f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [2.4512f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [2.5f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [2.428f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [2.2325f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [1.9444f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [1.5947f,0f,0f]