#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.094 ^-1.56 ^-0.37 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.094 ^-1.551 ^-0.37 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.094 ^-1.547 ^-0.369 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.094 ^-1.55 ^-0.369 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.094 ^-1.558 ^-0.369 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.094 ^-1.572 ^-0.37 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.094 ^-1.588 ^-0.371 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.094 ^-1.607 ^-0.371 ~ ~