#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.094 ^-1.829 ^0.12 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.094 ^-1.821 ^0.12 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.094 ^-1.818 ^0.12 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.094 ^-1.821 ^0.119 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.094 ^-1.829 ^0.12 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.094 ^-1.841 ^0.12 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.094 ^-1.855 ^0.121 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.094 ^-1.871 ^0.121 ~ ~