#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bee:animations/normal/tree/front_legs_root_0-7
execute if score .this aj.frame matches 8..15 run function bee:animations/normal/tree/front_legs_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.094 ^-1.888 ^0.122 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.094 ^-1.904 ^0.123 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.094 ^-1.918 ^0.124 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.094 ^-1.93 ^0.125 ~ ~