#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0.1406f,0.0582f,-22.4999f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0.2616f,0.2616f,-44.9994f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0.5883f,0.2437f,-22.4987f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0.9354f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [1.154f,0.478f,-22.4952f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [1.1038f,1.1036f,-44.9894f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [1.7128f,0.7093f,-22.4894f]