#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.344 ^-1.25 ^0.188 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.344 ^-1.242 ^0.189 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.344 ^-1.231 ^0.191 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.344 ^-1.216 ^0.194 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.344 ^-1.201 ^0.197 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.344 ^-1.184 ^0.2 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.344 ^-1.169 ^0.203 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.344 ^-1.155 ^0.206 ~ ~