#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bee:animations/normal/tree/left_wing_root_0-7
execute if score .this aj.frame matches 8..15 run function bee:animations/normal/tree/left_wing_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0.344 ^-1.202 ^0.199 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.344 ^-1.217 ^0.196 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.344 ^-1.231 ^0.192 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.344 ^-1.243 ^0.189 ~ ~