#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.094 ^-1.688 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.094 ^-1.679 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.094 ^-1.667 ^0.001 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.094 ^-1.652 ^0.001 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.094 ^-1.635 ^0.002 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.094 ^-1.618 ^0.003 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.094 ^-1.601 ^0.003 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.094 ^-1.586 ^0.004 ~ ~