#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bee:animations/normal/tree/middle_legs_root_0-7
execute if score .this aj.frame matches 8..15 run function bee:animations/normal/tree/middle_legs_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^-0.094 ^-1.635 ^0.003 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.094 ^-1.652 ^0.002 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.094 ^-1.667 ^0.001 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.094 ^-1.679 ^0 ~ ~