#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.344 ^-1.144 ^0.208 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.344 ^-1.136 ^0.21 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.344 ^-1.134 ^0.211 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.344 ^-1.137 ^0.212 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.344 ^-1.145 ^0.211 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.344 ^-1.156 ^0.209 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.344 ^-1.17 ^0.206 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.344 ^-1.186 ^0.203 ~ ~