#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [2.1112f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [2.1398f,-0.8861f,22.4835f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [1.7338f,-1.733f,44.9738f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [2.3099f,-0.9564f,22.4807f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [2.428f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [2.0627f,-0.8542f,22.4846f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [1.3752f,-1.3748f,44.9835f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [1.4733f,-0.6102f,22.4922f]