#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bee:animations/normal/tree/stinger_display_0-7
execute if score .this aj.frame matches 8..15 run function bee:animations/normal/tree/stinger_display_8-15
execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [1.2514f,-14.0493f,-0.3038f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0.846f,-9.9261f,-0.1458f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0.486f,-5.787f,-0.049f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0.1956f,-2.2668f,-0.0077f]