#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [0.1523f,2.42f,0.0064f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0.3722f,6.2599f,0.0406f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [0.6468f,10.1394f,0.1139f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [0.9588f,12.6783f,0.2104f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [1.2794f,12.497f,0.2769f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [1.5861f,10.2281f,0.2817f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [1.8652f,6.3053f,0.2049f]