#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function bee:animations/normal/tree/stinger_root_0-7
execute if score .this aj.frame matches 8..15 run function bee:animations/normal/tree/stinger_root_8-15
execute if score .this aj.frame matches 16 run tp @s ^0 ^-1.951 ^-1.317 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-1.976 ^-1.316 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-2 ^-1.314 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-2.019 ^-1.313 ~ ~