#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.438 ^-2.407 ^0.25 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.438 ^-2.399 ^0.248 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.438 ^-2.387 ^0.246 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.438 ^-2.373 ^0.243 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.438 ^-2.358 ^0.24 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.438 ^-2.342 ^0.237 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.438 ^-2.326 ^0.234 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.438 ^-2.313 ^0.231 ~ ~