#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-5.824f,1.4364f,4.9359f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-7.2406f,1.625f,5.8733f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-8.4733f,1.6915f,6.643f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-9.4044f,1.5961f,7.172f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-9.9162f,1.2988f,7.3873f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-10.0239f,0.6238f,7.218f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-9.8165f,-0.4219f,6.6946f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-9.3581f,-1.7166f,5.906f]