#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.012 ^-0.194 ^-0.047 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.012 ^-0.204 ^-0.047 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.012 ^-0.233 ^-0.047 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.012 ^-0.247 ^-0.047 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.012 ^-0.241 ^-0.047 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.012 ^-0.227 ^-0.047 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.012 ^-0.209 ^-0.047 ~ ~