#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-8.7132f,-3.1388f,4.941f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-7.9458f,-4.567f,3.8885f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-7.1205f,-5.8796f,2.8374f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-6.3014f,-6.955f,1.8765f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-5.5528f,-7.6718f,1.0948f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-4.6175f,-7.8203f,0.3886f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-2.2197f,-4.5279f,-0.0915f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-0.2445f,-0.4365f,0.0125f]