#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function amirkaka:animations/idle3/tree/leftleg_root_0-7
execute if score .this aj.frame matches 8..15 run function amirkaka:animations/idle3/tree/leftleg_root_8-15
execute if score .this aj.frame matches 16..23 run function amirkaka:animations/idle3/tree/leftleg_root_16-23
execute if score .this aj.frame matches 24..31 run function amirkaka:animations/idle3/tree/leftleg_root_24-31
execute if score .this aj.frame matches 32..39 run function amirkaka:animations/idle3/tree/leftleg_root_32-39
execute if score .this aj.frame matches 40 run tp @s ^0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.125 ^-1.125 ^0 ~ ~