#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.313 ^-0.438 ^0 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.313 ^-0.409 ^0 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.313 ^-0.353 ^0 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.313 ^-0.314 ^0 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.313 ^-0.333 ^0 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.313 ^-0.387 ^0 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.313 ^-0.433 ^0 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.313 ^-0.426 ^0 ~ ~