#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [0f,0f,-59.3871f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0f,0f,-60.065f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0f,0f,-60.6353f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0f,0f,-61.0981f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [0f,0f,-61.4532f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [0f,0f,-61.7007f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [0f,0f,-61.8406f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [0f,0f,-61.8728f]