#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [0f,0f,-57.3209f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [0f,0f,-56.2771f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [0f,0f,-55.1257f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [0f,0f,-53.8666f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [0f,0f,-52.5f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [0f,0f,-37.2656f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [0f,0f,-15f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [0f,0f,7.2656f]