#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,0f,-61.7975f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0f,0f,-61.6146f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [0f,0f,-61.324f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0f,0f,-60.9259f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0f,0f,-60.4201f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0f,0f,-59.8067f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,0f,-59.0857f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [0f,0f,-58.2571f]