#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,0f,61.8384f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0f,0f,61.6896f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [0f,0f,61.4264f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0f,0f,61.0487f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0f,0f,60.5566f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0f,0f,59.9501f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,0f,59.2291f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [0f,0f,58.3937f]