#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [0f,0f,58.9087f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0f,0f,59.6754f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0f,0f,60.3278f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0f,0f,60.8656f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [0f,0f,61.2891f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [0f,0f,61.5981f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [0f,0f,61.7926f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [0f,0f,61.8727f]