#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.boat.anim.new] at @s run function boat:animations/new/next_frame
scoreboard players operation @s aj.boat.animating = .aj.animation aj.boat.animating