#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.boat.bone.paddle_right] Pose.Head set value [125.264f,-30f,-144.736f]
data modify entity @s[tag=aj.boat.bone.paddle_left] Pose.Head set value [125.264f,30f,144.736f]
data modify entity @s[tag=aj.boat.bone.back] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.boat.bone.front] Pose.Head set value [-180f,0f,180f]
data modify entity @s[tag=aj.boat.bone.left] Pose.Head set value [0f,90f,0f]
data modify entity @s[tag=aj.boat.bone.right] Pose.Head set value [0f,-90f,0f]
data modify entity @s[tag=aj.boat.bone.bottom] Pose.Head set value [0f,90f,-90f]
data modify entity @s[tag=aj.boat.bone.bottom_no_water] Pose.Head set value [0f,-90f,90f]
tp @s ~ ~ ~ ~ ~