#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.bee.anim.normal
execute if score .aj.anim_loop aj.bee.animating matches 0 run function bee:animation_loop
scoreboard players set #execute aj.i 1