#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['new','aj.bee','aj.bee.root']}
execute as @e[type=minecraft:marker,tag=aj.bee.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function bee:summon/zzz/execute/2
function bee:assert_animation_flags