#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.cob.loop.loopMode matches 0 run function cob:animations/loop/stop
execute if score @s aj.cob.loop.loopMode matches 1 run function cob:animations/loop/pause
execute if score @s aj.cob.loop.loopMode matches 2 run function cob:animations/loop/zzz/execute/13