#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#cob:bone_entities,tag=aj.cob.bone,distance=..1.764] if score @s aj.id = .this aj.id run function cob:animations/loop/tree/trunk
scoreboard players operation @s aj.frame += .aj.cob.framerate aj.i
scoreboard players set .aj.animation aj.cob.animating 1
execute unless score @s aj.frame matches 0..280 run function cob:animations/loop/edge