#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.cobblestone.root] run function cobblestone:animations/new/zzz/conditional/22
execute if score #execute aj.i matches 0 run function cobblestone:animations/new/zzz/conditional/23