#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['new','aj.boat','aj.boat.root']}
execute as @e[type=minecraft:marker,tag=aj.boat.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function boat:summon/zzz/execute/2
function boat:assert_animation_flags