#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.wheelguy.bone.footl] run function wheelguy:animations/idle/tree/footl_display_top
execute if entity @s[tag=aj.wheelguy.bone.legl] run function wheelguy:animations/idle/tree/legl_display_top
execute if entity @s[tag=aj.wheelguy.bone.wheel] run function wheelguy:animations/idle/tree/wheel_display_top
execute if entity @s[tag=aj.wheelguy.bone.footr] run function wheelguy:animations/idle/tree/footr_display_top
execute if entity @s[tag=aj.wheelguy.bone.legr] run function wheelguy:animations/idle/tree/legr_display_top
execute if entity @s[tag=aj.wheelguy.bone.wheel2] run function wheelguy:animations/idle/tree/wheel2_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~