#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [0f,0f,3.6177f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [0f,0f,3.4308f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [0f,0f,3.2088f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [0f,0f,2.9502f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [0f,0f,2.6536f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [0f,0f,2.3178f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [0f,0f,1.9412f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [0f,0f,1.5225f]