#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.235 ^-1.559 ^-0.125 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.24 ^-1.557 ^-0.125 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.242 ^-1.563 ^-0.125 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.243 ^-1.573 ^-0.125 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.243 ^-1.586 ^-0.125 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.243 ^-1.598 ^-0.125 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.244 ^-1.607 ^-0.125 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.248 ^-1.611 ^-0.125 ~ ~