#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 208 run tp @s ^-0.021 ^-1.588 ^0.156 ~ ~
execute if score .this aj.frame matches 209 run tp @s ^-0.021 ^-1.588 ^0.156 ~ ~
execute if score .this aj.frame matches 210 run tp @s ^-0.021 ^-1.588 ^0.156 ~ ~
execute if score .this aj.frame matches 211 run tp @s ^-0.021 ^-1.588 ^0.156 ~ ~
execute if score .this aj.frame matches 212 run tp @s ^-0.021 ^-1.588 ^0.156 ~ ~
execute if score .this aj.frame matches 213 run tp @s ^-0.021 ^-1.588 ^0.156 ~ ~
execute if score .this aj.frame matches 214 run tp @s ^-0.021 ^-1.588 ^0.156 ~ ~
execute if score .this aj.frame matches 215 run tp @s ^-0.021 ^-1.588 ^0.156 ~ ~