#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [0f,0f,3.1191f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [0f,0f,3.0382f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [0f,0f,2.8826f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [0f,0f,2.6455f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [0f,0f,2.3202f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [0f,0f,1.8997f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [0f,0f,1.3774f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [0f,0f,0.7465f]