#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.097 ^-1.492 ^0.156 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.1 ^-1.52 ^0.156 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.097 ^-1.549 ^0.156 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.091 ^-1.574 ^0.156 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.083 ^-1.588 ^0.156 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.074 ^-1.594 ^0.156 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.063 ^-1.594 ^0.156 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.051 ^-1.59 ^0.156 ~ ~