#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [0f,0f,2.963f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [0f,0f,3.1493f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [0f,0f,3.3227f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [0f,0f,3.4819f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [0f,0f,3.6253f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [0f,0f,3.7517f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [0f,0f,3.8596f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [0f,0f,3.9477f]