#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^-0.348 ^-1.518 ^-0.125 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^-0.358 ^-1.505 ^-0.125 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^-0.364 ^-1.495 ^-0.125 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.367 ^-1.493 ^-0.125 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.368 ^-1.5 ^-0.125 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.366 ^-1.517 ^-0.125 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.362 ^-1.539 ^-0.125 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.353 ^-1.56 ^-0.125 ~ ~