#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.093 ^-1.492 ^-0.125 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.088 ^-1.47 ^-0.125 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.086 ^-1.462 ^-0.125 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.088 ^-1.471 ^-0.125 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.091 ^-1.492 ^-0.125 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.093 ^-1.52 ^-0.125 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.092 ^-1.549 ^-0.125 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.087 ^-1.573 ^-0.125 ~ ~