#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [0f,0f,0.3368f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [0f,0f,0.1148f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [0f,0f,-0.1148f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [0f,0f,-0.3368f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [0f,0f,-0.5358f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [0f,0f,-0.6965f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [0f,0f,-0.8037f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [0f,0f,-0.842f]