#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 160 run data modify entity @s Pose.Head set value [0f,0f,102.795f]
execute if score .this aj.frame matches 161 run data modify entity @s Pose.Head set value [0f,0f,129.5706f]
execute if score .this aj.frame matches 162 run data modify entity @s Pose.Head set value [0f,0f,155.4227f]
execute if score .this aj.frame matches 163 run data modify entity @s Pose.Head set value [0f,0f,-179.7951f]
execute if score .this aj.frame matches 164 run data modify entity @s Pose.Head set value [0f,0f,-156.2297f]
execute if score .this aj.frame matches 165 run data modify entity @s Pose.Head set value [0f,0f,-134.0277f]
execute if score .this aj.frame matches 166 run data modify entity @s Pose.Head set value [0f,0f,-113.3358f]
execute if score .this aj.frame matches 167 run data modify entity @s Pose.Head set value [0f,0f,-94.3006f]