#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [0f,0f,1.175f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [0f,0f,1.4144f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [0f,0f,1.6521f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [0f,0f,1.8866f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [0f,0f,2.1165f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [0f,0f,2.3405f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [0f,0f,2.5572f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [0f,0f,2.7651f]