#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.16 ^-1.574 ^-0.125 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.176 ^-1.549 ^-0.125 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.189 ^-1.52 ^-0.125 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.199 ^-1.492 ^-0.125 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.206 ^-1.47 ^-0.125 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.211 ^-1.462 ^-0.125 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.216 ^-1.471 ^-0.125 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.22 ^-1.493 ^-0.125 ~ ~