#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [0f,0f,-6.0185f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [0f,0f,-14.8148f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [0f,0f,-25f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [0f,0f,-35.1852f]
execute if score .this aj.frame matches 133 run data modify entity @s Pose.Head set value [0f,0f,-43.9815f]
execute if score .this aj.frame matches 134 run data modify entity @s Pose.Head set value [0f,0f,-50f]
execute if score .this aj.frame matches 135 run data modify entity @s Pose.Head set value [0f,0f,-50.7257f]