#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 160 run tp @s ^0.29 ^-1.589 ^-0.125 ~ ~
execute if score .this aj.frame matches 161 run tp @s ^0.292 ^-1.654 ^-0.125 ~ ~
execute if score .this aj.frame matches 162 run tp @s ^0.268 ^-1.705 ^-0.125 ~ ~
execute if score .this aj.frame matches 163 run tp @s ^0.229 ^-1.732 ^-0.125 ~ ~
execute if score .this aj.frame matches 164 run tp @s ^0.185 ^-1.734 ^-0.125 ~ ~
execute if score .this aj.frame matches 165 run tp @s ^0.148 ^-1.715 ^-0.125 ~ ~
execute if score .this aj.frame matches 166 run tp @s ^0.122 ^-1.68 ^-0.125 ~ ~
execute if score .this aj.frame matches 167 run tp @s ^0.111 ^-1.639 ^-0.125 ~ ~