#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [0f,0f,9.8438f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [0f,0f,5.8333f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [0f,0f,2.309f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [0f,0f,-0.8102f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [0f,0f,-0.6481f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [0f,0f,0.6481f]