#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [0f,0f,0.8102f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [0f,0f,-2.309f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [0f,0f,-5.8333f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [0f,0f,-9.8437f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [0f,0f,-13.6111f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [0f,0f,-16.4062f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [0f,0f,-17.5f]