#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^-0.325 ^-1.593 ^-0.125 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^-0.326 ^-1.592 ^-0.125 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^-0.327 ^-1.591 ^-0.125 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^-0.327 ^-1.591 ^-0.125 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^-0.328 ^-1.59 ^-0.125 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^-0.329 ^-1.589 ^-0.125 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^-0.331 ^-1.588 ^-0.125 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^-0.332 ^-1.587 ^-0.125 ~ ~