#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^-0.334 ^-1.59 ^0.156 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^-0.333 ^-1.59 ^0.156 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^-0.333 ^-1.59 ^0.156 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^-0.332 ^-1.59 ^0.156 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^-0.332 ^-1.591 ^0.156 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^-0.331 ^-1.591 ^0.156 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^-0.331 ^-1.591 ^0.156 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^-0.33 ^-1.591 ^0.156 ~ ~