#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [0f,0f,1.0604f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [0f,0f,0.5533f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [0f,0f,-9.1406f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [0f,0f,-22.5f]
execute if score .this aj.frame matches 133 run data modify entity @s Pose.Head set value [0f,0f,-35.8594f]
execute if score .this aj.frame matches 134 run data modify entity @s Pose.Head set value [0f,0f,-45f]
execute if score .this aj.frame matches 135 run data modify entity @s Pose.Head set value [0f,0f,-45.6523f]