#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.268 ^-1.47 ^0.156 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.274 ^-1.462 ^0.156 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.279 ^-1.47 ^0.156 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.283 ^-1.492 ^0.156 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.283 ^-1.52 ^0.156 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.28 ^-1.549 ^0.156 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.275 ^-1.574 ^0.156 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.271 ^-1.588 ^0.156 ~ ~