#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.088 ^-1.58 ^-0.125 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.092 ^-1.579 ^-0.125 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.097 ^-1.581 ^-0.125 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.105 ^-1.585 ^-0.125 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.113 ^-1.59 ^-0.125 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.123 ^-1.594 ^-0.125 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.134 ^-1.594 ^-0.125 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.146 ^-1.588 ^-0.125 ~ ~