#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^-0.328 ^-1.591 ^0.156 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^-0.328 ^-1.59 ^0.156 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^-0.328 ^-1.59 ^0.156 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^-0.328 ^-1.59 ^0.156 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^-0.328 ^-1.59 ^0.156 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^-0.329 ^-1.589 ^0.156 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^-0.33 ^-1.589 ^0.156 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^-0.33 ^-1.589 ^0.156 ~ ~