#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^0.182 ^-1.6 ^0.156 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^0.187 ^-1.601 ^0.156 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^0.195 ^-1.595 ^0.156 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^0.194 ^-1.562 ^0.156 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^0.186 ^-1.513 ^0.156 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^0.174 ^-1.459 ^0.156 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^0.162 ^-1.408 ^0.156 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^0.154 ^-1.372 ^0.156 ~ ~