#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.04 ^-1.585 ^0.156 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.032 ^-1.581 ^0.156 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.029 ^-1.579 ^0.156 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.033 ^-1.58 ^0.156 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.042 ^-1.582 ^0.156 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.053 ^-1.584 ^0.156 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.066 ^-1.586 ^0.156 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.077 ^-1.587 ^0.156 ~ ~