#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.021 ^-1.588 ^-0.125 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.022 ^-1.587 ^-0.125 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.022 ^-1.586 ^-0.125 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.022 ^-1.584 ^-0.125 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.023 ^-1.582 ^-0.125 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.025 ^-1.58 ^-0.125 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.029 ^-1.579 ^-0.125 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.036 ^-1.581 ^-0.125 ~ ~