#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0f,0f,0.3904f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [0f,0f,0.6506f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0f,0f,0.796f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0f,0f,0.842f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0f,0f,0.8037f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,0f,0.6965f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [0f,0f,0.5358f]