#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.083 ^-1.588 ^0.156 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.085 ^-1.589 ^0.156 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.085 ^-1.589 ^0.156 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.085 ^-1.59 ^0.156 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.085 ^-1.591 ^0.156 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.085 ^-1.592 ^0.156 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.084 ^-1.593 ^0.156 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.083 ^-1.594 ^0.156 ~ ~