#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.335 ^-1.589 ^0.156 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.335 ^-1.589 ^0.156 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.335 ^-1.589 ^0.156 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.335 ^-1.589 ^0.156 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.335 ^-1.589 ^0.156 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.335 ^-1.59 ^0.156 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.334 ^-1.59 ^0.156 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.334 ^-1.59 ^0.156 ~ ~