#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function wheelguy:animations/idle/tree/footr_display_0-63
execute if score .this aj.frame matches 64..127 run function wheelguy:animations/idle/tree/footr_display_64-127
execute if score .this aj.frame matches 128..191 run function wheelguy:animations/idle/tree/footr_display_128-191
execute if score .this aj.frame matches 239 run data modify entity @s Pose.Head set value [0f,0f,0f]