#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run tp @s ^0.113 ^-1.603 ^-0.125 ~ ~
execute if score .this aj.frame matches 169 run tp @s ^0.122 ^-1.573 ^-0.125 ~ ~
execute if score .this aj.frame matches 170 run tp @s ^0.134 ^-1.551 ^-0.125 ~ ~
execute if score .this aj.frame matches 171 run tp @s ^0.158 ^-1.559 ^-0.125 ~ ~
execute if score .this aj.frame matches 172 run tp @s ^0.171 ^-1.567 ^-0.125 ~ ~
execute if score .this aj.frame matches 173 run tp @s ^0.177 ^-1.574 ^-0.125 ~ ~
execute if score .this aj.frame matches 174 run tp @s ^0.179 ^-1.584 ^-0.125 ~ ~
execute if score .this aj.frame matches 175 run tp @s ^0.18 ^-1.594 ^-0.125 ~ ~