#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.143 ^-1.471 ^0.156 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.149 ^-1.462 ^0.156 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.154 ^-1.47 ^0.156 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.158 ^-1.492 ^0.156 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.158 ^-1.52 ^0.156 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.155 ^-1.549 ^0.156 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.15 ^-1.574 ^0.156 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.146 ^-1.588 ^0.156 ~ ~