#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 184 run tp @s ^0.153 ^-1.339 ^-0.125 ~ ~
execute if score .this aj.frame matches 185 run tp @s ^0.151 ^-1.372 ^-0.125 ~ ~
execute if score .this aj.frame matches 186 run tp @s ^0.128 ^-1.427 ^-0.125 ~ ~
execute if score .this aj.frame matches 187 run tp @s ^0.095 ^-1.506 ^-0.125 ~ ~
execute if score .this aj.frame matches 188 run tp @s ^0.053 ^-1.579 ^-0.125 ~ ~
execute if score .this aj.frame matches 189 run tp @s ^0.015 ^-1.62 ^-0.125 ~ ~
execute if score .this aj.frame matches 190 run tp @s ^-0.007 ^-1.602 ^-0.125 ~ ~
execute if score .this aj.frame matches 191 run tp @s ^-0.021 ^-1.588 ^-0.125 ~ ~