#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [0f,0f,4.0146f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [0f,0f,4.0588f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [0f,0f,4.079f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [0f,0f,4.0737f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [0f,0f,4.0417f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [0f,0f,3.9815f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [0f,0f,3.8917f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [0f,0f,3.7709f]