#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.078 ^-1.594 ^0.156 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.08 ^-1.593 ^0.156 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.081 ^-1.591 ^0.156 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.083 ^-1.588 ^0.156 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.095 ^-1.573 ^0.156 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.11 ^-1.549 ^0.156 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.124 ^-1.52 ^0.156 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.135 ^-1.492 ^0.156 ~ ~