#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.082 ^-1.59 ^-0.125 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.083 ^-1.589 ^-0.125 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.083 ^-1.589 ^-0.125 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.083 ^-1.588 ^-0.125 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.084 ^-1.587 ^-0.125 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.084 ^-1.586 ^-0.125 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.085 ^-1.584 ^-0.125 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.086 ^-1.582 ^-0.125 ~ ~