#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 160 run data modify entity @s Pose.Head set value [0f,0f,108.2128f]
execute if score .this aj.frame matches 161 run data modify entity @s Pose.Head set value [0f,0f,134.9425f]
execute if score .this aj.frame matches 162 run data modify entity @s Pose.Head set value [0f,0f,160.7441f]
execute if score .this aj.frame matches 163 run data modify entity @s Pose.Head set value [0f,0f,-174.5288f]
execute if score .this aj.frame matches 164 run data modify entity @s Pose.Head set value [0f,0f,-151.0231f]
execute if score .this aj.frame matches 165 run data modify entity @s Pose.Head set value [0f,0f,-128.8854f]
execute if score .this aj.frame matches 166 run data modify entity @s Pose.Head set value [0f,0f,-108.2623f]
execute if score .this aj.frame matches 167 run data modify entity @s Pose.Head set value [0f,0f,-89.3006f]