#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^-0.368 ^-1.517 ^0.156 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^-0.387 ^-1.515 ^0.156 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^-0.39 ^-1.514 ^0.156 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^-0.355 ^-1.513 ^0.156 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^-0.327 ^-1.483 ^0.156 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^-0.288 ^-1.456 ^0.156 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^-0.236 ^-1.436 ^0.156 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^-0.174 ^-1.428 ^0.156 ~ ~