#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.254 ^-1.608 ^-0.125 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.261 ^-1.6 ^-0.125 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.269 ^-1.59 ^-0.125 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.279 ^-1.579 ^-0.125 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.29 ^-1.567 ^-0.125 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.302 ^-1.557 ^-0.125 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.317 ^-1.547 ^-0.125 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.333 ^-1.533 ^-0.125 ~ ~