#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [0f,0f,-9.5313f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [0f,0f,-7.1296f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [0f,0f,-3.9641f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [0f,0f,6.0012f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [0f,0f,14.2593f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [0f,0f,23.2812f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [0f,0f,31.5741f]