#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [0f,0f,-3.9641f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [0f,0f,-7.1296f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [0f,0f,-9.5312f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [0f,0f,-11.2037f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,0f,-12.1817f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [0f,0f,-12.5f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [0f,0f,-12.1817f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [0f,0f,-11.2037f]