#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^-0.025 ^-1.583 ^0.141 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^-0.004 ^-1.58 ^0.141 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^0.018 ^-1.579 ^0.141 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^0.042 ^-1.579 ^0.141 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^0.065 ^-1.58 ^0.141 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^0.087 ^-1.582 ^0.141 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^0.107 ^-1.586 ^0.141 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^0.126 ^-1.589 ^0.141 ~ ~