#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run tp @s ^-0.155 ^-1.578 ^0.141 ~ ~
execute if score .this aj.frame matches 145 run tp @s ^-0.14 ^-1.581 ^0.141 ~ ~
execute if score .this aj.frame matches 146 run tp @s ^-0.124 ^-1.583 ^0.141 ~ ~
execute if score .this aj.frame matches 147 run tp @s ^-0.109 ^-1.586 ^0.141 ~ ~
execute if score .this aj.frame matches 148 run tp @s ^-0.094 ^-1.588 ^0.141 ~ ~
execute if score .this aj.frame matches 149 run tp @s ^-0.078 ^-1.588 ^0.141 ~ ~
execute if score .this aj.frame matches 150 run tp @s ^-0.062 ^-1.587 ^0.141 ~ ~
execute if score .this aj.frame matches 151 run tp @s ^-0.045 ^-1.585 ^0.141 ~ ~