#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.079 ^-1.479 ^0.141 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.085 ^-1.486 ^0.141 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.09 ^-1.492 ^0.141 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.095 ^-1.494 ^0.141 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.1 ^-1.492 ^0.141 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.105 ^-1.486 ^0.141 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.111 ^-1.479 ^0.141 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.116 ^-1.471 ^0.141 ~ ~