#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0.03 ^-1.494 ^0.141 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0.029 ^-1.495 ^0.141 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0.029 ^-1.496 ^0.141 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0.029 ^-1.496 ^0.141 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0.029 ^-1.497 ^0.141 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.029 ^-1.497 ^0.141 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.029 ^-1.498 ^0.141 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.029 ^-1.498 ^0.141 ~ ~