#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run tp @s ^0.258 ^-1.576 ^0.141 ~ ~
execute if score .this aj.frame matches 169 run tp @s ^0.27 ^-1.574 ^0.141 ~ ~
execute if score .this aj.frame matches 170 run tp @s ^0.28 ^-1.572 ^0.141 ~ ~
execute if score .this aj.frame matches 171 run tp @s ^0.305 ^-1.566 ^0.141 ~ ~
execute if score .this aj.frame matches 172 run tp @s ^0.318 ^-1.558 ^0.141 ~ ~
execute if score .this aj.frame matches 173 run tp @s ^0.322 ^-1.55 ^0.141 ~ ~
execute if score .this aj.frame matches 174 run tp @s ^0.319 ^-1.539 ^0.141 ~ ~
execute if score .this aj.frame matches 175 run tp @s ^0.311 ^-1.527 ^0.141 ~ ~