#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [0f,0f,-1.3691f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [0f,0f,-0.7263f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [0f,0f,12.1875f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [0f,0f,30f]
execute if score .this aj.frame matches 133 run data modify entity @s Pose.Head set value [0f,0f,47.8125f]
execute if score .this aj.frame matches 134 run data modify entity @s Pose.Head set value [0f,0f,60f]
execute if score .this aj.frame matches 135 run data modify entity @s Pose.Head set value [0f,0f,60.8682f]