#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.029 ^-1.498 ^0.141 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.03 ^-1.498 ^0.141 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.03 ^-1.498 ^0.141 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.031 ^-1.498 ^0.141 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.031 ^-1.498 ^0.141 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.031 ^-1.498 ^0.141 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.031 ^-1.497 ^0.141 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.032 ^-1.497 ^0.141 ~ ~