#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^0.301 ^-1.512 ^0.141 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^0.289 ^-1.495 ^0.141 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^0.28 ^-1.475 ^0.141 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^0.261 ^-1.43 ^0.141 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^0.234 ^-1.374 ^0.141 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^0.203 ^-1.314 ^0.141 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^0.175 ^-1.261 ^0.141 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^0.155 ^-1.225 ^0.141 ~ ~