#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run data modify entity @s Pose.Head set value [0f,0f,3f]
execute if score .this aj.frame matches 177 run data modify entity @s Pose.Head set value [0f,0f,-6.4f]
execute if score .this aj.frame matches 178 run data modify entity @s Pose.Head set value [0f,0f,-15f]
execute if score .this aj.frame matches 179 run data modify entity @s Pose.Head set value [0f,0f,-23.2f]
execute if score .this aj.frame matches 180 run data modify entity @s Pose.Head set value [0f,0f,-31.4f]
execute if score .this aj.frame matches 181 run data modify entity @s Pose.Head set value [0f,0f,-39f]
execute if score .this aj.frame matches 182 run data modify entity @s Pose.Head set value [0f,0f,-45.4f]
execute if score .this aj.frame matches 183 run data modify entity @s Pose.Head set value [0f,0f,-50f]