#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [0f,0f,-7.0313f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [0f,0f,-4.1667f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [0f,0f,-1.6493f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [0f,0f,0.1329f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [0f,0f,0.2136f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [0f,0f,0.2458f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [0f,0f,0.2331f]