#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [0f,0f,-3.2977f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [0f,0f,-3.4913f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [0f,0f,-3.6602f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [0f,0f,-3.8006f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [0f,0f,-3.9089f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [0f,0f,-3.9815f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [0f,0f,-4.0146f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [0f,0f,-4.0045f]