#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.049 ^-1.471 ^0.141 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.042 ^-1.479 ^0.141 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.036 ^-1.486 ^0.141 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.032 ^-1.492 ^0.141 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.03 ^-1.494 ^0.141 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.032 ^-1.492 ^0.141 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.038 ^-1.486 ^0.141 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.046 ^-1.479 ^0.141 ~ ~