#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 160 run data modify entity @s Pose.Head set value [0f,0f,-141.3049f]
execute if score .this aj.frame matches 161 run data modify entity @s Pose.Head set value [0f,0f,-115.2904f]
execute if score .this aj.frame matches 162 run data modify entity @s Pose.Head set value [0f,0f,-90.2335f]
execute if score .this aj.frame matches 163 run data modify entity @s Pose.Head set value [0f,0f,-66.2767f]
execute if score .this aj.frame matches 164 run data modify entity @s Pose.Head set value [0f,0f,-43.5625f]
execute if score .this aj.frame matches 165 run data modify entity @s Pose.Head set value [0f,0f,-22.2335f]
execute if score .this aj.frame matches 166 run data modify entity @s Pose.Head set value [0f,0f,-2.432f]
execute if score .this aj.frame matches 167 run data modify entity @s Pose.Head set value [0f,0f,15.6994f]