#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [0f,0f,-3.8911f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [0f,0f,-4.3235f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [0f,0f,-4.7189f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [0f,0f,-5.0754f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [0f,0f,-5.3909f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [0f,0f,-5.6635f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [0f,0f,-5.891f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [0f,0f,-6.0716f]