#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run data modify entity @s Pose.Head set value [0f,0f,61.6562f]
execute if score .this aj.frame matches 137 run data modify entity @s Pose.Head set value [0f,0f,62.3666f]
execute if score .this aj.frame matches 138 run data modify entity @s Pose.Head set value [0f,0f,63.0019f]
execute if score .this aj.frame matches 139 run data modify entity @s Pose.Head set value [0f,0f,63.5646f]
execute if score .this aj.frame matches 140 run data modify entity @s Pose.Head set value [0f,0f,76.7697f]
execute if score .this aj.frame matches 141 run data modify entity @s Pose.Head set value [0f,0f,92.0098f]
execute if score .this aj.frame matches 142 run data modify entity @s Pose.Head set value [0f,0f,109.1424f]
execute if score .this aj.frame matches 143 run data modify entity @s Pose.Head set value [0f,0f,128.0251f]