#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [0f,0f,-2.1811f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [0f,0f,-1.8862f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [0f,0f,-1.5418f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [0f,0f,-1.1707f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [0f,0f,-0.796f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [0f,0f,-0.4407f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [0f,0f,-0.1276f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [0f,0f,0.1203f]