#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^-0.232 ^-1.572 ^-0.11 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^-0.251 ^-1.572 ^-0.11 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^-0.255 ^-1.572 ^-0.11 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^-0.22 ^-1.572 ^-0.11 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^-0.21 ^-1.572 ^-0.11 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^-0.198 ^-1.573 ^-0.11 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^-0.184 ^-1.574 ^-0.11 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^-0.17 ^-1.575 ^-0.11 ~ ~