#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [0f,0f,6.0012f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [0f,0f,14.2593f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [0f,0f,23.2812f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [0f,0f,31.5741f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,0f,37.6447f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [0f,0f,40f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [0f,0f,37.5f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [0f,0f,31.1111f]