#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [0f,0f,5.2778f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [0f,0f,-0.6344f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [0f,0f,-1.246f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [0f,0f,-1.8328f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [0f,0f,-2.3927f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [0f,0f,-2.9237f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [0f,0f,-3.4239f]