#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0.053 ^-1.471 ^-0.11 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0.059 ^-1.465 ^-0.11 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0.061 ^-1.463 ^-0.11 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.059 ^-1.465 ^-0.11 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.054 ^-1.47 ^-0.11 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.048 ^-1.477 ^-0.11 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.04 ^-1.484 ^-0.11 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0.034 ^-1.49 ^-0.11 ~ ~