#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [0f,0f,-12.1817f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [0f,0f,-11.2037f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [0f,0f,-9.5313f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [0f,0f,-7.1296f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [0f,0f,-3.9641f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [0f,0f,6.0012f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [0f,0f,14.2593f]