#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.004 ^-1.465 ^-0.11 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.001 ^-1.463 ^-0.11 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.006 ^-1.465 ^-0.11 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.012 ^-1.471 ^-0.11 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.017 ^-1.479 ^-0.11 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.022 ^-1.486 ^-0.11 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.027 ^-1.492 ^-0.11 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.032 ^-1.494 ^-0.11 ~ ~