#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [0f,0f,0.2799f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [0f,0f,0.3284f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [0f,0f,0.2427f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [0f,0f,-1.6493f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [0f,0f,-4.1667f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [0f,0f,-7.0312f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [0f,0f,-9.7222f]