#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [0f,0f,-11.7187f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [0f,0f,-12.5f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [0f,0f,-12.1817f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [0f,0f,-11.2037f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [0f,0f,-9.5313f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [0f,0f,-7.1296f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [0f,0f,-3.9641f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [0f,0f,0f]