#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.wheelguy.bone.footl] run function wheelguy:animations/idle/tree/footl_root_top
execute if entity @s[tag=aj.wheelguy.bone.legl] run function wheelguy:animations/idle/tree/legl_root_top
execute if entity @s[tag=aj.wheelguy.bone.wheel] run function wheelguy:animations/idle/tree/wheel_root_top
execute if entity @s[tag=aj.wheelguy.bone.footr] run function wheelguy:animations/idle/tree/footr_root_top
execute if entity @s[tag=aj.wheelguy.bone.legr] run function wheelguy:animations/idle/tree/legr_root_top
execute if entity @s[tag=aj.wheelguy.bone.wheel2] run function wheelguy:animations/idle/tree/wheel2_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame