#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 184 run tp @s ^0.138 ^-1.197 ^-0.007 ~ ~
execute if score .this aj.frame matches 185 run tp @s ^0.135 ^-1.23 ^-0.007 ~ ~
execute if score .this aj.frame matches 186 run tp @s ^0.125 ^-1.284 ^-0.007 ~ ~
execute if score .this aj.frame matches 187 run tp @s ^0.111 ^-1.364 ^-0.007 ~ ~
execute if score .this aj.frame matches 188 run tp @s ^0.097 ^-1.444 ^-0.007 ~ ~
execute if score .this aj.frame matches 189 run tp @s ^0.088 ^-1.499 ^-0.007 ~ ~
execute if score .this aj.frame matches 190 run tp @s ^0.088 ^-1.499 ^-0.007 ~ ~
execute if score .this aj.frame matches 191 run tp @s ^0.088 ^-1.499 ^-0.007 ~ ~