#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^-0.226 ^-1.495 ^-0.007 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^-0.226 ^-1.495 ^-0.007 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^-0.226 ^-1.495 ^-0.007 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^-0.226 ^-1.494 ^-0.007 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^-0.226 ^-1.494 ^-0.007 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^-0.225 ^-1.494 ^-0.007 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^-0.225 ^-1.494 ^-0.007 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^-0.225 ^-1.494 ^-0.007 ~ ~