#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.044 ^-1.476 ^0 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.038 ^-1.483 ^0 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.032 ^-1.491 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.027 ^-1.497 ^0 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.026 ^-1.499 ^0 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.028 ^-1.497 ^0 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0.034 ^-1.491 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0.041 ^-1.483 ^0 ~ ~