#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [0f,0f,14.3243f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [0f,0f,-12.5457f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [0f,0f,-39.2805f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [0f,0f,-65.7597f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [0f,0f,-91.8627f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [0f,0f,-117.469f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [0f,0f,-142.458f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [0f,0f,-166.7093f]