#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,0f,4.2732f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0f,0f,-8.3674f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [0f,0f,-22.8013f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0f,0f,-38.908f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0f,0f,-56.5668f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0f,0f,-75.6574f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,0f,-96.0592f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [0f,0f,-117.6516f]