#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run data modify entity @s Pose.Head set value [0f,0f,12.4825f]
execute if score .this aj.frame matches 137 run data modify entity @s Pose.Head set value [0f,0f,13.5446f]
execute if score .this aj.frame matches 138 run data modify entity @s Pose.Head set value [0f,0f,14.5017f]
execute if score .this aj.frame matches 139 run data modify entity @s Pose.Head set value [0f,0f,15.3555f]
execute if score .this aj.frame matches 140 run data modify entity @s Pose.Head set value [0f,0f,28.8204f]
execute if score .this aj.frame matches 141 run data modify entity @s Pose.Head set value [0f,0f,44.2882f]
execute if score .this aj.frame matches 142 run data modify entity @s Pose.Head set value [0f,0f,61.6154f]
execute if score .this aj.frame matches 143 run data modify entity @s Pose.Head set value [0f,0f,80.659f]