#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [0f,0f,-30f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [0f,0f,-25.6955f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [0f,0f,-21.6406f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [0f,0f,-17.7897f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [0f,0f,-14.0972f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [0f,0f,-10.5176f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [0f,0f,-7.0052f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [0f,0f,-3.5145f]