#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.167 ^-1.497 ^-0.007 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.172 ^-1.491 ^-0.007 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.177 ^-1.483 ^-0.007 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.183 ^-1.476 ^-0.007 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.188 ^-1.47 ^-0.007 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.193 ^-1.468 ^-0.007 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.198 ^-1.47 ^-0.007 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.204 ^-1.475 ^-0.007 ~ ~