#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^0.296 ^-1.517 ^0 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^0.285 ^-1.5 ^0 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^0.276 ^-1.48 ^0 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^0.257 ^-1.435 ^0 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^0.23 ^-1.379 ^0 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^0.199 ^-1.319 ^0 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^0.171 ^-1.266 ^0 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^0.151 ^-1.23 ^0 ~ ~