#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run tp @s ^-0.16 ^-1.574 ^-0.007 ~ ~
execute if score .this aj.frame matches 145 run tp @s ^-0.143 ^-1.575 ^-0.007 ~ ~
execute if score .this aj.frame matches 146 run tp @s ^-0.125 ^-1.577 ^-0.007 ~ ~
execute if score .this aj.frame matches 147 run tp @s ^-0.107 ^-1.58 ^-0.007 ~ ~
execute if score .this aj.frame matches 148 run tp @s ^-0.09 ^-1.583 ^-0.007 ~ ~
execute if score .this aj.frame matches 149 run tp @s ^-0.072 ^-1.586 ^-0.007 ~ ~
execute if score .this aj.frame matches 150 run tp @s ^-0.056 ^-1.588 ^-0.007 ~ ~
execute if score .this aj.frame matches 151 run tp @s ^-0.039 ^-1.589 ^-0.007 ~ ~