#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.125 ^-1.47 ^0 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.13 ^-1.468 ^0 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.136 ^-1.47 ^0 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.141 ^-1.476 ^0 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.146 ^-1.483 ^0 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.151 ^-1.491 ^0 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.156 ^-1.497 ^0 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.162 ^-1.499 ^0 ~ ~