#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.027 ^-1.501 ^-0.007 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.027 ^-1.501 ^-0.007 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.027 ^-1.5 ^-0.007 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.026 ^-1.499 ^-0.007 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.022 ^-1.495 ^-0.007 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.018 ^-1.489 ^-0.007 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.012 ^-1.481 ^-0.007 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.006 ^-1.475 ^-0.007 ~ ~