#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 208 run data modify entity @s Pose.Head set value [0f,0f,-91.2289f]
execute if score .this aj.frame matches 209 run data modify entity @s Pose.Head set value [0f,0f,-88.111f]
execute if score .this aj.frame matches 210 run data modify entity @s Pose.Head set value [0f,0f,-84.9287f]
execute if score .this aj.frame matches 211 run data modify entity @s Pose.Head set value [0f,0f,-81.6901f]
execute if score .this aj.frame matches 212 run data modify entity @s Pose.Head set value [0f,0f,-78.4035f]
execute if score .this aj.frame matches 213 run data modify entity @s Pose.Head set value [0f,0f,-75.077f]
execute if score .this aj.frame matches 214 run data modify entity @s Pose.Head set value [0f,0f,-71.7187f]
execute if score .this aj.frame matches 215 run data modify entity @s Pose.Head set value [0f,0f,-68.3369f]