#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [0f,0f,-170f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [0f,0f,-155.5046f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [0f,0f,-141.9878f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [0f,0f,-129.4043f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [0f,0f,-117.7083f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [0f,0f,-106.8544f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [0f,0f,-96.7969f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [0f,0f,-87.4902f]