#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [0f,0f,62.936f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0f,0f,65f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0f,0f,64.7492f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0f,0f,61.7901f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [0f,0f,55.7292f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [0f,0f,46.1728f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [0f,0f,32.7276f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [0f,0f,15f]