#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.088 ^-1.499 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.085 ^-1.495 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.08 ^-1.489 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.075 ^-1.481 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.069 ^-1.475 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.063 ^-1.47 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.057 ^-1.468 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.051 ^-1.47 ^0 ~ ~