#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function wheelguy:animations/idle/tree/wheel_root_0-63
execute if score .this aj.frame matches 64..127 run function wheelguy:animations/idle/tree/wheel_root_64-127
execute if score .this aj.frame matches 128..191 run function wheelguy:animations/idle/tree/wheel_root_128-191
execute if score .this aj.frame matches 192..239 run function wheelguy:animations/idle/tree/wheel_root_192-239