#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run data modify entity @s Pose.Head set value [0f,0f,-24.5907f]
execute if score .this aj.frame matches 169 run data modify entity @s Pose.Head set value [0f,0f,-11.2191f]
execute if score .this aj.frame matches 170 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 171 run data modify entity @s Pose.Head set value [0f,0f,-4.2959f]
execute if score .this aj.frame matches 172 run data modify entity @s Pose.Head set value [0f,0f,-9.9691f]
execute if score .this aj.frame matches 173 run data modify entity @s Pose.Head set value [0f,0f,-16.8229f]
execute if score .this aj.frame matches 174 run data modify entity @s Pose.Head set value [0f,0f,-24.6605f]
execute if score .this aj.frame matches 175 run data modify entity @s Pose.Head set value [0f,0f,-33.2851f]