#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 224 run data modify entity @s Pose.Head set value [0f,0f,-38.1862f]
execute if score .this aj.frame matches 225 run data modify entity @s Pose.Head set value [0f,0f,-35.0174f]
execute if score .this aj.frame matches 226 run data modify entity @s Pose.Head set value [0f,0f,-31.9149f]
execute if score .this aj.frame matches 227 run data modify entity @s Pose.Head set value [0f,0f,-28.8867f]
execute if score .this aj.frame matches 228 run data modify entity @s Pose.Head set value [0f,0f,-25.9411f]
execute if score .this aj.frame matches 229 run data modify entity @s Pose.Head set value [0f,0f,-23.0861f]
execute if score .this aj.frame matches 230 run data modify entity @s Pose.Head set value [0f,0f,-20.3299f]
execute if score .this aj.frame matches 231 run data modify entity @s Pose.Head set value [0f,0f,-17.6808f]