#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.226 ^-1.5 ^-0.007 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.226 ^-1.5 ^-0.007 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.226 ^-1.5 ^-0.007 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.226 ^-1.5 ^-0.007 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.226 ^-1.499 ^-0.007 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.226 ^-1.499 ^-0.007 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.226 ^-1.499 ^-0.007 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.226 ^-1.499 ^-0.007 ~ ~