#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.084 ^-1.483 ^-0.007 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.089 ^-1.491 ^-0.007 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.094 ^-1.497 ^-0.007 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.099 ^-1.499 ^-0.007 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.104 ^-1.497 ^-0.007 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.11 ^-1.491 ^-0.007 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.115 ^-1.483 ^-0.007 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.12 ^-1.476 ^-0.007 ~ ~