#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 160 run data modify entity @s Pose.Head set value [0f,0f,168.1389f]
execute if score .this aj.frame matches 161 run data modify entity @s Pose.Head set value [0f,0f,-166.4275f]
execute if score .this aj.frame matches 162 run data modify entity @s Pose.Head set value [0f,0f,-142f]
execute if score .this aj.frame matches 163 run data modify entity @s Pose.Head set value [0f,0f,-118.7221f]
execute if score .this aj.frame matches 164 run data modify entity @s Pose.Head set value [0f,0f,-96.7371f]
execute if score .this aj.frame matches 165 run data modify entity @s Pose.Head set value [0f,0f,-76.1881f]
execute if score .this aj.frame matches 166 run data modify entity @s Pose.Head set value [0f,0f,-57.2185f]
execute if score .this aj.frame matches 167 run data modify entity @s Pose.Head set value [0f,0f,-39.9716f]