#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 216 run tp @s ^0.088 ^-1.499 ^0 ~ ~
execute if score .this aj.frame matches 217 run tp @s ^0.088 ^-1.499 ^0 ~ ~
execute if score .this aj.frame matches 218 run tp @s ^0.088 ^-1.499 ^0 ~ ~
execute if score .this aj.frame matches 219 run tp @s ^0.088 ^-1.499 ^0 ~ ~
execute if score .this aj.frame matches 220 run tp @s ^0.088 ^-1.499 ^0 ~ ~
execute if score .this aj.frame matches 221 run tp @s ^0.088 ^-1.499 ^0 ~ ~
execute if score .this aj.frame matches 222 run tp @s ^0.088 ^-1.499 ^0 ~ ~
execute if score .this aj.frame matches 223 run tp @s ^0.088 ^-1.499 ^0 ~ ~