#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [0f,0f,-175.4771f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [0f,0f,-158.666f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [0f,0f,-141.5625f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [0f,0f,-124.2253f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [0f,0f,-106.713f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [0f,0f,-89.0842f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [0f,0f,-71.3977f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [0f,0f,-53.7119f]