#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^-0.224 ^-1.496 ^-0.007 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^-0.224 ^-1.497 ^-0.007 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^-0.224 ^-1.498 ^-0.007 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^-0.224 ^-1.499 ^-0.007 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^-0.224 ^-1.525 ^-0.007 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^-0.224 ^-1.56 ^-0.007 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^-0.224 ^-1.585 ^-0.007 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^-0.224 ^-1.577 ^-0.007 ~ ~