#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192 run data modify entity @s Pose.Head set value [0f,0f,-125.701f]
execute if score .this aj.frame matches 193 run data modify entity @s Pose.Head set value [0f,0f,-124.723f]
execute if score .this aj.frame matches 194 run data modify entity @s Pose.Head set value [0f,0f,-123.5501f]
execute if score .this aj.frame matches 195 run data modify entity @s Pose.Head set value [0f,0f,-122.1904f]
execute if score .this aj.frame matches 196 run data modify entity @s Pose.Head set value [0f,0f,-120.652f]
execute if score .this aj.frame matches 197 run data modify entity @s Pose.Head set value [0f,0f,-118.9432f]
execute if score .this aj.frame matches 198 run data modify entity @s Pose.Head set value [0f,0f,-117.0721f]
execute if score .this aj.frame matches 199 run data modify entity @s Pose.Head set value [0f,0f,-115.0468f]