#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^-0.226 ^-1.498 ^0 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^-0.226 ^-1.498 ^0 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^-0.226 ^-1.498 ^0 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^-0.226 ^-1.497 ^0 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^-0.226 ^-1.497 ^0 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^-0.226 ^-1.496 ^0 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^-0.226 ^-1.496 ^0 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^-0.226 ^-1.496 ^0 ~ ~