#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 216 run data modify entity @s Pose.Head set value [0f,0f,-64.9397f]
execute if score .this aj.frame matches 217 run data modify entity @s Pose.Head set value [0f,0f,-61.5352f]
execute if score .this aj.frame matches 218 run data modify entity @s Pose.Head set value [0f,0f,-58.1316f]
execute if score .this aj.frame matches 219 run data modify entity @s Pose.Head set value [0f,0f,-54.7371f]
execute if score .this aj.frame matches 220 run data modify entity @s Pose.Head set value [0f,0f,-51.3598f]
execute if score .this aj.frame matches 221 run data modify entity @s Pose.Head set value [0f,0f,-48.0079f]
execute if score .this aj.frame matches 222 run data modify entity @s Pose.Head set value [0f,0f,-44.6896f]
execute if score .this aj.frame matches 223 run data modify entity @s Pose.Head set value [0f,0f,-41.4129f]