#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run data modify entity @s Pose.Head set value [0f,0f,-54.3604f]
execute if score .this aj.frame matches 153 run data modify entity @s Pose.Head set value [0f,0f,-26.0353f]
execute if score .this aj.frame matches 154 run data modify entity @s Pose.Head set value [0f,0f,2.43f]
execute if score .this aj.frame matches 155 run data modify entity @s Pose.Head set value [0f,0f,30.892f]
execute if score .this aj.frame matches 156 run data modify entity @s Pose.Head set value [0f,0f,59.2076f]
execute if score .this aj.frame matches 157 run data modify entity @s Pose.Head set value [0f,0f,87.2333f]
execute if score .this aj.frame matches 158 run data modify entity @s Pose.Head set value [0f,0f,114.826f]
execute if score .this aj.frame matches 159 run data modify entity @s Pose.Head set value [0f,0f,141.8422f]