#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [0f,0f,67.5958f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [0f,0f,79.957f]
execute if score .this aj.frame matches 74 run data modify entity @s Pose.Head set value [0f,0f,93.0797f]
execute if score .this aj.frame matches 75 run data modify entity @s Pose.Head set value [0f,0f,106.9052f]
execute if score .this aj.frame matches 76 run data modify entity @s Pose.Head set value [0f,0f,121.3749f]
execute if score .this aj.frame matches 77 run data modify entity @s Pose.Head set value [0f,0f,136.4302f]
execute if score .this aj.frame matches 78 run data modify entity @s Pose.Head set value [0f,0f,152.0123f]
execute if score .this aj.frame matches 79 run data modify entity @s Pose.Head set value [0f,0f,168.0628f]