#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
execute store result score @s aj.id run scoreboard players add .aj.last_id aj.i 1
execute at @s run function amirkaka:summon/zzz/execute/3
tag @s remove new
scoreboard players set @s aj.amirkaka.idle1.loopMode 0
scoreboard players set @s aj.amirkaka.idle2.loopMode 0
scoreboard players set @s aj.amirkaka.idle3.loopMode 0
scoreboard players set @s aj.amirkaka.idle4.loopMode 0
scoreboard players set @s aj.amirkaka.idle5.loopMode 0
scoreboard players set @s aj.amirkaka.fall.loopMode 0
scoreboard players set @s aj.frame 0
scoreboard players set @s aj.amirkaka.animating 0