#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['new','aj.bluejay','aj.bluejay.root']}
execute as @e[type=minecraft:marker,tag=aj.bluejay.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function bluejay:summon/zzz/execute/2
function bluejay:assert_animation_flags