#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['new','aj.amirkaka','aj.amirkaka.root']}
execute as @e[type=minecraft:marker,tag=aj.amirkaka.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function amirkaka:summon/zzz/execute/2
function amirkaka:assert_animation_flags