#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.boat.new.loopMode matches 0 run function boat:animations/new/stop
execute if score @s aj.boat.new.loopMode matches 1 run function boat:animations/new/pause
execute if score @s aj.boat.new.loopMode matches 2 run function boat:animations/new/zzz/execute/13