#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if score @s aj.frame matches ..1 run function bluejay:animations/fly/zzz/conditional/14
execute if score #execute aj.i matches 0 run function bluejay:animations/fly/zzz/conditional/15