#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-1.8171f,0.3554f,7.1092f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-0.722f,0.3085f,6.6726f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0.4689f,0.2668f,6.1054f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [1.6775f,0.2318f,5.4335f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [2.8255f,0.2035f,4.6832f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [3.9063f,0.1751f,3.8807f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [4.853f,0.1458f,3.0521f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [5.6115f,0.114f,2.2237f]