#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-0.0993f,-0.0086f,-0.2098f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-0.2657f,-0.019f,-0.5075f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-0.4582f,-0.0283f,-0.8638f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-0.6356f,-0.0343f,-1.2495f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-0.7567f,-0.0358f,-1.6354f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-0.7803f,-0.0326f,-1.9919f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-0.6652f,-0.0254f,-2.2899f]