#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [4.3089f,-0.0302f,-2.4998f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [3.8707f,-0.0686f,-2.1096f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [3.1347f,-0.1143f,-1.5341f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [2.1794f,-0.1606f,-0.8349f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [1.0838f,-0.2021f,-0.0736f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-0.0731f,-0.2351f,0.6883f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-1.2124f,-0.2578f,1.3888f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-2.255f,-0.2702f,1.9662f]