#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-1.969 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-1.966 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-1.961 ^-0.001 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-1.955 ^-0.002 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-1.948 ^-0.003 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-1.941 ^-0.003 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-1.933 ^-0.004 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-1.925 ^-0.005 ~ ~