#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-1.916 ^-0.006 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.907 ^-0.006 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-1.899 ^-0.007 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-1.89 ^-0.007 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-1.882 ^-0.007 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-1.874 ^-0.007 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-1.867 ^-0.006 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-1.861 ^-0.006 ~ ~