#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^0 ^-1.48 ^0.007 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^0 ^-1.476 ^0.006 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-1.472 ^0.005 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0 ^-1.47 ^0.003 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0 ^-1.469 ^0.002 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0 ^-1.47 ^0.001 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0 ^-1.472 ^-0.001 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^0 ^-1.476 ^-0.002 ~ ~