#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^-1.48 ^-0.003 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^-1.486 ^-0.005 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^-1.492 ^-0.006 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^-1.5 ^-0.007 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^-1.507 ^-0.008 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^-1.516 ^-0.009 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0 ^-1.524 ^-0.009 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0 ^-1.533 ^-0.01 ~ ~