#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-1.541 ^0.008 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.533 ^0.009 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-1.524 ^0.01 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-1.516 ^0.01 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-1.507 ^0.01 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-1.5 ^0.009 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-1.492 ^0.009 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-1.486 ^0.008 ~ ~