#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-1.594 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-1.591 ^0.001 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-1.586 ^0.001 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-1.58 ^0.002 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-1.573 ^0.004 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-1.566 ^0.005 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-1.558 ^0.006 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-1.55 ^0.007 ~ ~