#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function glare:animations/idle/tree/head_display_0-7
execute if score .this aj.frame matches 8..15 run function glare:animations/idle/tree/head_display_8-15
execute if score .this aj.frame matches 16..23 run function glare:animations/idle/tree/head_display_16-23
execute if score .this aj.frame matches 24..31 run function glare:animations/idle/tree/head_display_24-31
execute if score .this aj.frame matches 32..39 run function glare:animations/idle/tree/head_display_32-39