#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [3.3349f,0f,0f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [2.7565f,0f,0f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [2.1791f,0f,0f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [1.6133f,0f,0f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [1.07f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0.56f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0.094f,0f,0f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-0.3172f,0f,0f]