#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.5 ^-1.17 ^-0.486 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.5 ^-1.181 ^-0.491 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.5 ^-1.192 ^-0.495 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.5 ^-1.204 ^-0.499 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.5 ^-1.217 ^-0.502 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.5 ^-1.229 ^-0.506 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.5 ^-1.242 ^-0.509 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.5 ^-1.254 ^-0.511 ~ ~