#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^0 ^-1.699 ^-0.016 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^0 ^-1.704 ^-0.015 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^0 ^-1.711 ^-0.014 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^0 ^-1.718 ^-0.013 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^-1.726 ^-0.012 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0 ^-1.734 ^-0.011 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0 ^-1.743 ^-0.01 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0 ^-1.752 ^-0.008 ~ ~