#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0 ^-1.76 ^-0.007 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0 ^-1.769 ^-0.006 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0 ^-1.777 ^-0.005 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0 ^-1.785 ^-0.004 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0 ^-1.792 ^-0.003 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0 ^-1.799 ^-0.002 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0 ^-1.804 ^-0.001 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0 ^-1.809 ^-0.001 ~ ~