#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-1.759 ^-0.009 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.751 ^-0.011 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-1.742 ^-0.012 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-1.733 ^-0.014 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-1.725 ^-0.015 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-1.717 ^-0.016 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-1.71 ^-0.017 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-1.703 ^-0.018 ~ ~