#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function glare:animations/idle/tree/outer_root_0-7
execute if score .this aj.frame matches 8..15 run function glare:animations/idle/tree/outer_root_8-15
execute if score .this aj.frame matches 16..23 run function glare:animations/idle/tree/outer_root_16-23
execute if score .this aj.frame matches 24..31 run function glare:animations/idle/tree/outer_root_24-31
execute if score .this aj.frame matches 32..39 run function glare:animations/idle/tree/outer_root_32-39