#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [4.5576f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [5.1563f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [5.6777f,0f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [6.097f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [6.3889f,0f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [6.6004f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [6.7175f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [6.7392f,0f,0f]