#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0.175 ^-1.463 ^9.224 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.181 ^-1.001 ^8.671 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.188 ^-0.581 ^8.183 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.185 ^-0.193 ^7.614 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.168 ^0.121 ^6.995 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.14 ^0.365 ^6.343 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.106 ^0.544 ^5.676 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.071 ^0.66 ^5.01 ~ ~