#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^-0.004 ^-1.12 ^0.289 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^-0.001 ^-1.471 ^-0.004 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^0 ^-1.134 ^0.506 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^0 ^-1.202 ^-0.479 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^0 ^-1.105 ^-0.358 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^0 ^-1.075 ^-0.332 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^0 ^-1.034 ^-0.297 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^0 ^-0.986 ^-0.256 ~ ~