#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.038 ^0.716 ^4.363 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.011 ^0.713 ^3.751 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^-0.005 ^0.65 ^3.203 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^-0.014 ^0.498 ^2.681 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^-0.018 ^0.264 ^2.152 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^-0.018 ^-0.033 ^1.63 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^-0.014 ^-0.376 ^1.132 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^-0.009 ^-0.746 ^0.677 ~ ~