#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 96..103 run function amirkaka:animations/fall/tree/body_display_96-103
execute if score .this aj.frame matches 104..111 run function amirkaka:animations/fall/tree/body_display_104-111
execute if score .this aj.frame matches 112..119 run function amirkaka:animations/fall/tree/body_display_112-119
execute if score .this aj.frame matches 120..127 run function amirkaka:animations/fall/tree/body_display_120-127