#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^0 ^-8.96 ^0 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^0 ^-9.374 ^0 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^0 ^-9.787 ^0 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^0 ^-10.201 ^0 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^0 ^-10.614 ^0 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^0 ^-11.028 ^0 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^0 ^-11.442 ^0 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^0 ^-11.855 ^0 ~ ~