#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0 ^-5.651 ^0 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0 ^-6.065 ^0 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0 ^-6.478 ^0 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0 ^-6.892 ^0 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0 ^-7.306 ^0 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0 ^-7.719 ^0 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0 ^-8.133 ^0 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0 ^-8.546 ^0 ~ ~