#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [-55.2225f,0.3538f,-179.8231f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [-43.0013f,0.0575f,-179.9712f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [117.6656f,0f,-180f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [-93.0624f,0f,-180f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [-101.3484f,0f,-180f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [-107.0667f,0f,-180f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [-114.6994f,0f,-180f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [-123.7179f,0f,-180f]