#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.amirkaka.bone.head] run function amirkaka:animations/fall/tree/head_display_top
execute if entity @s[tag=aj.amirkaka.bone.body] run function amirkaka:animations/fall/tree/body_display_top
execute if entity @s[tag=aj.amirkaka.bone.rightarm] run function amirkaka:animations/fall/tree/rightarm_display_top
execute if entity @s[tag=aj.amirkaka.bone.leftarm] run function amirkaka:animations/fall/tree/leftarm_display_top
execute if entity @s[tag=aj.amirkaka.bone.leftleg] run function amirkaka:animations/fall/tree/leftleg_display_top
execute if entity @s[tag=aj.amirkaka.bone.rightleg] run function amirkaka:animations/fall/tree/rightleg_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~