#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [-111.25f,0f,-180f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [-126.3279f,0f,-180f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [-141.2f,0f,-180f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [-155.023f,0f,-180f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [-166.9534f,0f,-180f]
execute if score .this aj.frame matches 133 run data modify entity @s Pose.Head set value [-176.1476f,0f,-180f]
execute if score .this aj.frame matches 134 run data modify entity @s Pose.Head set value [171.7383f,0f,-180f]
execute if score .this aj.frame matches 135 run data modify entity @s Pose.Head set value [179.1968f,0f,-180f]