#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-0.012 ^-0.247 ^0.14 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-0.012 ^-0.247 ^0.14 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-0.012 ^-0.247 ^0.14 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-0.012 ^-0.242 ^0.125 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-0.012 ^-0.233 ^0.099 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-0.012 ^-0.224 ^0.073 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-0.012 ^-0.216 ^0.047 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-0.012 ^-0.207 ^0.02 ~ ~