#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [-155.5187f,-24.8967f,167.5516f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [-149.2276f,-22.5634f,168.7183f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [-145.004f,-21.978f,169.011f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [-141.9937f,-20.5969f,169.7016f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [-140.0185f,-18.0324f,170.9838f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [-138.6745f,-14.6733f,172.6634f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [-137.5574f,-10.9082f,174.5459f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [-136.2633f,-7.1258f,176.4371f]