#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192..199 run function amirkaka:animations/fall/tree/head_root_192-199
execute if score .this aj.frame matches 200 run tp @s ^-0.012 ^-0.185 ^0.015 ~ ~