#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run tp @s ^0.012 ^-0.185 ^0.041 ~ ~
execute if score .this aj.frame matches 145 run tp @s ^0.012 ^-0.185 ^0.038 ~ ~
execute if score .this aj.frame matches 146 run tp @s ^0.012 ^-0.185 ^0.035 ~ ~
execute if score .this aj.frame matches 147 run tp @s ^0.012 ^-0.185 ^0.031 ~ ~
execute if score .this aj.frame matches 148 run tp @s ^0.012 ^-0.185 ^0.028 ~ ~
execute if score .this aj.frame matches 149 run tp @s ^0.012 ^-0.185 ^0.024 ~ ~
execute if score .this aj.frame matches 150 run tp @s ^0.012 ^-0.185 ^0.021 ~ ~
execute if score .this aj.frame matches 151 run tp @s ^0.012 ^-0.185 ^0.018 ~ ~