#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192..199 run function amirkaka:animations/fall/tree/head_display_192-199
execute if score .this aj.frame matches 200 run data modify entity @s Pose.Head set value [0f,0f,0f]