#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0.289 ^-1.23 ^8.904 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.302 ^-0.81 ^8.326 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.317 ^-0.419 ^7.826 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.313 ^-0.054 ^7.248 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.286 ^0.241 ^6.619 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.241 ^0.47 ^5.957 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.187 ^0.635 ^5.282 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.129 ^0.738 ^4.609 ~ ~