#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [57.2275f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [58.7164f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [59.0666f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [58.6004f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [57.64f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [56.5078f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [55.5259f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [55.0168f,0f,0f]