#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [55f,0f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [50.4167f,0f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [42.7778f,0f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [35.1389f,0f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [27.5f,0f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [19.8611f,0f,0f]