#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.012 ^-6.352 ^11.618 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.032 ^-5.69 ^12.006 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.059 ^-4.995 ^12.075 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.037 ^-4.278 ^11.878 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.029 ^-3.563 ^11.471 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.117 ^-2.883 ^10.91 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0.2 ^-2.261 ^10.254 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0.259 ^-1.711 ^9.565 ~ ~