#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.012 ^-5.242 ^-0.047 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.012 ^-5.655 ^-0.047 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.012 ^-6.069 ^-0.047 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.012 ^-6.482 ^-0.047 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.012 ^-6.896 ^-0.047 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.012 ^-7.31 ^-0.047 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.012 ^-7.723 ^-0.047 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.012 ^-8.137 ^-0.047 ~ ~