#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192 run data modify entity @s Pose.Head set value [0f,15f,0f]
execute if score .this aj.frame matches 193 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 194 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 195 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 196 run data modify entity @s Pose.Head set value [0f,15f,0f]
execute if score .this aj.frame matches 197 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 198 run data modify entity @s Pose.Head set value [0f,-15f,0f]
execute if score .this aj.frame matches 199 run data modify entity @s Pose.Head set value [0f,-7.5f,0f]