#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.012 ^-0.604 ^-0.047 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.012 ^-1.047 ^-0.047 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.012 ^-1.49 ^-0.047 ~ ~