#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^0.012 ^-0.724 ^-0.446 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^0.012 ^-0.605 ^-0.337 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^0.012 ^-0.489 ^-0.231 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^0.012 ^-0.381 ^-0.133 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^0.012 ^-0.288 ^-0.048 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^0.012 ^-0.216 ^0.018 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^0.012 ^-0.116 ^0.108 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^0.012 ^-0.178 ^0.053 ~ ~