#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^-0.012 ^-8.55 ^-0.047 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^-0.012 ^-8.964 ^-0.047 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^-0.012 ^-9.378 ^-0.047 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.012 ^-9.791 ^-0.047 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.012 ^-10.205 ^-0.047 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.012 ^-10.618 ^-0.047 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.012 ^-11.032 ^-0.047 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.012 ^-11.446 ^-0.047 ~ ~