#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [-97.7225f,0.3538f,-179.8231f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [-85.5013f,0.0575f,-179.9712f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [113.9156f,0f,-180f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [-57.2858f,0f,-180f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [-65.7507f,0f,-180f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [-73.2168f,0f,-180f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [-83.851f,0f,-180f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [-96.8099f,0f,-180f]