#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [0f,0f,-3.0769f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [0f,0f,-2.8846f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [0f,0f,-2.6923f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [0f,0f,-2.5f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [0f,0f,-2.3077f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [0f,0f,-2.1154f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [0f,0f,-1.9231f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [0f,0f,-1.7308f]