#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128..135 run function amirkaka:animations/fall/tree/leftleg_display_128-135
execute if score .this aj.frame matches 152..159 run function amirkaka:animations/fall/tree/leftleg_display_152-159
execute if score .this aj.frame matches 160..167 run function amirkaka:animations/fall/tree/leftleg_display_160-167