#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^-0.065 ^-1.691 ^9.537 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^-0.066 ^-1.178 ^9.01 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^-0.064 ^-0.726 ^8.532 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^-0.066 ^-0.312 ^7.974 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^-0.073 ^0.025 ^7.369 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^-0.083 ^0.289 ^6.732 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^-0.094 ^0.486 ^6.08 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^-0.105 ^0.621 ^5.428 ~ ~