#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [161.0271f,-16.5897f,-39.7089f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [-162.8762f,-22.7415f,168.1582f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [75.4017f,-14.3362f,-2.9715f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [-5.6064f,-10.6059f,25.2353f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [32.3015f,-16.8082f,108.0664f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [70.6823f,-24.1337f,158.7419f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [84.8244f,20.3148f,10.9195f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [22.5568f,-15.4979f,14.5692f]