#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [-33.3265f,16.754f,55.5322f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [63.0694f,-0.3805f,150.6631f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [122.851f,10.9474f,163.9899f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [51.2578f,-0.4403f,17.7733f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [-18.2261f,-3.3273f,38.0054f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [-37.8346f,36.2979f,69.5564f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [81.553f,-2.3831f,170.8973f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [142.0373f,56.9043f,163.6012f]