#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.125 ^-7.14 ^11.934 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^-0.123 ^-6.516 ^12.227 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^-0.115 ^-5.831 ^12.264 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^-0.103 ^-5.109 ^12.087 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.089 ^-4.372 ^11.739 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.077 ^-3.642 ^11.264 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.068 ^-2.94 ^10.709 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.065 ^-2.284 ^10.118 ~ ~