#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 155 run data modify entity @s Pose.Head set value [180f,0f,157.5f]
execute if score .this aj.frame matches 156 run data modify entity @s Pose.Head set value [169.5581f,23.6317f,155.3098f]
execute if score .this aj.frame matches 157 run data modify entity @s Pose.Head set value [148.657f,51.469f,142.0975f]
execute if score .this aj.frame matches 158 run data modify entity @s Pose.Head set value [90f,67.5f,90f]
execute if score .this aj.frame matches 159 run data modify entity @s Pose.Head set value [31.343f,51.469f,37.9025f]