#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [-177.5f,0f,-180f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [180f,0f,-180f]