#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^-0.115 ^0.697 ^4.791 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^-0.122 ^0.72 ^4.186 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^-0.126 ^0.688 ^3.64 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^-0.129 ^0.563 ^3.117 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^-0.13 ^0.353 ^2.584 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^-0.13 ^0.082 ^2.056 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^-0.129 ^-0.229 ^1.547 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^-0.127 ^-0.554 ^1.073 ~ ~