#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^-0.283 ^0.768 ^3.969 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^-0.326 ^0.755 ^3.369 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^-0.352 ^0.669 ^2.829 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^-0.367 ^0.496 ^2.314 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^-0.373 ^0.241 ^1.792 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^-0.372 ^-0.081 ^1.278 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^-0.366 ^-0.457 ^0.792 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^-0.358 ^-0.869 ^0.357 ~ ~