#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [0f,0f,-137.5f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [0f,0f,-137.6138f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [0f,0f,-138.7546f]