#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^-0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^-0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^-0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^-0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^-0.31 ^-0.375 ^0.149 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^-0.183 ^-0.375 ^0.291 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^0 ^-0.375 ^0.343 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^0.183 ^-0.375 ^0.291 ~ ~