#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [0f,0f,-140.7772f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [0f,0f,-143.255f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [0f,0f,-145.7613f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [0f,0f,-147.8693f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [0f,0f,-149.1523f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [0f,0f,-149.1835f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [0f,0f,-147.5364f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [0f,0f,-143.7841f]