#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [-113.0187f,-24.8967f,167.5516f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [-106.7276f,-22.5634f,168.7183f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [-102.504f,-21.978f,169.011f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [-99.4937f,-20.5969f,169.7016f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [-97.5185f,-18.0324f,170.9838f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [-96.1745f,-14.6733f,172.6634f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [-95.0574f,-10.9082f,174.5459f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [-93.7633f,-7.1258f,176.4371f]