#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^-0.126 ^-0.87 ^0.649 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^-0.125 ^-1.151 ^0.295 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^-0.125 ^-1.265 ^0.25 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^-0.125 ^-1.173 ^-0.108 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^-0.125 ^-1.125 ^0.011 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^-0.125 ^-1.125 ^0.023 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^-0.125 ^-1.125 ^0.035 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^-0.125 ^-1.125 ^0.047 ~ ~