#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [28.523f,-23.1732f,36.4236f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [-51.2392f,0.9926f,50.9941f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [-35.396f,55.126f,80.476f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [103.5694f,-0.6088f,-176.4019f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [-11.3791f,77.8485f,-3.8822f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [-0.0181f,-16.9464f,50.4987f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [-76.1942f,23.5939f,50.1175f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [55.5751f,74.6906f,159.1564f]