#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [87.3087f,-15.1967f,-81.9466f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [103.8607f,-12.483f,-103.474f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [120.4127f,-9.7693f,-125.0014f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [136.9647f,-7.0556f,-146.5288f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [153.5168f,-4.3419f,-168.0562f]
execute if score .this aj.frame matches 133 run data modify entity @s Pose.Head set value [170.0688f,-1.6282f,170.4164f]
execute if score .this aj.frame matches 134 run data modify entity @s Pose.Head set value [180f,0f,157.5f]