#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [-91.888f,-3.7148f,178.1426f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [-89.0274f,-1.064f,179.468f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [-85.0169f,0.4989f,-179.7505f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [-81.5592f,1.3169f,-179.3416f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [-78.4782f,1.6252f,-179.1874f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [-75.0389f,1.5535f,-179.2232f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [-70.5064f,1.2314f,-179.3843f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [-64.1459f,0.7883f,-179.6059f]