#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [-128.7553f,78.7743f,81.8345f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [79.4508f,27.5141f,-162.9978f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [-20.3932f,-0.8378f,160.2245f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [157.0492f,13.7818f,-177.8672f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [154.5423f,12.6016f,-177.0647f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [157.1941f,11.289f,-175.0267f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [159.846f,9.9763f,-172.9887f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [162.4978f,8.6636f,-170.9507f]