#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [-55.2225f,0.3538f,-179.8231f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [-43.0013f,0.0575f,-179.9712f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [76.4156f,0f,-180f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [-174.9895f,0f,-180f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [180f,0f,-180f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [175f,0f,173.75f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [170f,0f,167.5f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [174.9977f,-0.1085f,168.1155f]