#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [158.1716f,-12.497f,-28.3793f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [156.6511f,14.409f,-13.8805f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [149.3826f,-11.2494f,-75.291f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [123.7949f,57.8117f,-20.6933f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [25.8829f,20.2419f,76.7642f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [-81.4612f,-5.7495f,75.7637f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [19.006f,-24.0588f,157.4142f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [134.1902f,14.5173f,170.7434f]