#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [11.6347f,86.0568f,-49.8431f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [-38.0798f,48.2711f,71.7515f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [-65.2874f,25.1727f,111.1942f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [65.1741f,-16.9236f,178.3922f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [-168.4243f,37.2877f,-163.1054f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [-5.07f,67.8556f,-39.6921f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [-83.9794f,48.6041f,76.2886f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [-40.4203f,35.6968f,133.9644f]