#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [0f,0f,-22.5f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [0f,0f,77.5f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [0f,0f,137.5f]