#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.135 ^0.705 ^4.808 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.128 ^0.722 ^4.19 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^0.124 ^0.687 ^3.638 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^0.121 ^0.56 ^3.111 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^0.12 ^0.35 ^2.577 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^0.12 ^0.078 ^2.049 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^0.121 ^-0.231 ^1.542 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^0.123 ^-0.556 ^1.069 ~ ~