#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0.157 ^-1.642 ^9.642 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.161 ^-1.133 ^9.106 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.163 ^-0.682 ^8.626 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.164 ^-0.27 ^8.062 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.162 ^0.062 ^7.446 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.157 ^0.32 ^6.796 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.15 ^0.509 ^6.127 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.142 ^0.636 ^5.459 ~ ~