#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^0.344 ^-0.844 ^-0.313 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^0.344 ^-0.761 ^-0.257 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^0.344 ^-0.677 ^-0.201 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^0.344 ^-0.593 ^-0.145 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^0.344 ^-0.509 ^-0.09 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^0.344 ^-0.426 ^-0.034 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^0.344 ^-0.375 ^0 ~ ~