#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.344 ^-6.52 ^11.645 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0.302 ^-5.81 ^12.117 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.256 ^-5.058 ^12.233 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.258 ^-4.301 ^12.062 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.311 ^-3.582 ^11.674 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.392 ^-2.897 ^11.12 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0.475 ^-2.271 ^10.462 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0.537 ^-1.715 ^9.765 ~ ~