#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.403 ^0.785 ^4.006 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.362 ^0.756 ^3.372 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^0.335 ^0.661 ^2.814 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^0.32 ^0.483 ^2.289 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^0.314 ^0.226 ^1.763 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^0.315 ^-0.095 ^1.25 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^0.321 ^-0.469 ^0.769 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^0.329 ^-0.878 ^0.342 ~ ~