#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [179.9953f,-0.217f,168.731f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [-175.007f,-0.3255f,169.3465f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [-170.0093f,-0.434f,169.9621f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [-175.0047f,-0.217f,174.981f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [180f,0f,-180f]