#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.125 ^-7.14 ^11.934 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0.114 ^-6.481 ^12.299 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.101 ^-5.779 ^12.379 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.097 ^-5.049 ^12.224 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.105 ^-4.31 ^11.884 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.119 ^-3.58 ^11.406 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0.136 ^-2.881 ^10.841 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0.149 ^-2.23 ^10.236 ~ ~