#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [92.6134f,-2.7997f,-167.1564f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [-98.7788f,58.5099f,-114.7503f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [-25.4677f,52.0582f,-19.2238f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [-122.0173f,54.1993f,76.9449f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [8.1666f,39.8212f,163.4927f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [129.8842f,2.4128f,-159.5266f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [-47.654f,42.7997f,-80.9393f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [-82.1288f,50.0291f,-28.7712f]