#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^0.113 ^-1.125 ^-0.055 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^0.067 ^-1.125 ^-0.106 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^0 ^-1.125 ^-0.125 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^-0.066 ^-1.125 ^-0.106 ~ ~