#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^-0.344 ^-8.71 ^0 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^-0.344 ^-9.124 ^0 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^-0.344 ^-9.538 ^0 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^-0.344 ^-9.952 ^0 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^-0.344 ^-10.367 ^0 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^-0.344 ^-10.782 ^0 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^-0.344 ^-11.196 ^0 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^-0.344 ^-11.61 ^0 ~ ~