#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.125 ^-2.722 ^0 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.125 ^-3.138 ^0 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.125 ^-3.554 ^0 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.125 ^-3.97 ^0 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.125 ^-4.386 ^0 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.125 ^-4.802 ^0 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.125 ^-5.218 ^0 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.125 ^-5.634 ^0 ~ ~