#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 160 run tp @s ^-0.31 ^-0.375 ^-0.149 ~ ~
execute if score .this aj.frame matches 161 run tp @s ^-0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 162 run tp @s ^-0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 163 run tp @s ^-0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 164 run tp @s ^-0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 165 run tp @s ^-0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 166 run tp @s ^-0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 167 run tp @s ^-0.344 ^-0.375 ^0 ~ ~