#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192 run tp @s ^-0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 193 run tp @s ^-0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 194 run tp @s ^-0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 195 run tp @s ^-0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 196 run tp @s ^-0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 197 run tp @s ^-0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 198 run tp @s ^-0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 199 run tp @s ^-0.125 ^-1.125 ^0 ~ ~