#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [0f,0f,137.5f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [0f,0f,133.5791f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [0f,0f,106.2829f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [0f,0f,68.75f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [0f,0f,24.5023f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [0f,0f,-22.9386f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [0f,0f,-70.0507f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [0f,0f,-113.3124f]