#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function amirkaka:animations/fall/tree/rightarm_display_64-71
execute if score .this aj.frame matches 88..95 run function amirkaka:animations/fall/tree/rightarm_display_88-95
execute if score .this aj.frame matches 96..103 run function amirkaka:animations/fall/tree/rightarm_display_96-103
execute if score .this aj.frame matches 104..111 run function amirkaka:animations/fall/tree/rightarm_display_104-111
execute if score .this aj.frame matches 112..119 run function amirkaka:animations/fall/tree/rightarm_display_112-119
execute if score .this aj.frame matches 120..127 run function amirkaka:animations/fall/tree/rightarm_display_120-127