#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.125 ^-6.05 ^0 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.125 ^-6.466 ^0 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.125 ^-6.882 ^0 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.125 ^-7.298 ^0 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.125 ^-7.714 ^0 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.125 ^-8.13 ^0 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.125 ^-8.546 ^0 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.125 ^-8.962 ^0 ~ ~