#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 304 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 305 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 306 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 307 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 308 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 309 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 310 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 311 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~