#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 296 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 297 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 298 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 299 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 300 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 301 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 302 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 303 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~