#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 392 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 393 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 394 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 395 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 396 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 397 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 398 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 399 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~