#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 288 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 289 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 290 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 291 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 292 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 293 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 294 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~
execute if score .this aj.frame matches 295 run tp @s ^-0.031 ^-1.188 ^0.219 ~ ~