#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 184 run data modify entity @s Pose.Head set value [-171.0703f,23.151f,-164.2599f]
execute if score .this aj.frame matches 185 run data modify entity @s Pose.Head set value [-177.5465f,29.8352f,-169.5938f]
execute if score .this aj.frame matches 186 run data modify entity @s Pose.Head set value [172.541f,37.4396f,-179.8702f]
execute if score .this aj.frame matches 187 run data modify entity @s Pose.Head set value [161.4686f,45.4827f,167.6301f]
execute if score .this aj.frame matches 188 run data modify entity @s Pose.Head set value [151.513f,53.4829f,155.6264f]
execute if score .this aj.frame matches 189 run data modify entity @s Pose.Head set value [144.9508f,60.9586f,146.838f]
execute if score .this aj.frame matches 190 run data modify entity @s Pose.Head set value [144.0586f,67.4283f,143.9843f]
execute if score .this aj.frame matches 191 run data modify entity @s Pose.Head set value [151.1129f,72.4105f,149.7845f]