#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192 run tp @s ^1.084 ^1.047 ^-2.235 ~ ~
execute if score .this aj.frame matches 193 run tp @s ^0.967 ^1.122 ^-2.454 ~ ~
execute if score .this aj.frame matches 194 run tp @s ^0.828 ^1.189 ^-2.653 ~ ~
execute if score .this aj.frame matches 195 run tp @s ^0.668 ^1.242 ^-2.823 ~ ~
execute if score .this aj.frame matches 196 run tp @s ^0.481 ^1.278 ^-2.958 ~ ~
execute if score .this aj.frame matches 197 run tp @s ^0.263 ^1.291 ^-3.053 ~ ~
execute if score .this aj.frame matches 198 run tp @s ^0.005 ^1.28 ^-3.104 ~ ~
execute if score .this aj.frame matches 199 run tp @s ^-0.319 ^1.247 ^-3.113 ~ ~