#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [0.3283f,1.9218f,0f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [0.3436f,1.966f,0f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [0.3584f,2.0073f,0f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [0.3726f,2.0456f,0f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [0.3862f,2.0806f,0f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [0.399f,2.1123f,0f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [0.411f,2.1403f,0f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [0.4222f,2.1645f,0f]