#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [-99.8293f,-72.8452f,95.581f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [-107.7254f,-75.3165f,103.9405f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [-115.2825f,-77.3217f,111.9799f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [-122.4101f,-78.7911f,119.6066f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [-129.0177f,-79.655f,126.7277f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [-135.0148f,-79.8437f,133.2505f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [-140.3109f,-79.2877f,139.0823f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [-144.8157f,-77.9171f,144.1302f]