#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 328 run tp @s ^0.438 ^-1.407 ^-0.078 ~ ~
execute if score .this aj.frame matches 329 run tp @s ^0.438 ^-1.407 ^-0.078 ~ ~
execute if score .this aj.frame matches 330 run tp @s ^0.438 ^-1.407 ^-0.078 ~ ~
execute if score .this aj.frame matches 331 run tp @s ^0.438 ^-1.407 ^-0.078 ~ ~
execute if score .this aj.frame matches 332 run tp @s ^0.438 ^-1.407 ^-0.078 ~ ~
execute if score .this aj.frame matches 333 run tp @s ^0.438 ^-1.407 ^-0.078 ~ ~
execute if score .this aj.frame matches 334 run tp @s ^0.438 ^-1.407 ^-0.078 ~ ~
execute if score .this aj.frame matches 335 run tp @s ^0.438 ^-1.407 ^-0.078 ~ ~