#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0.76 ^-1.383 ^1 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.777 ^-1.352 ^1.018 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.791 ^-1.31 ^1.04 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.803 ^-1.258 ^1.066 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.815 ^-1.193 ^1.096 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.831 ^-1.119 ^1.13 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.852 ^-1.036 ^1.168 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.879 ^-0.948 ^1.21 ~ ~