#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run tp @s ^1.054 ^0.047 ^1.095 ~ ~
execute if score .this aj.frame matches 169 run tp @s ^1.057 ^0.014 ^1.086 ~ ~
execute if score .this aj.frame matches 170 run tp @s ^1.056 ^-0.02 ^1.083 ~ ~
execute if score .this aj.frame matches 171 run tp @s ^1.052 ^-0.043 ^1.084 ~ ~
execute if score .this aj.frame matches 172 run tp @s ^1.042 ^-0.058 ^1.122 ~ ~
execute if score .this aj.frame matches 173 run tp @s ^1.028 ^-0.071 ^1.192 ~ ~
execute if score .this aj.frame matches 174 run tp @s ^1.021 ^-0.072 ^1.241 ~ ~
execute if score .this aj.frame matches 175 run tp @s ^1.027 ^-0.057 ^1.218 ~ ~