#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run tp @s ^1.126 ^0.086 ^1.674 ~ ~
execute if score .this aj.frame matches 145 run tp @s ^1.126 ^0.103 ^1.674 ~ ~
execute if score .this aj.frame matches 146 run tp @s ^1.124 ^0.118 ^1.673 ~ ~
execute if score .this aj.frame matches 147 run tp @s ^1.122 ^0.124 ^1.671 ~ ~
execute if score .this aj.frame matches 148 run tp @s ^1.12 ^0.116 ^1.669 ~ ~
execute if score .this aj.frame matches 149 run tp @s ^1.117 ^0.1 ^1.667 ~ ~
execute if score .this aj.frame matches 150 run tp @s ^1.114 ^0.081 ^1.664 ~ ~
execute if score .this aj.frame matches 151 run tp @s ^1.11 ^0.065 ^1.66 ~ ~