#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 224 run tp @s ^-6.197 ^-1.792 ^0.82 ~ ~
execute if score .this aj.frame matches 225 run tp @s ^-5.97 ^-1.854 ^0.973 ~ ~
execute if score .this aj.frame matches 226 run tp @s ^-5.676 ^-1.875 ^1.092 ~ ~
execute if score .this aj.frame matches 227 run tp @s ^-5.303 ^-1.855 ^1.171 ~ ~
execute if score .this aj.frame matches 228 run tp @s ^-4.867 ^-1.801 ^1.217 ~ ~
execute if score .this aj.frame matches 229 run tp @s ^-4.384 ^-1.722 ^1.235 ~ ~
execute if score .this aj.frame matches 230 run tp @s ^-3.869 ^-1.626 ^1.23 ~ ~
execute if score .this aj.frame matches 231 run tp @s ^-3.341 ^-1.52 ^1.207 ~ ~