#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^1.18 ^-0.324 ^1.443 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^1.135 ^-0.26 ^1.409 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^1.057 ^-0.195 ^1.383 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^0.981 ^-0.126 ^1.386 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^0.934 ^-0.057 ^1.418 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^0.933 ^0.006 ^1.464 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^0.97 ^0.06 ^1.508 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^1.026 ^0.107 ^1.542 ~ ~