#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.435 ^-1.469 ^0.305 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.435 ^-1.469 ^0.305 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.435 ^-1.469 ^0.306 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.435 ^-1.469 ^0.306 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.435 ^-1.47 ^0.307 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.435 ^-1.47 ^0.307 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.434 ^-1.47 ^0.308 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.434 ^-1.47 ^0.308 ~ ~