#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^0.433 ^-1.47 ^0.312 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^0.433 ^-1.47 ^0.311 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^0.434 ^-1.47 ^0.31 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^0.434 ^-1.47 ^0.31 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^0.434 ^-1.47 ^0.309 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^0.434 ^-1.47 ^0.308 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^0.435 ^-1.47 ^0.307 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^0.435 ^-1.47 ^0.306 ~ ~