#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 280 run data modify entity @s Pose.Head set value [178.5394f,-24.2632f,-175.8056f]
execute if score .this aj.frame matches 281 run data modify entity @s Pose.Head set value [-178.8753f,-18.2244f,-177.7635f]
execute if score .this aj.frame matches 282 run data modify entity @s Pose.Head set value [-176.4106f,-12.4694f,-179.7273f]
execute if score .this aj.frame matches 283 run data modify entity @s Pose.Head set value [-174.3174f,-7.5854f,178.4431f]
execute if score .this aj.frame matches 284 run data modify entity @s Pose.Head set value [-172.8467f,-4.1594f,176.8881f]
execute if score .this aj.frame matches 285 run data modify entity @s Pose.Head set value [-167.3265f,-1.6437f,178.5197f]
execute if score .this aj.frame matches 286 run data modify entity @s Pose.Head set value [-159.969f,-1.7476f,-176.9826f]
execute if score .this aj.frame matches 287 run data modify entity @s Pose.Head set value [-158.9307f,-2.8158f,-177.4128f]