#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^1.106 ^0.058 ^1.656 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^1.102 ^0.064 ^1.651 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^1.097 ^0.08 ^1.646 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^1.092 ^0.099 ^1.64 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^1.076 ^0.115 ^1.618 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^1.055 ^0.122 ^1.585 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^1.033 ^0.115 ^1.542 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^1.012 ^0.097 ^1.491 ~ ~