#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 232 run tp @s ^-2.833 ^-1.405 ^1.175 ~ ~
execute if score .this aj.frame matches 233 run tp @s ^-2.358 ^-1.293 ^1.14 ~ ~
execute if score .this aj.frame matches 234 run tp @s ^-1.927 ^-1.195 ^1.108 ~ ~
execute if score .this aj.frame matches 235 run tp @s ^-1.552 ^-1.119 ^1.083 ~ ~
execute if score .this aj.frame matches 236 run tp @s ^-1.24 ^-1.068 ^1.069 ~ ~
execute if score .this aj.frame matches 237 run tp @s ^-1.001 ^-1.039 ^1.07 ~ ~
execute if score .this aj.frame matches 238 run tp @s ^-1.004 ^-1.041 ^1.071 ~ ~
execute if score .this aj.frame matches 239 run tp @s ^-1.007 ^-1.029 ^1.072 ~ ~