#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 264 run tp @s ^-0.655 ^-1.081 ^1.331 ~ ~
execute if score .this aj.frame matches 265 run tp @s ^-0.654 ^-1.1 ^1.331 ~ ~
execute if score .this aj.frame matches 266 run tp @s ^-0.654 ^-1.115 ^1.332 ~ ~
execute if score .this aj.frame matches 267 run tp @s ^-0.654 ^-1.122 ^1.332 ~ ~
execute if score .this aj.frame matches 268 run tp @s ^-0.654 ^-1.115 ^1.332 ~ ~
execute if score .this aj.frame matches 269 run tp @s ^-0.654 ^-1.099 ^1.332 ~ ~
execute if score .this aj.frame matches 270 run tp @s ^-0.654 ^-1.081 ^1.332 ~ ~
execute if score .this aj.frame matches 271 run tp @s ^-0.654 ^-1.065 ^1.332 ~ ~