#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^0.014 ^-1.513 ^0.395 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^0.02 ^-1.527 ^0.452 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^0.025 ^-1.543 ^0.516 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^0.032 ^-1.559 ^0.586 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^0.041 ^-1.573 ^0.659 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^0.054 ^-1.584 ^0.735 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^0.071 ^-1.59 ^0.811 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^0.092 ^-1.588 ^0.887 ~ ~