#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 216 run tp @s ^-7.132 ^-0.607 ^-0.747 ~ ~
execute if score .this aj.frame matches 217 run tp @s ^-7.096 ^-0.792 ^-0.488 ~ ~
execute if score .this aj.frame matches 218 run tp @s ^-7.035 ^-0.97 ^-0.231 ~ ~
execute if score .this aj.frame matches 219 run tp @s ^-6.949 ^-1.149 ^0.03 ~ ~
execute if score .this aj.frame matches 220 run tp @s ^-6.835 ^-1.328 ^0.297 ~ ~
execute if score .this aj.frame matches 221 run tp @s ^-6.691 ^-1.497 ^0.563 ~ ~
execute if score .this aj.frame matches 222 run tp @s ^-6.52 ^-1.648 ^0.818 ~ ~
execute if score .this aj.frame matches 223 run tp @s ^-6.328 ^-1.773 ^1.049 ~ ~