#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 296 run tp @s ^-0.031 ^-1.41 ^-0.116 ~ ~
execute if score .this aj.frame matches 297 run tp @s ^-0.033 ^-1.409 ^-0.118 ~ ~
execute if score .this aj.frame matches 298 run tp @s ^-0.034 ^-1.408 ^-0.12 ~ ~
execute if score .this aj.frame matches 299 run tp @s ^-0.034 ^-1.408 ^-0.12 ~ ~
execute if score .this aj.frame matches 300 run tp @s ^-0.034 ^-1.408 ^-0.12 ~ ~
execute if score .this aj.frame matches 301 run tp @s ^-0.033 ^-1.409 ^-0.119 ~ ~
execute if score .this aj.frame matches 302 run tp @s ^-0.032 ^-1.41 ^-0.117 ~ ~
execute if score .this aj.frame matches 303 run tp @s ^-0.03 ^-1.411 ^-0.115 ~ ~