#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 248 run data modify entity @s Pose.Head set value [174.2433f,-36.6076f,-173.0103f]
execute if score .this aj.frame matches 249 run data modify entity @s Pose.Head set value [174.2187f,-36.7037f,-172.9955f]
execute if score .this aj.frame matches 250 run data modify entity @s Pose.Head set value [174.1735f,-36.826f,-172.9614f]
execute if score .this aj.frame matches 251 run data modify entity @s Pose.Head set value [174.1097f,-36.9713f,-172.9097f]
execute if score .this aj.frame matches 252 run data modify entity @s Pose.Head set value [174.0294f,-37.1364f,-172.8422f]
execute if score .this aj.frame matches 253 run data modify entity @s Pose.Head set value [173.9345f,-37.3181f,-172.7609f]
execute if score .this aj.frame matches 254 run data modify entity @s Pose.Head set value [173.8272f,-37.513f,-172.6674f]
execute if score .this aj.frame matches 255 run data modify entity @s Pose.Head set value [173.7094f,-37.718f,-172.5637f]