#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 280 run tp @s ^-0.493 ^-1.228 ^1.069 ~ ~
execute if score .this aj.frame matches 281 run tp @s ^-0.424 ^-1.274 ^0.954 ~ ~
execute if score .this aj.frame matches 282 run tp @s ^-0.357 ^-1.319 ^0.836 ~ ~
execute if score .this aj.frame matches 283 run tp @s ^-0.295 ^-1.361 ^0.721 ~ ~
execute if score .this aj.frame matches 284 run tp @s ^-0.244 ^-1.396 ^0.614 ~ ~
execute if score .this aj.frame matches 285 run tp @s ^-0.161 ^-1.455 ^0.418 ~ ~
execute if score .this aj.frame matches 286 run tp @s ^-0.084 ^-1.514 ^0.21 ~ ~
execute if score .this aj.frame matches 287 run tp @s ^-0.027 ^-1.544 ^0.024 ~ ~