#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-1.5 ^-0.068 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-1.506 ^-0.016 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-1.503 ^0.029 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-1.501 ^0.074 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-1.507 ^0.125 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-1.501 ^0.167 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-1.503 ^0.216 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-1.506 ^0.265 ~ ~