#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run data modify entity @s Pose.Head set value [-168.7814f,61.9991f,-169.4128f]
execute if score .this aj.frame matches 145 run data modify entity @s Pose.Head set value [-168.4672f,62.026f,-169.4461f]
execute if score .this aj.frame matches 146 run data modify entity @s Pose.Head set value [-168.1698f,61.9438f,-169.5023f]
execute if score .this aj.frame matches 147 run data modify entity @s Pose.Head set value [-167.8956f,61.7555f,-169.5789f]
execute if score .this aj.frame matches 148 run data modify entity @s Pose.Head set value [-167.6507f,61.4638f,-169.6731f]
execute if score .this aj.frame matches 149 run data modify entity @s Pose.Head set value [-167.4414f,61.0719f,-169.7822f]
execute if score .this aj.frame matches 150 run data modify entity @s Pose.Head set value [-167.274f,60.5824f,-169.9034f]
execute if score .this aj.frame matches 151 run data modify entity @s Pose.Head set value [-167.1547f,59.9985f,-170.0341f]