#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-9.1389f,17.4719f,8.307f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-9.8831f,17.1797f,9.0064f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-10.5774f,16.8672f,9.6625f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-11.2108f,16.538f,10.265f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-11.7724f,16.1961f,10.8035f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-12.251f,15.8451f,11.2678f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-12.6357f,15.489f,11.6476f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-12.9155f,15.1317f,11.9324f]