#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 312 run tp @s ^-0.009 ^-1.428 ^-0.082 ~ ~
execute if score .this aj.frame matches 313 run tp @s ^-0.007 ^-1.43 ^-0.078 ~ ~
execute if score .this aj.frame matches 314 run tp @s ^-0.005 ^-1.432 ^-0.075 ~ ~
execute if score .this aj.frame matches 315 run tp @s ^-0.003 ^-1.434 ^-0.073 ~ ~
execute if score .this aj.frame matches 316 run tp @s ^-0.002 ^-1.436 ^-0.071 ~ ~
execute if score .this aj.frame matches 317 run tp @s ^-0.001 ^-1.437 ^-0.069 ~ ~
execute if score .this aj.frame matches 318 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 319 run tp @s ^0 ^-1.438 ^-0.068 ~ ~