#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 224 run tp @s ^-6.118 ^-1.866 ^1.246 ~ ~
execute if score .this aj.frame matches 225 run tp @s ^-5.897 ^-1.923 ^1.4 ~ ~
execute if score .this aj.frame matches 226 run tp @s ^-5.604 ^-1.945 ^1.519 ~ ~
execute if score .this aj.frame matches 227 run tp @s ^-5.228 ^-1.929 ^1.597 ~ ~
execute if score .this aj.frame matches 228 run tp @s ^-4.786 ^-1.882 ^1.641 ~ ~
execute if score .this aj.frame matches 229 run tp @s ^-4.294 ^-1.811 ^1.655 ~ ~
execute if score .this aj.frame matches 230 run tp @s ^-3.77 ^-1.723 ^1.647 ~ ~
execute if score .this aj.frame matches 231 run tp @s ^-3.23 ^-1.624 ^1.619 ~ ~