#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 256 run data modify entity @s Pose.Head set value [173.5831f,-37.9297f,-172.4515f]
execute if score .this aj.frame matches 257 run data modify entity @s Pose.Head set value [173.4505f,-38.1451f,-172.3326f]
execute if score .this aj.frame matches 258 run data modify entity @s Pose.Head set value [173.3134f,-38.3608f,-172.209f]
execute if score .this aj.frame matches 259 run data modify entity @s Pose.Head set value [173.174f,-38.5735f,-172.0824f]
execute if score .this aj.frame matches 260 run data modify entity @s Pose.Head set value [173.0342f,-38.7801f,-171.9546f]
execute if score .this aj.frame matches 261 run data modify entity @s Pose.Head set value [172.8962f,-38.9774f,-171.8275f]
execute if score .this aj.frame matches 262 run data modify entity @s Pose.Head set value [172.7618f,-39.1619f,-171.7028f]
execute if score .this aj.frame matches 263 run data modify entity @s Pose.Head set value [172.6332f,-39.3306f,-171.5825f]