#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.12 ^-1.578 ^0.96 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0.154 ^-1.558 ^1.029 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.196 ^-1.527 ^1.093 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.246 ^-1.484 ^1.149 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.286 ^-1.449 ^1.183 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.332 ^-1.408 ^1.218 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0.382 ^-1.362 ^1.254 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0.437 ^-1.313 ^1.29 ~ ~