#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^1.479 ^-0.019 ^1.185 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^1.523 ^0.027 ^1.02 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^1.597 ^0.087 ^0.805 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^1.684 ^0.158 ^0.548 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^1.771 ^0.236 ^0.261 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^1.842 ^0.318 ^-0.048 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^1.871 ^0.408 ^-0.368 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^1.856 ^0.509 ^-0.68 ~ ~