#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 376 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 377 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 378 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 379 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 380 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 381 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 382 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 383 run tp @s ^0 ^-1.438 ^-0.068 ~ ~