#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.002 ^-1.488 ^0.307 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.003 ^-1.489 ^0.307 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.003 ^-1.489 ^0.307 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.003 ^-1.49 ^0.307 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.003 ^-1.491 ^0.307 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.003 ^-1.491 ^0.308 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.003 ^-1.492 ^0.308 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.004 ^-1.493 ^0.308 ~ ~