#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [-35.314f,-44.6541f,28.3185f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [-42.6648f,-48.3463f,35.8981f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [-50.4005f,-52.1298f,43.8999f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [-58.4305f,-55.9349f,52.2311f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [-66.6644f,-59.6918f,60.7989f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [-75.0117f,-63.331f,69.5106f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [-83.382f,-66.7828f,78.2733f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [-91.6847f,-69.9774f,86.9944f]