#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.938 ^-0.76 ^1.679 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.992 ^-0.694 ^1.725 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^1.043 ^-0.631 ^1.767 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^1.093 ^-0.571 ^1.804 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^1.14 ^-0.515 ^1.836 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^1.183 ^-0.463 ^1.86 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^1.222 ^-0.417 ^1.877 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^1.256 ^-0.376 ^1.884 ~ ~