#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.004 ^-1.496 ^0.308 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.004 ^-1.498 ^0.308 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.004 ^-1.499 ^0.308 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.004 ^-1.5 ^0.308 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.004 ^-1.501 ^0.308 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.003 ^-1.501 ^0.308 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.003 ^-1.501 ^0.308 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.003 ^-1.501 ^0.308 ~ ~