#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.005 ^-1.499 ^0.308 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.005 ^-1.5 ^0.308 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.005 ^-1.501 ^0.308 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.005 ^-1.501 ^0.308 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.005 ^-1.5 ^0.308 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.005 ^-1.499 ^0.308 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.005 ^-1.498 ^0.308 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.005 ^-1.497 ^0.308 ~ ~