#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 160 run tp @s ^1.379 ^0.012 ^1.229 ~ ~
execute if score .this aj.frame matches 161 run tp @s ^1.397 ^-0.001 ^1.224 ~ ~
execute if score .this aj.frame matches 162 run tp @s ^1.414 ^-0.005 ^1.222 ~ ~
execute if score .this aj.frame matches 163 run tp @s ^1.429 ^0.004 ^1.223 ~ ~
execute if score .this aj.frame matches 164 run tp @s ^1.442 ^0.022 ^1.225 ~ ~
execute if score .this aj.frame matches 165 run tp @s ^1.453 ^0.042 ^1.227 ~ ~
execute if score .this aj.frame matches 166 run tp @s ^1.46 ^0.058 ^1.228 ~ ~
execute if score .this aj.frame matches 167 run tp @s ^1.469 ^0.06 ^1.226 ~ ~