#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192 run tp @s ^1.183 ^1.056 ^-2.663 ~ ~
execute if score .this aj.frame matches 193 run tp @s ^1.059 ^1.101 ^-2.883 ~ ~
execute if score .this aj.frame matches 194 run tp @s ^0.908 ^1.138 ^-3.081 ~ ~
execute if score .this aj.frame matches 195 run tp @s ^0.729 ^1.166 ^-3.251 ~ ~
execute if score .this aj.frame matches 196 run tp @s ^0.516 ^1.182 ^-3.385 ~ ~
execute if score .this aj.frame matches 197 run tp @s ^0.269 ^1.187 ^-3.48 ~ ~
execute if score .this aj.frame matches 198 run tp @s ^-0.018 ^1.178 ^-3.53 ~ ~
execute if score .this aj.frame matches 199 run tp @s ^-0.367 ^1.155 ^-3.54 ~ ~