#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 304 run tp @s ^-0.028 ^-1.412 ^-0.112 ~ ~
execute if score .this aj.frame matches 305 run tp @s ^-0.026 ^-1.413 ^-0.108 ~ ~
execute if score .this aj.frame matches 306 run tp @s ^-0.023 ^-1.415 ^-0.105 ~ ~
execute if score .this aj.frame matches 307 run tp @s ^-0.021 ^-1.417 ^-0.101 ~ ~
execute if score .this aj.frame matches 308 run tp @s ^-0.018 ^-1.419 ^-0.097 ~ ~
execute if score .this aj.frame matches 309 run tp @s ^-0.016 ^-1.421 ^-0.093 ~ ~
execute if score .this aj.frame matches 310 run tp @s ^-0.013 ^-1.423 ^-0.089 ~ ~
execute if score .this aj.frame matches 311 run tp @s ^-0.011 ^-1.426 ^-0.085 ~ ~