#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 360 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 361 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 362 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 363 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 364 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 365 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 366 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 367 run tp @s ^0 ^-1.438 ^-0.068 ~ ~