#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 240 run tp @s ^-0.659 ^-1.087 ^1.326 ~ ~
execute if score .this aj.frame matches 241 run tp @s ^-0.66 ^-1.068 ^1.325 ~ ~
execute if score .this aj.frame matches 242 run tp @s ^-0.66 ^-1.06 ^1.325 ~ ~
execute if score .this aj.frame matches 243 run tp @s ^-0.66 ^-1.066 ^1.324 ~ ~
execute if score .this aj.frame matches 244 run tp @s ^-0.661 ^-1.082 ^1.324 ~ ~
execute if score .this aj.frame matches 245 run tp @s ^-0.661 ^-1.1 ^1.324 ~ ~
execute if score .this aj.frame matches 246 run tp @s ^-0.661 ^-1.116 ^1.324 ~ ~
execute if score .this aj.frame matches 247 run tp @s ^-0.661 ^-1.122 ^1.324 ~ ~