#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 272 run tp @s ^-0.654 ^-1.059 ^1.332 ~ ~
execute if score .this aj.frame matches 273 run tp @s ^-0.662 ^-1.06 ^1.342 ~ ~
execute if score .this aj.frame matches 274 run tp @s ^-0.679 ^-1.066 ^1.363 ~ ~
execute if score .this aj.frame matches 275 run tp @s ^-0.691 ^-1.077 ^1.378 ~ ~
execute if score .this aj.frame matches 276 run tp @s ^-0.688 ^-1.095 ^1.372 ~ ~
execute if score .this aj.frame matches 277 run tp @s ^-0.656 ^-1.122 ^1.329 ~ ~
execute if score .this aj.frame matches 278 run tp @s ^-0.615 ^-1.15 ^1.263 ~ ~
execute if score .this aj.frame matches 279 run tp @s ^-0.559 ^-1.186 ^1.174 ~ ~