#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.001 ^-1.49 ^0.307 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.001 ^-1.49 ^0.307 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.002 ^-1.489 ^0.307 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.002 ^-1.488 ^0.307 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.002 ^-1.488 ^0.307 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.002 ^-1.487 ^0.307 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.002 ^-1.487 ^0.307 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.002 ^-1.487 ^0.307 ~ ~