#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 232 run tp @s ^-2.692 ^-1.519 ^1.575 ~ ~
execute if score .this aj.frame matches 233 run tp @s ^-2.172 ^-1.415 ^1.519 ~ ~
execute if score .this aj.frame matches 234 run tp @s ^-1.692 ^-1.317 ^1.458 ~ ~
execute if score .this aj.frame matches 235 run tp @s ^-1.269 ^-1.232 ^1.399 ~ ~
execute if score .this aj.frame matches 236 run tp @s ^-0.919 ^-1.165 ^1.352 ~ ~
execute if score .this aj.frame matches 237 run tp @s ^-0.656 ^-1.122 ^1.329 ~ ~
execute if score .this aj.frame matches 238 run tp @s ^-0.657 ^-1.122 ^1.328 ~ ~
execute if score .this aj.frame matches 239 run tp @s ^-0.658 ^-1.108 ^1.327 ~ ~