#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^1.324 ^-0.291 ^1.857 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^1.37 ^-0.221 ^1.777 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^1.391 ^-0.162 ^1.667 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^1.389 ^-0.111 ^1.546 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^1.373 ^-0.066 ^1.434 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^1.354 ^-0.025 ^1.343 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^1.342 ^0.013 ^1.279 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^1.344 ^0.047 ^1.245 ~ ~