#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-0.005 ^-1.489 ^0.308 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-0.005 ^-1.488 ^0.308 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.005 ^-1.489 ^0.308 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.005 ^-1.49 ^0.308 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.005 ^-1.491 ^0.308 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.005 ^-1.493 ^0.308 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.005 ^-1.494 ^0.308 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.005 ^-1.495 ^0.308 ~ ~