#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function bluejay:animations/fly/tree/head_root_0-63
execute if score .this aj.frame matches 64..127 run function bluejay:animations/fly/tree/head_root_64-127
execute if score .this aj.frame matches 128..191 run function bluejay:animations/fly/tree/head_root_128-191
execute if score .this aj.frame matches 192..255 run function bluejay:animations/fly/tree/head_root_192-255
execute if score .this aj.frame matches 256..319 run function bluejay:animations/fly/tree/head_root_256-319
execute if score .this aj.frame matches 320..383 run function bluejay:animations/fly/tree/head_root_320-383
execute if score .this aj.frame matches 384..399 run function bluejay:animations/fly/tree/head_root_384-399