#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-0.015f,0.0024f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0.0334f,1.15f,-0.0548f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [0.1794f,2.7539f,-0.1947f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [0.3817f,4.6951f,-0.3835f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [0.5991f,6.8551f,-0.5851f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [0.7907f,9.1149f,-0.7631f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [0.9154f,11.3559f,-0.8809f]