#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 336 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 337 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 338 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 339 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 340 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 341 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 342 run tp @s ^0 ^-1.438 ^-0.068 ~ ~
execute if score .this aj.frame matches 343 run tp @s ^0 ^-1.438 ^-0.068 ~ ~