#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^1.361 ^0.067 ^1.214 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^1.362 ^0.057 ^1.214 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^1.352 ^0.031 ^1.231 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^1.34 ^0.006 ^1.253 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^1.334 ^-0.006 ^1.266 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^1.332 ^0.002 ^1.269 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^1.33 ^0.018 ^1.272 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^1.329 ^0.038 ^1.275 ~ ~