#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 224 run tp @s ^-6.196 ^-1.905 ^1.129 ~ ~
execute if score .this aj.frame matches 225 run tp @s ^-5.967 ^-1.977 ^1.312 ~ ~
execute if score .this aj.frame matches 226 run tp @s ^-5.667 ^-2.011 ^1.46 ~ ~
execute if score .this aj.frame matches 227 run tp @s ^-5.29 ^-1.987 ^1.506 ~ ~
execute if score .this aj.frame matches 228 run tp @s ^-4.849 ^-1.93 ^1.519 ~ ~
execute if score .this aj.frame matches 229 run tp @s ^-4.351 ^-1.871 ^1.562 ~ ~
execute if score .this aj.frame matches 230 run tp @s ^-3.819 ^-1.795 ^1.581 ~ ~
execute if score .this aj.frame matches 231 run tp @s ^-3.285 ^-1.683 ^1.524 ~ ~