#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 208 run tp @s ^-5.266 ^0.472 ^-2.462 ~ ~
execute if score .this aj.frame matches 209 run tp @s ^-5.765 ^0.365 ^-2.315 ~ ~
execute if score .this aj.frame matches 210 run tp @s ^-6.203 ^0.253 ^-2.162 ~ ~
execute if score .this aj.frame matches 211 run tp @s ^-6.547 ^0.156 ^-1.947 ~ ~
execute if score .this aj.frame matches 212 run tp @s ^-6.692 ^0.061 ^-1.741 ~ ~
execute if score .this aj.frame matches 213 run tp @s ^-6.844 ^-0.1 ^-1.593 ~ ~
execute if score .this aj.frame matches 214 run tp @s ^-7.011 ^-0.268 ^-1.359 ~ ~
execute if score .this aj.frame matches 215 run tp @s ^-7.069 ^-0.42 ^-1.122 ~ ~