#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^1.285 ^-0.065 ^1.41 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^1.301 ^-0.069 ^1.382 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^1.317 ^-0.065 ^1.354 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^1.3 ^-0.036 ^1.377 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^1.281 ^-0.009 ^1.393 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^1.299 ^-0.013 ^1.357 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^1.323 ^-0.03 ^1.321 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^1.303 ^-0.035 ^1.325 ~ ~