#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0.233 ^-1.625 ^0.88 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0.235 ^-1.622 ^0.959 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.245 ^-1.607 ^1.038 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.316 ^-1.563 ^1.082 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0.376 ^-1.528 ^1.101 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0.389 ^-1.499 ^1.156 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0.408 ^-1.461 ^1.216 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0.477 ^-1.417 ^1.233 ~ ~