#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [1.6244f,9.172f,-129.947f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [14.381f,-12.9218f,-71.3851f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [-2.6483f,-27.0232f,-4.7234f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [16.7916f,-22.1493f,-67.9965f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [18.0252f,3.8195f,-120.8805f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [19.1024f,-30.8841f,-64.813f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [-22.129f,-37.822f,14.7969f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [24.5265f,-41.3342f,-63.1993f]