#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 272 run tp @s ^-0.775 ^-1.112 ^1.27 ~ ~
execute if score .this aj.frame matches 273 run tp @s ^-0.761 ^-1.125 ^1.3 ~ ~
execute if score .this aj.frame matches 274 run tp @s ^-0.754 ^-1.142 ^1.34 ~ ~
execute if score .this aj.frame matches 275 run tp @s ^-0.79 ^-1.141 ^1.337 ~ ~
execute if score .this aj.frame matches 276 run tp @s ^-0.81 ^-1.148 ^1.313 ~ ~
execute if score .this aj.frame matches 277 run tp @s ^-0.755 ^-1.186 ^1.289 ~ ~
execute if score .this aj.frame matches 278 run tp @s ^-0.691 ^-1.226 ^1.248 ~ ~
execute if score .this aj.frame matches 279 run tp @s ^-0.662 ^-1.253 ^1.151 ~ ~