#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 280 run data modify entity @s Pose.Head set value [144.2109f,17.7765f,-58.8265f]
execute if score .this aj.frame matches 281 run data modify entity @s Pose.Head set value [157.1007f,-7.5605f,-116.1668f]
execute if score .this aj.frame matches 282 run data modify entity @s Pose.Head set value [-176.4106f,-12.4694f,-179.7273f]
execute if score .this aj.frame matches 283 run data modify entity @s Pose.Head set value [168.6518f,-6.3737f,-120.3432f]
execute if score .this aj.frame matches 284 run data modify entity @s Pose.Head set value [157.7694f,0.5908f,-61.7828f]
execute if score .this aj.frame matches 285 run data modify entity @s Pose.Head set value [177.3106f,-9.5842f,-120.9074f]
execute if score .this aj.frame matches 286 run data modify entity @s Pose.Head set value [-159.969f,-1.7476f,-176.9826f]
execute if score .this aj.frame matches 287 run data modify entity @s Pose.Head set value [-179.4703f,-17.4567f,-117.2672f]