#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^1.255 ^-0.374 ^1.759 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^1.293 ^-0.307 ^1.729 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^1.323 ^-0.247 ^1.668 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^1.292 ^-0.188 ^1.558 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^1.249 ^-0.131 ^1.475 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^1.276 ^-0.092 ^1.413 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^1.31 ^-0.062 ^1.352 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^1.298 ^-0.018 ^1.341 ~ ~