#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run data modify entity @s Pose.Head set value [147.1806f,9.0157f,-63.6352f]
execute if score .this aj.frame matches 169 run data modify entity @s Pose.Head set value [161.8754f,-14.6327f,-120.3f]
execute if score .this aj.frame matches 170 run data modify entity @s Pose.Head set value [-164.8972f,-16.1174f,176.5292f]
execute if score .this aj.frame matches 171 run data modify entity @s Pose.Head set value [169.0662f,-22.073f,-119.3017f]
execute if score .this aj.frame matches 172 run data modify entity @s Pose.Head set value [141.058f,-8.7771f,-57.8104f]
execute if score .this aj.frame matches 173 run data modify entity @s Pose.Head set value [174.4028f,-27.309f,-119.534f]
execute if score .this aj.frame matches 174 run data modify entity @s Pose.Head set value [-151.4633f,-12.726f,177.044f]
execute if score .this aj.frame matches 175 run data modify entity @s Pose.Head set value [174.7221f,-29.7402f,-119.5949f]