#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-0.015f,0.0024f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-0.028f,0.0096f,0f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-0.0391f,0.0213f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-0.0483f,0.0374f,0f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-0.0558f,0.0577f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-0.0614f,0.0819f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-0.0655f,0.11f,0f]