#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run tp @s ^0.139 ^-1.577 ^0.355 ~ ~
execute if score .this aj.frame matches 89 run tp @s ^0.114 ^-1.596 ^0.41 ~ ~
execute if score .this aj.frame matches 90 run tp @s ^0.09 ^-1.619 ^0.473 ~ ~
execute if score .this aj.frame matches 91 run tp @s ^0.127 ^-1.621 ^0.535 ~ ~
execute if score .this aj.frame matches 92 run tp @s ^0.165 ^-1.62 ^0.598 ~ ~
execute if score .this aj.frame matches 93 run tp @s ^0.147 ^-1.641 ^0.675 ~ ~
execute if score .this aj.frame matches 94 run tp @s ^0.134 ^-1.659 ^0.755 ~ ~
execute if score .this aj.frame matches 95 run tp @s ^0.181 ^-1.645 ^0.82 ~ ~