#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 384..391 run function bluejay:animations/fly/tree/l_wing_root_384-391
execute if score .this aj.frame matches 392..399 run function bluejay:animations/fly/tree/l_wing_root_392-399