#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 288 run tp @s ^-0.125 ^-1.604 ^-0.069 ~ ~
execute if score .this aj.frame matches 289 run tp @s ^0.094 ^-1.513 ^-0.101 ~ ~
execute if score .this aj.frame matches 290 run tp @s ^0.06 ^-1.512 ^-0.107 ~ ~
execute if score .this aj.frame matches 291 run tp @s ^0.058 ^-1.504 ^-0.113 ~ ~
execute if score .this aj.frame matches 292 run tp @s ^0.055 ^-1.498 ^-0.118 ~ ~
execute if score .this aj.frame matches 293 run tp @s ^0.053 ^-1.493 ^-0.122 ~ ~
execute if score .this aj.frame matches 294 run tp @s ^0.051 ^-1.489 ^-0.125 ~ ~
execute if score .this aj.frame matches 295 run tp @s ^0.049 ^-1.486 ^-0.128 ~ ~