#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [0.4738f,2.1808f,0f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [0.4729f,2.1566f,0f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [0.4705f,2.1266f,0f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [0.4665f,2.0906f,0f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [0.4609f,2.0482f,0f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [0.4534f,1.9995f,0f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [0.4442f,1.9441f,0f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [0.4331f,1.8818f,0f]