#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^1.345 ^-0.07 ^1.215 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^1.419 ^-0.029 ^1.061 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^1.522 ^0.026 ^0.856 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^1.581 ^0.101 ^0.587 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^1.638 ^0.184 ^0.289 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^1.74 ^0.261 ^-0.006 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^1.8 ^0.35 ^-0.309 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^1.759 ^0.469 ^-0.612 ~ ~