#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 192 run data modify entity @s Pose.Head set value [-122.9901f,-24.1651f,-79.3072f]
execute if score .this aj.frame matches 193 run data modify entity @s Pose.Head set value [-111.614f,29.9203f,-97.1913f]
execute if score .this aj.frame matches 194 run data modify entity @s Pose.Head set value [-165.523f,78.0159f,-167.9876f]
execute if score .this aj.frame matches 195 run data modify entity @s Pose.Head set value [-106.1663f,22.9592f,-94.5274f]
execute if score .this aj.frame matches 196 run data modify entity @s Pose.Head set value [-115.651f,-39.2113f,-83.0423f]
execute if score .this aj.frame matches 197 run data modify entity @s Pose.Head set value [-98.1605f,19.6602f,-91.3407f]
execute if score .this aj.frame matches 198 run data modify entity @s Pose.Head set value [-75.2283f,80.4479f,-78.5099f]
execute if score .this aj.frame matches 199 run data modify entity @s Pose.Head set value [-90.5378f,21.2854f,-88.3798f]