#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 352 run tp @s ^0.063 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 353 run tp @s ^0.063 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 354 run tp @s ^0.063 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 355 run tp @s ^0.063 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 356 run tp @s ^0.063 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 357 run tp @s ^0.063 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 358 run tp @s ^0.063 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 359 run tp @s ^0.063 ^-1.521 ^-0.101 ~ ~