#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run data modify entity @s Pose.Head set value [-140.3485f,-29.9859f,-68.351f]
execute if score .this aj.frame matches 145 run data modify entity @s Pose.Head set value [-126.1015f,21.6159f,-101.4936f]
execute if score .this aj.frame matches 146 run data modify entity @s Pose.Head set value [-168.1698f,61.9438f,-169.5023f]
execute if score .this aj.frame matches 147 run data modify entity @s Pose.Head set value [-126.2605f,21.264f,-102.1887f]
execute if score .this aj.frame matches 148 run data modify entity @s Pose.Head set value [-141.0725f,-30.4122f,-69.243f]
execute if score .this aj.frame matches 149 run data modify entity @s Pose.Head set value [-126.8444f,20.7976f,-103.0003f]
execute if score .this aj.frame matches 150 run data modify entity @s Pose.Head set value [-167.274f,60.5824f,-169.9034f]
execute if score .this aj.frame matches 151 run data modify entity @s Pose.Head set value [-127.8352f,20.24f,-103.8492f]