#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 160 run tp @s ^1.281 ^-0.044 ^1.321 ~ ~
execute if score .this aj.frame matches 161 run tp @s ^1.317 ^-0.07 ^1.291 ~ ~
execute if score .this aj.frame matches 162 run tp @s ^1.357 ^-0.085 ^1.27 ~ ~
execute if score .this aj.frame matches 163 run tp @s ^1.337 ^-0.07 ^1.263 ~ ~
execute if score .this aj.frame matches 164 run tp @s ^1.317 ^-0.048 ^1.251 ~ ~
execute if score .this aj.frame matches 165 run tp @s ^1.358 ^-0.037 ^1.245 ~ ~
execute if score .this aj.frame matches 166 run tp @s ^1.396 ^-0.029 ^1.247 ~ ~
execute if score .this aj.frame matches 167 run tp @s ^1.373 ^-0.02 ^1.234 ~ ~