#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 304 run data modify entity @s Pose.Head set value [-11.727f,0.1996f,-10.5897f]
execute if score .this aj.frame matches 305 run data modify entity @s Pose.Head set value [-10.8965f,0.1854f,-9.8398f]
execute if score .this aj.frame matches 306 run data modify entity @s Pose.Head set value [-9.9827f,0.1699f,-9.0146f]
execute if score .this aj.frame matches 307 run data modify entity @s Pose.Head set value [-9.0063f,0.1533f,-8.1329f]
execute if score .this aj.frame matches 308 run data modify entity @s Pose.Head set value [-7.9883f,0.1359f,-7.2135f]
execute if score .this aj.frame matches 309 run data modify entity @s Pose.Head set value [-6.9493f,0.1183f,-6.2754f]
execute if score .this aj.frame matches 310 run data modify entity @s Pose.Head set value [-5.9104f,0.1006f,-5.3372f]
execute if score .this aj.frame matches 311 run data modify entity @s Pose.Head set value [-4.8923f,0.0833f,-4.4179f]