#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 264 run data modify entity @s Pose.Head set value [131.1496f,28.4464f,-62.87f]
execute if score .this aj.frame matches 265 run data modify entity @s Pose.Head set value [134.396f,-11.1135f,-110.331f]
execute if score .this aj.frame matches 266 run data modify entity @s Pose.Head set value [172.3021f,-39.709f,-171.2655f]
execute if score .this aj.frame matches 267 run data modify entity @s Pose.Head set value [134.1704f,-11.0738f,-110.2241f]
execute if score .this aj.frame matches 268 run data modify entity @s Pose.Head set value [130.8808f,28.8213f,-62.8727f]
execute if score .this aj.frame matches 269 run data modify entity @s Pose.Head set value [134.0833f,-11.0149f,-110.1573f]
execute if score .this aj.frame matches 270 run data modify entity @s Pose.Head set value [172.0638f,-39.7946f,-171.0137f]
execute if score .this aj.frame matches 271 run data modify entity @s Pose.Head set value [134.1638f,-10.9344f,-110.1396f]