#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 312 run tp @s ^0.059 ^-1.509 ^-0.109 ~ ~
execute if score .this aj.frame matches 313 run tp @s ^0.06 ^-1.512 ^-0.107 ~ ~
execute if score .this aj.frame matches 314 run tp @s ^0.061 ^-1.514 ^-0.106 ~ ~
execute if score .this aj.frame matches 315 run tp @s ^0.061 ^-1.516 ^-0.104 ~ ~
execute if score .this aj.frame matches 316 run tp @s ^0.062 ^-1.518 ^-0.103 ~ ~
execute if score .this aj.frame matches 317 run tp @s ^0.062 ^-1.52 ^-0.102 ~ ~
execute if score .this aj.frame matches 318 run tp @s ^0.062 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 319 run tp @s ^0.063 ^-1.521 ^-0.101 ~ ~