#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [0.4324f,2.1848f,0f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [0.4417f,2.2009f,0f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [0.4499f,2.2126f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [0.457f,2.2198f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0.463f,2.2222f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [0.4677f,2.2197f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [0.4711f,2.2121f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [0.4732f,2.1992f,0f]