#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 248 run tp @s ^-0.785 ^-1.172 ^1.27 ~ ~
execute if score .this aj.frame matches 249 run tp @s ^-0.76 ^-1.167 ^1.288 ~ ~
execute if score .this aj.frame matches 250 run tp @s ^-0.735 ^-1.159 ^1.307 ~ ~
execute if score .this aj.frame matches 251 run tp @s ^-0.759 ^-1.133 ^1.289 ~ ~
execute if score .this aj.frame matches 252 run tp @s ^-0.783 ^-1.115 ^1.27 ~ ~
execute if score .this aj.frame matches 253 run tp @s ^-0.758 ^-1.132 ^1.289 ~ ~
execute if score .this aj.frame matches 254 run tp @s ^-0.734 ^-1.159 ^1.307 ~ ~
execute if score .this aj.frame matches 255 run tp @s ^-0.757 ^-1.166 ^1.289 ~ ~