#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.907 ^-0.863 ^1.581 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.958 ^-0.792 ^1.654 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^1.011 ^-0.726 ^1.725 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^1.055 ^-0.662 ^1.728 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^1.096 ^-0.6 ^1.726 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^1.141 ^-0.55 ^1.781 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^1.182 ^-0.507 ^1.83 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^1.209 ^-0.462 ^1.807 ~ ~