#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128..135 run function bluejay:animations/fly/tree/l_wing_root_128-135
execute if score .this aj.frame matches 136..143 run function bluejay:animations/fly/tree/l_wing_root_136-143
execute if score .this aj.frame matches 144..151 run function bluejay:animations/fly/tree/l_wing_root_144-151
execute if score .this aj.frame matches 152..159 run function bluejay:animations/fly/tree/l_wing_root_152-159
execute if score .this aj.frame matches 160..167 run function bluejay:animations/fly/tree/l_wing_root_160-167
execute if score .this aj.frame matches 168..175 run function bluejay:animations/fly/tree/l_wing_root_168-175
execute if score .this aj.frame matches 176..183 run function bluejay:animations/fly/tree/l_wing_root_176-183
execute if score .this aj.frame matches 184..191 run function bluejay:animations/fly/tree/l_wing_root_184-191