#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 232 run data modify entity @s Pose.Head set value [94.3497f,42.7358f,-83.4201f]
execute if score .this aj.frame matches 233 run data modify entity @s Pose.Head set value [107.138f,-12.9861f,-102.912f]
execute if score .this aj.frame matches 234 run data modify entity @s Pose.Head set value [156.6972f,-55.7592f,-157.807f]
execute if score .this aj.frame matches 235 run data modify entity @s Pose.Head set value [123.0871f,-10.0772f,-106.6714f]
execute if score .this aj.frame matches 236 run data modify entity @s Pose.Head set value [128.8056f,31.9563f,-63.0966f]
execute if score .this aj.frame matches 237 run data modify entity @s Pose.Head set value [135.7059f,-10.5538f,-110.4779f]
execute if score .this aj.frame matches 238 run data modify entity @s Pose.Head set value [172.9107f,-37.8042f,-171.6906f]
execute if score .this aj.frame matches 239 run data modify entity @s Pose.Head set value [136.6193f,-10.6237f,-110.8584f]