#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run tp @s ^1.29 ^-0.038 ^1.417 ~ ~
execute if score .this aj.frame matches 145 run tp @s ^1.304 ^-0.031 ^1.391 ~ ~
execute if score .this aj.frame matches 146 run tp @s ^1.318 ^-0.027 ^1.363 ~ ~
execute if score .this aj.frame matches 147 run tp @s ^1.303 ^-0.01 ^1.39 ~ ~
execute if score .this aj.frame matches 148 run tp @s ^1.288 ^-0.007 ^1.416 ~ ~
execute if score .this aj.frame matches 149 run tp @s ^1.302 ^-0.034 ^1.388 ~ ~
execute if score .this aj.frame matches 150 run tp @s ^1.317 ^-0.063 ^1.36 ~ ~
execute if score .this aj.frame matches 151 run tp @s ^1.302 ^-0.069 ^1.385 ~ ~