#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.059 ^-1.584 ^0.276 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.059 ^-1.584 ^0.276 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.059 ^-1.584 ^0.276 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.059 ^-1.584 ^0.276 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.059 ^-1.584 ^0.276 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.059 ^-1.584 ^0.276 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.059 ^-1.584 ^0.276 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.059 ^-1.584 ^0.277 ~ ~