#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 240 run tp @s ^-0.783 ^-1.141 ^1.271 ~ ~
execute if score .this aj.frame matches 241 run tp @s ^-0.759 ^-1.134 ^1.289 ~ ~
execute if score .this aj.frame matches 242 run tp @s ^-0.735 ^-1.137 ^1.307 ~ ~
execute if score .this aj.frame matches 243 run tp @s ^-0.76 ^-1.132 ^1.289 ~ ~
execute if score .this aj.frame matches 244 run tp @s ^-0.785 ^-1.137 ^1.271 ~ ~
execute if score .this aj.frame matches 245 run tp @s ^-0.76 ^-1.167 ^1.289 ~ ~
execute if score .this aj.frame matches 246 run tp @s ^-0.736 ^-1.193 ^1.307 ~ ~
execute if score .this aj.frame matches 247 run tp @s ^-0.76 ^-1.189 ^1.289 ~ ~