#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 296 run data modify entity @s Pose.Head set value [-12.8667f,0.219f,-11.6189f]
execute if score .this aj.frame matches 297 run data modify entity @s Pose.Head set value [-13.4539f,0.229f,-12.1491f]
execute if score .this aj.frame matches 298 run data modify entity @s Pose.Head set value [-13.7909f,0.2347f,-12.4535f]
execute if score .this aj.frame matches 299 run data modify entity @s Pose.Head set value [-13.8987f,0.2365f,-12.5508f]
execute if score .this aj.frame matches 300 run data modify entity @s Pose.Head set value [-13.7979f,0.2348f,-12.4598f]
execute if score .this aj.frame matches 301 run data modify entity @s Pose.Head set value [-13.5095f,0.2299f,-12.1993f]
execute if score .this aj.frame matches 302 run data modify entity @s Pose.Head set value [-13.0543f,0.2222f,-11.7883f]
execute if score .this aj.frame matches 303 run data modify entity @s Pose.Head set value [-12.4532f,0.2119f,-11.2455f]