#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 296 run tp @s ^0.048 ^-1.484 ^-0.13 ~ ~
execute if score .this aj.frame matches 297 run tp @s ^0.047 ^-1.482 ^-0.131 ~ ~
execute if score .this aj.frame matches 298 run tp @s ^0.047 ^-1.481 ^-0.132 ~ ~
execute if score .this aj.frame matches 299 run tp @s ^0.046 ^-1.481 ^-0.132 ~ ~
execute if score .this aj.frame matches 300 run tp @s ^0.047 ^-1.481 ^-0.132 ~ ~
execute if score .this aj.frame matches 301 run tp @s ^0.047 ^-1.482 ^-0.131 ~ ~
execute if score .this aj.frame matches 302 run tp @s ^0.048 ^-1.483 ^-0.13 ~ ~
execute if score .this aj.frame matches 303 run tp @s ^0.049 ^-1.485 ^-0.129 ~ ~