#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run data modify entity @s Pose.Head set value [-143.5696f,-30.2827f,-68.9675f]
execute if score .this aj.frame matches 153 run data modify entity @s Pose.Head set value [-129.2183f,19.62f,-104.6593f]
execute if score .this aj.frame matches 154 run data modify entity @s Pose.Head set value [-167.1477f,57.7082f,-170.4559f]
execute if score .this aj.frame matches 155 run data modify entity @s Pose.Head set value [-130.9835f,18.9752f,-105.3597f]
execute if score .this aj.frame matches 156 run data modify entity @s Pose.Head set value [-150.082f,-28.4272f,-65.9645f]
execute if score .this aj.frame matches 157 run data modify entity @s Pose.Head set value [-139.4987f,16.437f,-107.7939f]
execute if score .this aj.frame matches 158 run data modify entity @s Pose.Head set value [-170.7708f,42.0712f,-173.0645f]
execute if score .this aj.frame matches 159 run data modify entity @s Pose.Head set value [-153.1298f,12.6521f,-111.3648f]