#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run data modify entity @s Pose.Head set value [136.9698f,-12.6508f,-56.4314f]
execute if score .this aj.frame matches 177 run data modify entity @s Pose.Head set value [173.5182f,-30.782f,-119.5938f]
execute if score .this aj.frame matches 178 run data modify entity @s Pose.Head set value [-150.362f,-15.0906f,175.8102f]
execute if score .this aj.frame matches 179 run data modify entity @s Pose.Head set value [172.7777f,-30.0895f,-119.6026f]
execute if score .this aj.frame matches 180 run data modify entity @s Pose.Head set value [137.9006f,-11.2086f,-57.1246f]
execute if score .this aj.frame matches 181 run data modify entity @s Pose.Head set value [174.4074f,-27.3111f,-119.5363f]
execute if score .this aj.frame matches 182 run data modify entity @s Pose.Head set value [-156.8829f,-3.7469f,-175.6258f]
execute if score .this aj.frame matches 183 run data modify entity @s Pose.Head set value [-171.1805f,-8.0411f,-107.8386f]