#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run tp @s ^1.348 ^-0.03 ^1.22 ~ ~
execute if score .this aj.frame matches 169 run tp @s ^1.379 ^-0.066 ^1.227 ~ ~
execute if score .this aj.frame matches 170 run tp @s ^1.407 ^-0.103 ^1.237 ~ ~
execute if score .this aj.frame matches 171 run tp @s ^1.374 ^-0.117 ^1.227 ~ ~
execute if score .this aj.frame matches 172 run tp @s ^1.336 ^-0.123 ^1.252 ~ ~
execute if score .this aj.frame matches 173 run tp @s ^1.353 ^-0.139 ^1.333 ~ ~
execute if score .this aj.frame matches 174 run tp @s ^1.374 ^-0.144 ^1.396 ~ ~
execute if score .this aj.frame matches 175 run tp @s ^1.349 ^-0.12 ^1.367 ~ ~