#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 240 run data modify entity @s Pose.Head set value [133.3298f,26.9821f,-62.0143f]
execute if score .this aj.frame matches 241 run data modify entity @s Pose.Head set value [137.2618f,-10.6993f,-111.1437f]
execute if score .this aj.frame matches 242 run data modify entity @s Pose.Head set value [173.8449f,-36.7642f,-172.5896f]
execute if score .this aj.frame matches 243 run data modify entity @s Pose.Head set value [137.6612f,-10.7749f,-111.3396f]
execute if score .this aj.frame matches 244 run data modify entity @s Pose.Head set value [133.7817f,26.2847f,-62.0552f]
execute if score .this aj.frame matches 245 run data modify entity @s Pose.Head set value [137.8462f,-10.8468f,-111.4535f]
execute if score .this aj.frame matches 246 run data modify entity @s Pose.Head set value [174.2226f,-36.5073f,-172.9743f]
execute if score .this aj.frame matches 247 run data modify entity @s Pose.Head set value [137.846f,-10.9127f,-111.4944f]