#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 184 run data modify entity @s Pose.Head set value [140.8407f,-0.6204f,71.6713f]
execute if score .this aj.frame matches 185 run data modify entity @s Pose.Head set value [146.5957f,18.0581f,124.3582f]
execute if score .this aj.frame matches 186 run data modify entity @s Pose.Head set value [172.541f,37.4396f,-179.8702f]
execute if score .this aj.frame matches 187 run data modify entity @s Pose.Head set value [124.524f,10.4198f,109.1086f]
execute if score .this aj.frame matches 188 run data modify entity @s Pose.Head set value [121.8737f,-38.1312f,62.8025f]
execute if score .this aj.frame matches 189 run data modify entity @s Pose.Head set value [105.9656f,11.5586f,98.1321f]
execute if score .this aj.frame matches 190 run data modify entity @s Pose.Head set value [144.0586f,67.4283f,143.9843f]
execute if score .this aj.frame matches 191 run data modify entity @s Pose.Head set value [98.0574f,20.4533f,93.2001f]