#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 256 run tp @s ^-0.585 ^-1.196 ^1.424 ~ ~
execute if score .this aj.frame matches 257 run tp @s ^-0.61 ^-1.207 ^1.405 ~ ~
execute if score .this aj.frame matches 258 run tp @s ^-0.635 ^-1.206 ^1.385 ~ ~
execute if score .this aj.frame matches 259 run tp @s ^-0.61 ^-1.186 ^1.406 ~ ~
execute if score .this aj.frame matches 260 run tp @s ^-0.585 ^-1.163 ^1.427 ~ ~
execute if score .this aj.frame matches 261 run tp @s ^-0.61 ^-1.152 ^1.407 ~ ~
execute if score .this aj.frame matches 262 run tp @s ^-0.634 ^-1.15 ^1.387 ~ ~
execute if score .this aj.frame matches 263 run tp @s ^-0.61 ^-1.152 ^1.408 ~ ~