#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 304 run tp @s ^-0.073 ^-1.51 ^-0.128 ~ ~
execute if score .this aj.frame matches 305 run tp @s ^-0.072 ^-1.51 ^-0.126 ~ ~
execute if score .this aj.frame matches 306 run tp @s ^-0.071 ^-1.511 ^-0.123 ~ ~
execute if score .this aj.frame matches 307 run tp @s ^-0.07 ^-1.512 ^-0.121 ~ ~
execute if score .this aj.frame matches 308 run tp @s ^-0.069 ^-1.513 ^-0.119 ~ ~
execute if score .this aj.frame matches 309 run tp @s ^-0.068 ^-1.514 ^-0.116 ~ ~
execute if score .this aj.frame matches 310 run tp @s ^-0.067 ^-1.515 ^-0.114 ~ ~
execute if score .this aj.frame matches 311 run tp @s ^-0.066 ^-1.516 ^-0.112 ~ ~