#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 384 run tp @s ^-0.062 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 385 run tp @s ^-0.062 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 386 run tp @s ^-0.062 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 387 run tp @s ^-0.062 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 388 run tp @s ^-0.062 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 389 run tp @s ^-0.062 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 390 run tp @s ^-0.062 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 391 run tp @s ^-0.062 ^-1.521 ^-0.101 ~ ~