#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-0.0679f,0.1416f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-0.0687f,0.1767f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-0.0681f,0.2149f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-0.066f,0.2563f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-0.0626f,0.3004f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-0.0579f,0.3472f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-0.0519f,0.3965f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-0.0448f,0.4481f,0f]