#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run data modify entity @s Pose.Head set value [177.8678f,17.8451f,58.2174f]
execute if score .this aj.frame matches 169 run data modify entity @s Pose.Head set value [-167.5433f,2.0499f,117.9016f]
execute if score .this aj.frame matches 170 run data modify entity @s Pose.Head set value [-164.8972f,-16.1174f,176.5292f]
execute if score .this aj.frame matches 171 run data modify entity @s Pose.Head set value [-164.5871f,11.7066f,121.5267f]
execute if score .this aj.frame matches 172 run data modify entity @s Pose.Head set value [164.0218f,31.8952f,58.1644f]
execute if score .this aj.frame matches 173 run data modify entity @s Pose.Head set value [-162.1303f,18.4355f,124.1674f]
execute if score .this aj.frame matches 174 run data modify entity @s Pose.Head set value [-151.4633f,-12.726f,177.044f]
execute if score .this aj.frame matches 175 run data modify entity @s Pose.Head set value [-159.9449f,19.7487f,124.9739f]