#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 280 run data modify entity @s Pose.Head set value [-172.845f,15.412f,66.3799f]
execute if score .this aj.frame matches 281 run data modify entity @s Pose.Head set value [-171.0243f,-5.6864f,121.2242f]
execute if score .this aj.frame matches 282 run data modify entity @s Pose.Head set value [-176.4106f,-12.4694f,-179.7273f]
execute if score .this aj.frame matches 283 run data modify entity @s Pose.Head set value [-178.0713f,3.442f,118.5923f]
execute if score .this aj.frame matches 284 run data modify entity @s Pose.Head set value [164.8799f,12.8074f,55.7282f]
execute if score .this aj.frame matches 285 run data modify entity @s Pose.Head set value [-179.6885f,12.4561f,119.0085f]
execute if score .this aj.frame matches 286 run data modify entity @s Pose.Head set value [-159.969f,-1.7476f,-176.9826f]
execute if score .this aj.frame matches 287 run data modify entity @s Pose.Head set value [-174.1115f,19.0119f,124.9191f]