#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 232 run tp @s ^-2.686 ^-1.611 ^1.688 ~ ~
execute if score .this aj.frame matches 233 run tp @s ^-2.167 ^-1.51 ^1.599 ~ ~
execute if score .this aj.frame matches 234 run tp @s ^-1.692 ^-1.414 ^1.508 ~ ~
execute if score .this aj.frame matches 235 run tp @s ^-1.24 ^-1.325 ^1.476 ~ ~
execute if score .this aj.frame matches 236 run tp @s ^-0.857 ^-1.252 ^1.451 ~ ~
execute if score .this aj.frame matches 237 run tp @s ^-0.61 ^-1.208 ^1.405 ~ ~
execute if score .this aj.frame matches 238 run tp @s ^-0.635 ^-1.212 ^1.384 ~ ~
execute if score .this aj.frame matches 239 run tp @s ^-0.61 ^-1.194 ^1.403 ~ ~