#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [-34.6839f,3.9875f,112.2601f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [-28.6066f,-14.3601f,56.0542f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [-2.6483f,-27.0232f,-4.7234f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [-37.4457f,-10.3713f,62.0693f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [-38.0308f,20.8212f,118.7295f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [-45.4648f,-6.1743f,67.444f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [-22.129f,-37.822f,14.7969f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [-56.0307f,-2.0214f,73.0268f]