#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 312 run tp @s ^-0.066 ^-1.517 ^-0.109 ~ ~
execute if score .this aj.frame matches 313 run tp @s ^-0.065 ^-1.518 ^-0.107 ~ ~
execute if score .this aj.frame matches 314 run tp @s ^-0.064 ^-1.518 ^-0.106 ~ ~
execute if score .this aj.frame matches 315 run tp @s ^-0.064 ^-1.519 ^-0.104 ~ ~
execute if score .this aj.frame matches 316 run tp @s ^-0.063 ^-1.52 ^-0.103 ~ ~
execute if score .this aj.frame matches 317 run tp @s ^-0.063 ^-1.52 ^-0.102 ~ ~
execute if score .this aj.frame matches 318 run tp @s ^-0.063 ^-1.521 ^-0.101 ~ ~
execute if score .this aj.frame matches 319 run tp @s ^-0.062 ^-1.521 ^-0.101 ~ ~