#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^-0.064 ^-1.584 ^0.273 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^-0.064 ^-1.584 ^0.273 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^-0.064 ^-1.584 ^0.273 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^-0.063 ^-1.584 ^0.273 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^-0.063 ^-1.584 ^0.274 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^-0.063 ^-1.583 ^0.274 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^-0.062 ^-1.583 ^0.274 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^-0.086 ^-1.579 ^0.315 ~ ~