#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128..135 run function bluejay:animations/fly/tree/r_wing_display_128-135
execute if score .this aj.frame matches 136..143 run function bluejay:animations/fly/tree/r_wing_display_136-143
execute if score .this aj.frame matches 144..151 run function bluejay:animations/fly/tree/r_wing_display_144-151
execute if score .this aj.frame matches 152..159 run function bluejay:animations/fly/tree/r_wing_display_152-159
execute if score .this aj.frame matches 160..167 run function bluejay:animations/fly/tree/r_wing_display_160-167
execute if score .this aj.frame matches 168..175 run function bluejay:animations/fly/tree/r_wing_display_168-175
execute if score .this aj.frame matches 176..183 run function bluejay:animations/fly/tree/r_wing_display_176-183
execute if score .this aj.frame matches 184..191 run function bluejay:animations/fly/tree/r_wing_display_184-191