#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..63 run function bluejay:animations/fly/tree/r_wing_display_0-63
execute if score .this aj.frame matches 64..127 run function bluejay:animations/fly/tree/r_wing_display_64-127
execute if score .this aj.frame matches 128..191 run function bluejay:animations/fly/tree/r_wing_display_128-191
execute if score .this aj.frame matches 192..255 run function bluejay:animations/fly/tree/r_wing_display_192-255
execute if score .this aj.frame matches 256..319 run function bluejay:animations/fly/tree/r_wing_display_256-319
execute if score .this aj.frame matches 399 run data modify entity @s Pose.Head set value [0f,0f,0f]