#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 248 run data modify entity @s Pose.Head set value [-159.6172f,17.7208f,70.7734f]
execute if score .this aj.frame matches 249 run data modify entity @s Pose.Head set value [-156.7835f,-19.3334f,119.6403f]
execute if score .this aj.frame matches 250 run data modify entity @s Pose.Head set value [174.1735f,-36.826f,-172.9614f]
execute if score .this aj.frame matches 251 run data modify entity @s Pose.Head set value [-156.5569f,-19.5166f,119.5854f]
execute if score .this aj.frame matches 252 run data modify entity @s Pose.Head set value [-159.0396f,17.8007f,70.9893f]
execute if score .this aj.frame matches 253 run data modify entity @s Pose.Head set value [-156.273f,-19.7778f,119.533f]
execute if score .this aj.frame matches 254 run data modify entity @s Pose.Head set value [173.8272f,-37.513f,-172.6674f]
execute if score .this aj.frame matches 255 run data modify entity @s Pose.Head set value [-155.9507f,-20.0941f,119.4832f]