#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [0.1939f,1.4889f,0f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [0.2112f,1.549f,0f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [0.2286f,1.6077f,0f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [0.2458f,1.665f,0f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [0.2629f,1.7205f,0f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [0.2797f,1.7742f,0f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [0.2963f,1.8257f,0f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [0.3125f,1.875f,0f]