#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 264 run tp @s ^-0.585 ^-1.163 ^1.429 ~ ~
execute if score .this aj.frame matches 265 run tp @s ^-0.61 ^-1.186 ^1.409 ~ ~
execute if score .this aj.frame matches 266 run tp @s ^-0.634 ^-1.206 ^1.388 ~ ~
execute if score .this aj.frame matches 267 run tp @s ^-0.609 ^-1.208 ^1.409 ~ ~
execute if score .this aj.frame matches 268 run tp @s ^-0.585 ^-1.198 ^1.43 ~ ~
execute if score .this aj.frame matches 269 run tp @s ^-0.609 ^-1.186 ^1.41 ~ ~
execute if score .this aj.frame matches 270 run tp @s ^-0.634 ^-1.172 ^1.389 ~ ~
execute if score .this aj.frame matches 271 run tp @s ^-0.609 ^-1.152 ^1.409 ~ ~