#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 272 run data modify entity @s Pose.Head set value [-156.0075f,17.5142f,72.5401f]
execute if score .this aj.frame matches 273 run data modify entity @s Pose.Head set value [-154.7292f,-21.8831f,119.5943f]
execute if score .this aj.frame matches 274 run data modify entity @s Pose.Head set value [172.1768f,-39.2113f,-171.0639f]
execute if score .this aj.frame matches 275 run data modify entity @s Pose.Head set value [-155.1778f,-21.5872f,119.745f]
execute if score .this aj.frame matches 276 run data modify entity @s Pose.Head set value [-157.0635f,17.3038f,72.1918f]
execute if score .this aj.frame matches 277 run data modify entity @s Pose.Head set value [-155.8167f,-21.1106f,119.9288f]
execute if score .this aj.frame matches 278 run data modify entity @s Pose.Head set value [174.0111f,-34.8431f,-172.4686f]
execute if score .this aj.frame matches 279 run data modify entity @s Pose.Head set value [-162.5316f,-15.1778f,121.377f]