#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^1.587 ^-0.054 ^1.276 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^1.6 ^-0.016 ^1.108 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^1.643 ^0.035 ^0.889 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^1.761 ^0.114 ^0.636 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^1.88 ^0.2 ^0.351 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^1.923 ^0.27 ^0.034 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^1.924 ^0.341 ^-0.301 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^1.939 ^0.425 ^-0.641 ~ ~