#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^1.419 ^-0.024 ^1.195 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^1.4 ^-0.023 ^1.223 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^1.382 ^-0.034 ^1.251 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^1.396 ^-0.045 ^1.224 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^1.41 ^-0.058 ^1.196 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^1.393 ^-0.079 ^1.225 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^1.377 ^-0.091 ^1.253 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^1.391 ^-0.08 ^1.225 ~ ~