#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.914 ^-0.79 ^1.819 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.97 ^-0.746 ^1.836 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^1.021 ^-0.701 ^1.847 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^1.073 ^-0.63 ^1.912 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^1.123 ^-0.564 ^1.972 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^1.164 ^-0.526 ^1.966 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^1.2 ^-0.492 ^1.952 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^1.24 ^-0.439 ^1.99 ~ ~