#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^1.474 ^-0.006 ^1.157 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^1.45 ^-0.023 ^1.176 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^1.417 ^-0.054 ^1.215 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^1.424 ^-0.076 ^1.209 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^1.434 ^-0.082 ^1.194 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^1.411 ^-0.08 ^1.22 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^1.39 ^-0.069 ^1.247 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^1.405 ^-0.045 ^1.221 ~ ~