#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [-124.189f,39.8449f,83.2292f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [-129.5514f,-13.2114f,106.7795f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [-163.9531f,-40.6035f,168.623f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [-161.9591f,2.4155f,116.2752f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [160.9085f,16.1237f,55.0182f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [163.8573f,19.2986f,115.9067f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [-169.5829f,30.9356f,-177.6552f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [136.2373f,27.4919f,110.8496f]