#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run data modify entity @s Pose.Head set value [0.239f,0.9832f,0f]
execute if score .this aj.frame matches 81 run data modify entity @s Pose.Head set value [0.2057f,0.8422f,0f]
execute if score .this aj.frame matches 82 run data modify entity @s Pose.Head set value [0.17f,0.6924f,0f]
execute if score .this aj.frame matches 83 run data modify entity @s Pose.Head set value [0.1316f,0.5334f,0f]
execute if score .this aj.frame matches 84 run data modify entity @s Pose.Head set value [0.0905f,0.3651f,0f]
execute if score .this aj.frame matches 85 run data modify entity @s Pose.Head set value [0.0466f,0.1874f,0f]
execute if score .this aj.frame matches 86 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 87 run data modify entity @s Pose.Head set value [-8.5805f,-2.9141f,60.3541f]