#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.062 ^-1.583 ^-0.101 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.062 ^-1.587 ^-0.053 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.062 ^-1.586 ^-0.006 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.062 ^-1.584 ^0.04 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.062 ^-1.588 ^0.088 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.062 ^-1.584 ^0.134 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.062 ^-1.586 ^0.181 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.062 ^-1.587 ^0.229 ~ ~