#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 256..263 run function bluejay:animations/fly/tree/r_wing_display_256-263
execute if score .this aj.frame matches 264..271 run function bluejay:animations/fly/tree/r_wing_display_264-271
execute if score .this aj.frame matches 272..279 run function bluejay:animations/fly/tree/r_wing_display_272-279
execute if score .this aj.frame matches 280..287 run function bluejay:animations/fly/tree/r_wing_display_280-287
execute if score .this aj.frame matches 288..295 run function bluejay:animations/fly/tree/r_wing_display_288-295
execute if score .this aj.frame matches 296..303 run function bluejay:animations/fly/tree/r_wing_display_296-303
execute if score .this aj.frame matches 304..311 run function bluejay:animations/fly/tree/r_wing_display_304-311
execute if score .this aj.frame matches 312..319 run function bluejay:animations/fly/tree/r_wing_display_312-319