#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 296 run tp @s ^-0.074 ^-1.509 ^-0.13 ~ ~
execute if score .this aj.frame matches 297 run tp @s ^-0.075 ^-1.508 ^-0.132 ~ ~
execute if score .this aj.frame matches 298 run tp @s ^-0.075 ^-1.508 ^-0.133 ~ ~
execute if score .this aj.frame matches 299 run tp @s ^-0.076 ^-1.508 ^-0.133 ~ ~
execute if score .this aj.frame matches 300 run tp @s ^-0.075 ^-1.508 ^-0.133 ~ ~
execute if score .this aj.frame matches 301 run tp @s ^-0.075 ^-1.508 ^-0.132 ~ ~
execute if score .this aj.frame matches 302 run tp @s ^-0.075 ^-1.509 ^-0.131 ~ ~
execute if score .this aj.frame matches 303 run tp @s ^-0.074 ^-1.509 ^-0.129 ~ ~