#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [-46.2154f,41.9853f,123.6526f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [-68.1754f,0.4429f,77.7804f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [-50.4005f,-52.1298f,43.8999f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [-80.4139f,-0.0506f,81.5672f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [-76.7143f,55.7708f,107.5527f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [-90.9396f,-3.6587f,84.827f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [-83.382f,-66.7828f,78.2733f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [-98.4332f,-9.2568f,87.8055f]