#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 240 run data modify entity @s Pose.Head set value [-158.7922f,17.407f,71.348f]
execute if score .this aj.frame matches 241 run data modify entity @s Pose.Head set value [-156.7276f,-19.8317f,119.8698f]
execute if score .this aj.frame matches 242 run data modify entity @s Pose.Head set value [173.8449f,-36.7642f,-172.5896f]
execute if score .this aj.frame matches 243 run data modify entity @s Pose.Head set value [-156.9269f,-19.4789f,119.8153f]
execute if score .this aj.frame matches 244 run data modify entity @s Pose.Head set value [-159.6154f,17.589f,70.857f]
execute if score .this aj.frame matches 245 run data modify entity @s Pose.Head set value [-156.9883f,-19.2922f,119.7565f]
execute if score .this aj.frame matches 246 run data modify entity @s Pose.Head set value [174.2226f,-36.5073f,-172.9743f]
execute if score .this aj.frame matches 247 run data modify entity @s Pose.Head set value [-156.9337f,-19.251f,119.6975f]