#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [-104.194f,48.3729f,89.7685f]
execute if score .this aj.frame matches 113 run data modify entity @s Pose.Head set value [-102.6782f,-15.0475f,90.3108f]
execute if score .this aj.frame matches 114 run data modify entity @s Pose.Head set value [-115.2825f,-77.3217f,111.9799f]
execute if score .this aj.frame matches 115 run data modify entity @s Pose.Head set value [-104.6324f,-19.4256f,92.2346f]
execute if score .this aj.frame matches 116 run data modify entity @s Pose.Head set value [-109.6303f,39.6824f,88.6902f]
execute if score .this aj.frame matches 117 run data modify entity @s Pose.Head set value [-106.0995f,-21.5808f,94.004f]
execute if score .this aj.frame matches 118 run data modify entity @s Pose.Head set value [-140.3109f,-79.2877f,139.0823f]
execute if score .this aj.frame matches 119 run data modify entity @s Pose.Head set value [-108.9926f,-21.4891f,96.3267f]