#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run data modify entity @s Pose.Head set value [108.4573f,-18.0755f,68.4626f]
execute if score .this aj.frame matches 153 run data modify entity @s Pose.Head set value [117.8819f,32.6126f,103.499f]
execute if score .this aj.frame matches 154 run data modify entity @s Pose.Head set value [-167.1477f,57.7082f,-170.4559f]
execute if score .this aj.frame matches 155 run data modify entity @s Pose.Head set value [119.9801f,32.3684f,104.5092f]
execute if score .this aj.frame matches 156 run data modify entity @s Pose.Head set value [114.0174f,-15.3733f,66.6685f]
execute if score .this aj.frame matches 157 run data modify entity @s Pose.Head set value [129.5157f,29.9776f,109.6151f]
execute if score .this aj.frame matches 158 run data modify entity @s Pose.Head set value [-170.7708f,42.0712f,-173.0645f]
execute if score .this aj.frame matches 159 run data modify entity @s Pose.Head set value [143.3077f,23.8576f,115.7612f]