#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 232 run data modify entity @s Pose.Head set value [-121.6207f,19.7773f,85.2672f]
execute if score .this aj.frame matches 233 run data modify entity @s Pose.Head set value [-129.7637f,-37.9244f,108.404f]
execute if score .this aj.frame matches 234 run data modify entity @s Pose.Head set value [156.6972f,-55.7592f,-157.807f]
execute if score .this aj.frame matches 235 run data modify entity @s Pose.Head set value [-146.8581f,-30.5752f,117.5436f]
execute if score .this aj.frame matches 236 run data modify entity @s Pose.Head set value [-152.2084f,16.6283f,74.4232f]
execute if score .this aj.frame matches 237 run data modify entity @s Pose.Head set value [-155.8142f,-21.1073f,119.9291f]
execute if score .this aj.frame matches 238 run data modify entity @s Pose.Head set value [172.9107f,-37.8042f,-171.6906f]
execute if score .this aj.frame matches 239 run data modify entity @s Pose.Head set value [-156.366f,-20.3692f,119.912f]