#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 280 run tp @s ^-0.398 ^-1.304 ^1.149 ~ ~
execute if score .this aj.frame matches 281 run tp @s ^-0.349 ^-1.351 ^1.016 ~ ~
execute if score .this aj.frame matches 282 run tp @s ^-0.304 ^-1.4 ^0.887 ~ ~
execute if score .this aj.frame matches 283 run tp @s ^-0.206 ^-1.43 ^0.773 ~ ~
execute if score .this aj.frame matches 284 run tp @s ^-0.119 ^-1.452 ^0.665 ~ ~
execute if score .this aj.frame matches 285 run tp @s ^-0.067 ^-1.519 ^0.47 ~ ~
execute if score .this aj.frame matches 286 run tp @s ^-0.027 ^-1.583 ^0.271 ~ ~
execute if score .this aj.frame matches 287 run tp @s ^0.061 ^-1.606 ^0.086 ~ ~