#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 200 run tp @s ^-0.772 ^1.043 ^-3.639 ~ ~
execute if score .this aj.frame matches 201 run tp @s ^-1.26 ^0.997 ^-3.562 ~ ~
execute if score .this aj.frame matches 202 run tp @s ^-1.795 ^0.938 ^-3.46 ~ ~
execute if score .this aj.frame matches 203 run tp @s ^-2.377 ^0.884 ^-3.398 ~ ~
execute if score .this aj.frame matches 204 run tp @s ^-2.98 ^0.822 ^-3.315 ~ ~
execute if score .this aj.frame matches 205 run tp @s ^-3.579 ^0.736 ^-3.154 ~ ~
execute if score .this aj.frame matches 206 run tp @s ^-4.173 ^0.643 ^-2.976 ~ ~
execute if score .this aj.frame matches 207 run tp @s ^-4.758 ^0.56 ^-2.848 ~ ~