#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.bluejay.bone.birdhouse] run function bluejay:animations/fly/tree/birdhouse_root_top
execute if entity @s[tag=aj.bluejay.bone.head] run function bluejay:animations/fly/tree/head_root_top
execute if entity @s[tag=aj.bluejay.bone.body] run function bluejay:animations/fly/tree/body_root_top
execute if entity @s[tag=aj.bluejay.bone.r_wing] run function bluejay:animations/fly/tree/r_wing_root_top
execute if entity @s[tag=aj.bluejay.bone.l_wing] run function bluejay:animations/fly/tree/l_wing_root_top
execute if entity @s[tag=aj.bluejay.bone.tail] run function bluejay:animations/fly/tree/tail_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame