#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 312 run tp @s ^0.426 ^-1.371 ^-0.094 ~ ~
execute if score .this aj.frame matches 313 run tp @s ^0.429 ^-1.379 ^-0.09 ~ ~
execute if score .this aj.frame matches 314 run tp @s ^0.432 ^-1.387 ^-0.087 ~ ~
execute if score .this aj.frame matches 315 run tp @s ^0.434 ^-1.393 ^-0.084 ~ ~
execute if score .this aj.frame matches 316 run tp @s ^0.435 ^-1.399 ^-0.081 ~ ~
execute if score .this aj.frame matches 317 run tp @s ^0.437 ^-1.403 ^-0.08 ~ ~
execute if score .this aj.frame matches 318 run tp @s ^0.437 ^-1.406 ^-0.079 ~ ~
execute if score .this aj.frame matches 319 run tp @s ^0.438 ^-1.407 ^-0.078 ~ ~