#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.433 ^-1.47 ^0.312 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.433 ^-1.47 ^0.313 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.433 ^-1.47 ^0.313 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.433 ^-1.47 ^0.313 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.433 ^-1.47 ^0.314 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.433 ^-1.47 ^0.314 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.432 ^-1.47 ^0.314 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.432 ^-1.47 ^0.314 ~ ~