#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 200 run tp @s ^-0.728 ^1.196 ^-3.09 ~ ~
execute if score .this aj.frame matches 201 run tp @s ^-1.207 ^1.134 ^-3.04 ~ ~
execute if score .this aj.frame matches 202 run tp @s ^-1.742 ^1.065 ^-2.965 ~ ~
execute if score .this aj.frame matches 203 run tp @s ^-2.317 ^0.99 ^-2.869 ~ ~
execute if score .this aj.frame matches 204 run tp @s ^-2.917 ^0.912 ^-2.754 ~ ~
execute if score .this aj.frame matches 205 run tp @s ^-3.524 ^0.832 ^-2.623 ~ ~
execute if score .this aj.frame matches 206 run tp @s ^-4.124 ^0.749 ^-2.476 ~ ~
execute if score .this aj.frame matches 207 run tp @s ^-4.7 ^0.661 ^-2.318 ~ ~