#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run data modify entity @s Pose.Head set value [-174.7056f,-17.5307f,176.2795f]
execute if score .this aj.frame matches 169 run data modify entity @s Pose.Head set value [-170.0173f,-17.3288f,176.3152f]
execute if score .this aj.frame matches 170 run data modify entity @s Pose.Head set value [-164.8972f,-16.1174f,176.5292f]
execute if score .this aj.frame matches 171 run data modify entity @s Pose.Head set value [-159.9411f,-14.5021f,176.8145f]
execute if score .this aj.frame matches 172 run data modify entity @s Pose.Head set value [-155.7446f,-13.0886f,177.0641f]
execute if score .this aj.frame matches 173 run data modify entity @s Pose.Head set value [-152.9037f,-12.4827f,177.171f]
execute if score .this aj.frame matches 174 run data modify entity @s Pose.Head set value [-151.4633f,-12.726f,177.044f]
execute if score .this aj.frame matches 175 run data modify entity @s Pose.Head set value [-150.5435f,-13.3172f,176.7356f]