#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [3.2475f,-21.2392f,-9.8405f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [0.8786f,-24.0974f,-7.938f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [-2.6483f,-27.0232f,-4.7234f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [-7.5f,-30f,0f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [-11.5692f,-32.191f,4.0772f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [-16.4757f,-34.8215f,9.0404f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [-22.129f,-37.822f,14.7969f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [-28.4386f,-41.1228f,21.2538f]