#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^1.106 ^0.124 ^1.649 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^1.111 ^0.131 ^1.655 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^1.116 ^0.124 ^1.66 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^1.12 ^0.108 ^1.664 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^1.122 ^0.089 ^1.668 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^1.125 ^0.073 ^1.67 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^1.126 ^0.066 ^1.672 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^1.127 ^0.071 ^1.673 ~ ~