#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [-153.5794f,-70.2359f,154.4296f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [-159.7978f,-57.2646f,162.4634f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [-163.9531f,-40.6035f,168.623f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [-166.5271f,-21.8527f,173.2996f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [-168.0021f,-2.6124f,176.8845f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [-168.86f,15.5171f,179.7691f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [-169.5829f,30.9356f,-177.6552f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [-170.6529f,42.0429f,-174.9973f]