#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 216 run data modify entity @s Pose.Head set value [62.0593f,-36.417f,-45.0401f]
execute if score .this aj.frame matches 217 run data modify entity @s Pose.Head set value [83.2476f,-44.1788f,-63.9643f]
execute if score .this aj.frame matches 218 run data modify entity @s Pose.Head set value [104.8312f,-51.5132f,-83.4926f]
execute if score .this aj.frame matches 219 run data modify entity @s Pose.Head set value [125.5012f,-58.2569f,-102.4548f]
execute if score .this aj.frame matches 220 run data modify entity @s Pose.Head set value [143.949f,-64.2461f,-119.6806f]
execute if score .this aj.frame matches 221 run data modify entity @s Pose.Head set value [158.8661f,-69.3175f,-133.9997f]
execute if score .this aj.frame matches 222 run data modify entity @s Pose.Head set value [168.9439f,-73.3074f,-144.242f]
execute if score .this aj.frame matches 223 run data modify entity @s Pose.Head set value [173.7727f,-76.1822f,-150.2669f]