#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [0.5591f,-2.7837f,-1.4433f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [1.4402f,-4.5078f,-2.9521f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [2.4996f,-6.4315f,-4.7234f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [3.5704f,-8.5381f,-6.5603f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [4.4853f,-10.8113f,-8.266f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [5.0776f,-13.2345f,-9.6437f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [5.18f,-15.7912f,-10.4965f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [4.6257f,-18.4649f,-10.6277f]