#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^1.054 ^-0.014 ^1.072 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^1.101 ^0.03 ^0.903 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^1.175 ^0.089 ^0.685 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^1.262 ^0.16 ^0.429 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^1.347 ^0.241 ^0.148 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^1.415 ^0.33 ^-0.148 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^1.438 ^0.474 ^-0.399 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^1.443 ^0.643 ^-0.611 ~ ~