#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 264 run data modify entity @s Pose.Head set value [172.5123f,-39.4802f,-171.4683f]
execute if score .this aj.frame matches 265 run data modify entity @s Pose.Head set value [172.4013f,-39.6074f,-171.362f]
execute if score .this aj.frame matches 266 run data modify entity @s Pose.Head set value [172.3021f,-39.709f,-171.2655f]
execute if score .this aj.frame matches 267 run data modify entity @s Pose.Head set value [172.2167f,-39.7818f,-171.1806f]
execute if score .this aj.frame matches 268 run data modify entity @s Pose.Head set value [172.1471f,-39.8225f,-171.1091f]
execute if score .this aj.frame matches 269 run data modify entity @s Pose.Head set value [172.0955f,-39.8278f,-171.0529f]
execute if score .this aj.frame matches 270 run data modify entity @s Pose.Head set value [172.0638f,-39.7946f,-171.0137f]
execute if score .this aj.frame matches 271 run data modify entity @s Pose.Head set value [172.0541f,-39.7196f,-170.9934f]