#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 248 run tp @s ^-1.014 ^-1.042 ^1.074 ~ ~
execute if score .this aj.frame matches 249 run tp @s ^-1.013 ^-1.027 ^1.073 ~ ~
execute if score .this aj.frame matches 250 run tp @s ^-1.012 ^-1.008 ^1.073 ~ ~
execute if score .this aj.frame matches 251 run tp @s ^-1.011 ^-0.992 ^1.072 ~ ~
execute if score .this aj.frame matches 252 run tp @s ^-1.01 ^-0.986 ^1.072 ~ ~
execute if score .this aj.frame matches 253 run tp @s ^-1.009 ^-0.992 ^1.071 ~ ~
execute if score .this aj.frame matches 254 run tp @s ^-1.008 ^-1.007 ^1.07 ~ ~
execute if score .this aj.frame matches 255 run tp @s ^-1.006 ^-1.025 ^1.069 ~ ~