#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 112 run tp @s ^0.913 ^-0.859 ^1.252 ~ ~
execute if score .this aj.frame matches 113 run tp @s ^0.952 ^-0.772 ^1.294 ~ ~
execute if score .this aj.frame matches 114 run tp @s ^0.995 ^-0.69 ^1.335 ~ ~
execute if score .this aj.frame matches 115 run tp @s ^1.039 ^-0.615 ^1.371 ~ ~
execute if score .this aj.frame matches 116 run tp @s ^1.081 ^-0.547 ^1.402 ~ ~
execute if score .this aj.frame matches 117 run tp @s ^1.118 ^-0.489 ^1.427 ~ ~
execute if score .this aj.frame matches 118 run tp @s ^1.149 ^-0.439 ^1.444 ~ ~
execute if score .this aj.frame matches 119 run tp @s ^1.17 ^-0.399 ^1.454 ~ ~