#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 320..327 run function bluejay:animations/fly/tree/tail_root_320-327
execute if score .this aj.frame matches 328..335 run function bluejay:animations/fly/tree/tail_root_328-335
execute if score .this aj.frame matches 336..343 run function bluejay:animations/fly/tree/tail_root_336-343
execute if score .this aj.frame matches 344..351 run function bluejay:animations/fly/tree/tail_root_344-351
execute if score .this aj.frame matches 352..359 run function bluejay:animations/fly/tree/tail_root_352-359
execute if score .this aj.frame matches 360..367 run function bluejay:animations/fly/tree/tail_root_360-367
execute if score .this aj.frame matches 368..375 run function bluejay:animations/fly/tree/tail_root_368-375
execute if score .this aj.frame matches 376..383 run function bluejay:animations/fly/tree/tail_root_376-383