#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 200 run data modify entity @s Pose.Head set value [-34.0322f,80.4615f,-37.5548f]
execute if score .this aj.frame matches 201 run data modify entity @s Pose.Head set value [-17.8966f,80.3542f,-21.5235f]
execute if score .this aj.frame matches 202 run data modify entity @s Pose.Head set value [-6.0596f,80.2417f,-9.7896f]
execute if score .this aj.frame matches 203 run data modify entity @s Pose.Head set value [2.9701f,80.313f,-0.7824f]
execute if score .this aj.frame matches 204 run data modify entity @s Pose.Head set value [7.7737f,80.6146f,4.1652f]
execute if score .this aj.frame matches 205 run data modify entity @s Pose.Head set value [9.2307f,80.9216f,5.8649f]
execute if score .this aj.frame matches 206 run data modify entity @s Pose.Head set value [8.221f,81.0088f,5.1286f]
execute if score .this aj.frame matches 207 run data modify entity @s Pose.Head set value [5.6244f,80.6511f,2.7683f]