#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.bluejay.fly.loopMode matches 0 run function bluejay:animations/fly/stop
execute if score @s aj.bluejay.fly.loopMode matches 1 run function bluejay:animations/fly/pause
execute if score @s aj.bluejay.fly.loopMode matches 2 run function bluejay:animations/fly/zzz/execute/13