#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#bluejay:bone_entities,tag=aj.bluejay.bone,distance=..8.506] if score @s aj.id = .this aj.id run function bluejay:animations/fly/tree/trunk
scoreboard players operation @s aj.frame += .aj.bluejay.framerate aj.i
scoreboard players set .aj.animation aj.bluejay.animating 1
execute unless score @s aj.frame matches 0..400 run function bluejay:animations/fly/edge