#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.bluejay.anim.fly] at @s run function bluejay:animations/fly/next_frame
scoreboard players operation @s aj.bluejay.animating = .aj.animation aj.bluejay.animating