#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.bluejay.bone.birdhouse] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.bluejay.bone.head] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.bluejay.bone.l_wing] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.bluejay.bone.r_wing] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.bluejay.bone.tail] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.bluejay.bone.body] Pose.Head set value [0f,0f,0f]
tp @s ~ ~ ~ ~ ~