#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.amirkaka.idle5.loopMode matches 0 run function amirkaka:animations/idle5/stop
execute if score @s aj.amirkaka.idle5.loopMode matches 1 run function amirkaka:animations/idle5/pause
execute if score @s aj.amirkaka.idle5.loopMode matches 2 run function amirkaka:animations/idle5/zzz/execute/32