#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['new','aj.cob','aj.cob.root']}
execute as @e[type=minecraft:marker,tag=aj.cob.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function cob:summon/zzz/execute/2
function cob:assert_animation_flags