#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.amirkaka.root] at @s run function amirkaka:animations/idle3/zzz/conditional/26
execute if score #execute aj.i matches 0 run function amirkaka:animations/idle3/zzz/conditional/27