#Project generated by Animated Java (https://animated-java.dev/)

schedule function cobblestone:animation_loop 1t
scoreboard players set .aj.anim_loop aj.cobblestone.animating 1
scoreboard players set .aj.animation aj.cobblestone.animating 0
execute as @e[type=minecraft:marker,tag=aj.cobblestone.root] run function cobblestone:zzz/execute/11
execute if score .aj.animation aj.cobblestone.animating matches 0 run function cobblestone:zzz/execute/12