#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.wheelguy.anim.idle] at @s run function wheelguy:animations/idle/next_frame
scoreboard players operation @s aj.wheelguy.animating = .aj.animation aj.wheelguy.animating