#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#wheelguy:bone_entities,tag=aj.wheelguy.bone] if score @s aj.id = .this aj.id run function wheelguy:zzz/execute/8