#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.glare.anim.idle] at @s run function glare:animations/idle/next_frame
scoreboard players operation @s aj.glare.animating = .aj.animation aj.glare.animating