#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#glare:bone_entities,tag=aj.glare.bone] if score @s aj.id = .this aj.id run function glare:zzz/execute/8