#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-4.2044f,0.5507f,3.1322f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-1.6659f,0.2182f,1.2411f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [0f,0f,0f]