#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-14.6483f,2.1677f,37.0548f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-15.3899f,2.2774f,-33.974f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-16.126f,2.3863f,-104.4703f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-16.8546f,2.4942f,-174.2567f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-17.574f,2.6006f,116.8445f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-18.2822f,2.7054f,49.0106f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-18.9775f,2.8083f,-17.5808f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-19.658f,2.909f,-82.7522f]