#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-1.6659f,0.2182f,1.2411f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-4.2044f,0.5507f,3.1322f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-6.9016f,0.9039f,5.1416f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-9.0435f,1.1845f,6.7372f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-9.9162f,1.2988f,7.3873f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-9.0435f,1.1845f,6.7372f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-6.9016f,0.9039f,5.1416f]