#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function amirkaka:animations/idle5/tree/head_root_0-7
execute if score .this aj.frame matches 8..15 run function amirkaka:animations/idle5/tree/head_root_8-15
execute if score .this aj.frame matches 16..23 run function amirkaka:animations/idle5/tree/head_root_16-23
execute if score .this aj.frame matches 24..30 run function amirkaka:animations/idle5/tree/head_root_24-30