#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~