#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-4.5862f,-0.5805f,-1.119f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-11.5747f,-1.4651f,-2.8241f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-19f,-2.4049f,-4.6358f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-24.8966f,-3.1513f,-6.0745f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-27.2989f,-3.4553f,-6.6607f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-24.8966f,-3.1513f,-6.0745f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-19f,-2.4049f,-4.6358f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-11.5747f,-1.4651f,-2.8241f]