#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.344 ^-0.27 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.344 ^-0.111 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.344 ^0.06 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.344 ^0.194 ^0 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.344 ^0.25 ^0 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.344 ^0.194 ^0 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.344 ^0.06 ^0 ~ ~