#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-4.5862f,-0.5805f,-1.119f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,0f,0f]