#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-7.42f,0f,-23.08f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-2.94f,0f,4.44f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,0f,22.5f]