#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-25f,0f,-17.5f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-26.6488f,1.7285f,-16.8512f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-27.1138f,4.3624f,-12.5862f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-26.5452f,7.1609f,-6.3548f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-25.0937f,9.3832f,0.1937f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-22.9098f,10.2886f,5.4098f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-21.1525f,9.9922f,7.6579f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-18.7782f,9.1877f,9.927f]