#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,22.5f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-2.94f,0f,4.44f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-7.42f,0f,-23.08f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-12.18f,0f,-52.32f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-15.96f,0f,-75.54f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-17.5f,0f,-85f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-15.96f,0f,-75.54f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-12.18f,0f,-52.32f]