#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-76.9533f,1.9927f,6.9608f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-46.8796f,1.214f,13.0336f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-18.5749f,0.481f,18.7492f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0f,0f,22.5f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,0f,22.5f]