#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-4.2848f,-1.6543f,9.8491f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-8.5695f,-3.3087f,19.6983f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-12.8543f,-4.963f,29.5474f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-17.1391f,-6.6174f,39.3965f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-21.4238f,-8.2717f,49.2457f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-17.1391f,-6.6174f,39.3965f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-12.8543f,-4.963f,29.5474f]