#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-3.18f,0f,31.56f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-1.26f,0f,-1.08f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,0f,-22.5f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [0f,0f,-22.5f]