#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [20.3218f,-2.6181f,-17.6471f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0f,0f,-22.5f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,0f,-22.5f]