#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-8.5695f,-3.3087f,19.6983f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-4.2848f,-1.6543f,9.8491f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [3.6991f,-0.7982f,1.9446f]