#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [20.3218f,-2.6181f,-17.6471f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [51.2883f,-6.6076f,-10.2522f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [84.1902f,-10.8464f,-2.3951f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [110.3182f,-14.2126f,3.8444f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [120.9629f,-15.5839f,6.3864f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [110.3182f,-14.2126f,3.8444f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [84.1902f,-10.8464f,-2.3951f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [51.2883f,-6.6076f,-10.2522f]