#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [9.3357f,-2.0145f,4.9079f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [15.3246f,-3.3068f,8.0563f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [20.0806f,-4.333f,10.5566f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [22.0182f,-4.7511f,11.5752f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [20.0806f,-4.333f,10.5566f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [15.3246f,-3.3068f,8.0563f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [9.3357f,-2.0145f,4.9079f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [3.6991f,-0.7982f,1.9446f]