#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.25 ^-4.188 ^-0.937 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.25 ^-4.188 ^-0.937 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.25 ^-4.188 ^-0.937 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.25 ^-4.188 ^-0.937 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.25 ^-0.125 ^-1.562 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.25 ^-0.062 ^-1.586 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.25 ^-0.088 ^-1.601 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.25 ^-0.188 ^-1.608 ~ ~