#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.25 ^-0.345 ^-1.609 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.25 ^-0.543 ^-1.605 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.25 ^-0.766 ^-1.598 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.25 ^-0.998 ^-1.589 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.25 ^-1.222 ^-1.579 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.25 ^-1.423 ^-1.571 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.25 ^-1.584 ^-1.565 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.25 ^-1.688 ^-1.562 ~ ~