#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.062 ^-3.75 ^0.125 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.062 ^-3.569 ^0.125 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.062 ^-3.315 ^0.125 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.062 ^-3.01 ^0.125 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.062 ^-2.674 ^0.125 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.062 ^-2.327 ^0.125 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.062 ^-1.991 ^0.125 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.062 ^-1.686 ^0.125 ~ ~