#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.boat.bone.front] run function boat:animations/new/tree/front_display_top
execute if entity @s[tag=aj.boat.bone.back] run function boat:animations/new/tree/back_display_top
execute if entity @s[tag=aj.boat.bone.left] run function boat:animations/new/tree/left_display_top
execute if entity @s[tag=aj.boat.bone.right] run function boat:animations/new/tree/right_display_top
execute if entity @s[tag=aj.boat.bone.paddle_left] run function boat:animations/new/tree/paddle_left_display_top
execute if entity @s[tag=aj.boat.bone.paddle_right] run function boat:animations/new/tree/paddle_right_display_top
execute if entity @s[tag=aj.boat.bone.bottom] run function boat:animations/new/tree/bottom_display_top
execute if entity @s[tag=aj.boat.bone.bottom_no_water] run function boat:animations/new/tree/bottom_no_water_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~