#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function boat:animations/new/tree/front_root_0-7
execute if score .this aj.frame matches 8..15 run function boat:animations/new/tree/front_root_8-15
execute if score .this aj.frame matches 16..21 run function boat:animations/new/tree/front_root_16-21