#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.709 ^-4.125 ^-0.312 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.709 ^-3.688 ^-0.312 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.709 ^-3.044 ^-0.312 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.709 ^-2.331 ^-0.312 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.709 ^-1.687 ^-0.312 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.709 ^-1.25 ^-0.312 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.709 ^-1.25 ^-0.312 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.727 ^-1.25 ^-0.312 ~ ~