#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.756 ^-1.25 ^-0.312 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.762 ^-1.25 ^-0.312 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.709 ^-1.25 ^-0.312 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.635 ^-1.25 ^-0.312 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.528 ^-1.25 ^-0.312 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.401 ^-1.25 ^-0.312 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.268 ^-1.25 ^-0.312 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.141 ^-1.25 ^-0.312 ~ ~