#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [125.2644f,30f,144.7356f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [125.2644f,30f,144.7356f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [125.2644f,30f,144.7356f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [125.2644f,30f,144.7356f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [125.2644f,30f,144.7356f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [125.2644f,30f,144.7356f]