#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.562 ^-3.563 ^1.125 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-2.812 ^-0.688 ^1.125 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-2.666 ^-0.689 ^1.125 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-2.203 ^-1.008 ^1.125 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-1.67 ^-1.417 ^1.125 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-1.312 ^-1.688 ^1.125 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-1.312 ^-1.688 ^1.125 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-1.33 ^-1.688 ^1.125 ~ ~