#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-1.359 ^-1.688 ^1.125 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-1.365 ^-1.688 ^1.125 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-1.312 ^-1.688 ^1.125 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-1.238 ^-1.688 ^1.125 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-1.131 ^-1.688 ^1.125 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-1.004 ^-1.688 ^1.125 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.871 ^-1.688 ^1.125 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.744 ^-1.688 ^1.125 ~ ~