#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.boat.bone.front] run function boat:animations/new/tree/front_root_top
execute if entity @s[tag=aj.boat.bone.back] run function boat:animations/new/tree/back_root_top
execute if entity @s[tag=aj.boat.bone.left] run function boat:animations/new/tree/left_root_top
execute if entity @s[tag=aj.boat.bone.right] run function boat:animations/new/tree/right_root_top
execute if entity @s[tag=aj.boat.bone.paddle_left] run function boat:animations/new/tree/paddle_left_root_top
execute if entity @s[tag=aj.boat.bone.paddle_right] run function boat:animations/new/tree/paddle_right_root_top
execute if entity @s[tag=aj.boat.bone.bottom] run function boat:animations/new/tree/bottom_root_top
execute if entity @s[tag=aj.boat.bone.bottom_no_water] run function boat:animations/new/tree/bottom_no_water_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame