#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:marker ~ ~ ~ {Tags:['new','aj.wheelguy','aj.wheelguy.root']}
execute as @e[type=minecraft:marker,tag=aj.wheelguy.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function wheelguy:summon/zzz/execute/2
function wheelguy:assert_animation_flags