#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.cob.anim.loop
execute if score .aj.cob.framerate aj.i matches ..-1 run scoreboard players set @s aj.frame 280
execute if score .aj.cob.framerate aj.i matches 1.. run scoreboard players set @s aj.frame 0
scoreboard players add .noScripts aj.i 0
execute if score .aj.anim_loop aj.cob.animating matches 0 run function cob:animation_loop
scoreboard players set #execute aj.i 1