#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.bluejay.anim.fly
execute if score .aj.anim_loop aj.bluejay.animating matches 0 run function bluejay:animation_loop
scoreboard players set #execute aj.i 1