#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.bluejay.anim.fly
execute if score .aj.bluejay.framerate aj.i matches ..-1 run scoreboard players set @s aj.frame 400
execute if score .aj.bluejay.framerate aj.i matches 1.. run scoreboard players set @s aj.frame 0
scoreboard players add .noScripts aj.i 0
execute if score .aj.anim_loop aj.bluejay.animating matches 0 run function bluejay:animation_loop
scoreboard players set #execute aj.i 1