#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.bee.anim.normal] at @s run function bee:animations/normal/next_frame
scoreboard players operation @s aj.bee.animating = .aj.animation aj.bee.animating