#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#bee:bone_entities,tag=aj.bee.bone] if score @s aj.id = .this aj.id run function bee:zzz/execute/8