#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function cobblestone:animations/loop/tree/bone_display_64-71
execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [0f,0f,0f]