#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^0 ^-1.813 ^0 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^0 ^-1.813 ^0 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^0 ^-1.813 ^0 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^0 ^-1.813 ^0 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^0 ^-1.813 ^0 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^0 ^-1.813 ^0 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^0 ^-1.813 ^0 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^0 ^-1.813 ^0 ~ ~