#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-1.4815f,0f,0f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-3.5185f,0f,0f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-5f,0f,0f]