#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.cobblestone.bone.bone] run function cobblestone:animations/loop/tree/bone_display_top
execute if entity @s[tag=aj.cobblestone.bone.head] run function cobblestone:animations/loop/tree/head_display_top
execute if entity @s[tag=aj.cobblestone.bone.face] run function cobblestone:animations/loop/tree/face_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~