#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0 ^-1.83 ^-0.012 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0 ^-1.825 ^-0.008 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0 ^-1.821 ^0 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0 ^-1.816 ^0.008 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0 ^-1.811 ^0.011 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0 ^-1.806 ^0.007 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^0 ^-1.802 ^0 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^0 ^-1.797 ^-0.007 ~ ~