#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0 ^-1.86 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0 ^-1.858 ^0.004 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0 ^-1.855 ^0.009 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0 ^-1.851 ^0.013 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0 ^-1.847 ^0.014 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0 ^-1.844 ^0.008 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0 ^-1.84 ^-0.001 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0 ^-1.835 ^-0.009 ~ ~