#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^0 ^-1.785 ^0 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^0 ^-1.784 ^0 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^0 ^-1.784 ^0 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^0 ^-1.785 ^0 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^0 ^-1.785 ^0 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^0 ^-1.787 ^0.003 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^0 ^-1.79 ^0.004 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^0 ^-1.793 ^0 ~ ~