#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0 ^-1.785 ^0 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0 ^-1.786 ^0 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0 ^-1.786 ^0 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0 ^-1.787 ^0 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0 ^-1.787 ^0 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0 ^-1.788 ^0 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0 ^-1.788 ^0 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0 ^-1.789 ^0 ~ ~