#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^0 ^-1.829 ^0 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^0 ^-1.834 ^0 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^0 ^-1.838 ^0 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^0 ^-1.843 ^0 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^0 ^-1.847 ^0 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^0 ^-1.851 ^0 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^0 ^-1.855 ^0 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^0 ^-1.858 ^0 ~ ~