#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [0.0005f,0f,0f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [0.0019f,0f,0f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [0.0042f,0f,0f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [0.0074f,0f,0f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [0.0112f,0f,0f]