#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [0.0706f,0f,0f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [0.0787f,0f,0f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [0.087f,0f,0f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [0.0954f,0f,0f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [0.1037f,0f,0f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [0.1119f,0f,0f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [0.12f,0f,0f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [0.1279f,0f,0f]