#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run data modify entity @s Pose.Head set value [0.0846f,0f,0f]
execute if score .this aj.frame matches 137 run data modify entity @s Pose.Head set value [0.0663f,0f,0f]
execute if score .this aj.frame matches 138 run data modify entity @s Pose.Head set value [0.0461f,0f,0f]
execute if score .this aj.frame matches 139 run data modify entity @s Pose.Head set value [0.024f,0f,0f]
execute if score .this aj.frame matches 140 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 141 run data modify entity @s Pose.Head set value [-1.5625f,0f,0f]
execute if score .this aj.frame matches 142 run data modify entity @s Pose.Head set value [-2.5f,0f,0f]
execute if score .this aj.frame matches 143 run data modify entity @s Pose.Head set value [0.1562f,0f,0f]