#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run tp @s ^0 ^-1.796 ^-0.005 ~ ~
execute if score .this aj.frame matches 145 run tp @s ^0 ^-1.8 ^0 ~ ~
execute if score .this aj.frame matches 146 run tp @s ^0 ^-1.804 ^0.005 ~ ~
execute if score .this aj.frame matches 147 run tp @s ^0 ^-1.809 ^0.003 ~ ~
execute if score .this aj.frame matches 148 run tp @s ^0 ^-1.813 ^0 ~ ~
execute if score .this aj.frame matches 149 run tp @s ^0 ^-1.817 ^0 ~ ~
execute if score .this aj.frame matches 150 run tp @s ^0 ^-1.82 ^0 ~ ~
execute if score .this aj.frame matches 151 run tp @s ^0 ^-1.825 ^0 ~ ~