#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run data modify entity @s Pose.Head set value [2.5f,0f,0f]
execute if score .this aj.frame matches 145 run data modify entity @s Pose.Head set value [0.1563f,0f,0f]
execute if score .this aj.frame matches 146 run data modify entity @s Pose.Head set value [-2.5f,0f,0f]
execute if score .this aj.frame matches 147 run data modify entity @s Pose.Head set value [-1.5625f,0f,0f]
execute if score .this aj.frame matches 148 run data modify entity @s Pose.Head set value [0f,0f,0f]