#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-180f,15.84f,180f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-180f,66.195f,180f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [0f,69.12f,0f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [0f,30.915f,0f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-2.0501f,-43.7217f,1.4173f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-9.7881f,-68.8387f,9.1396f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-25.3947f,-78.2741f,24.9297f]