#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [5f,0f,0f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [3.5547f,0f,0f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0.3125f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-3.0859f,0f,0f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-5f,0f,0f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-4.6875f,0f,0f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-3.125f,0f,0f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-1.25f,0f,0f]