#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0 ^-1.502 ^-0.029 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0 ^-1.502 ^-0.03 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0 ^-1.502 ^-0.031 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0 ^-1.502 ^-0.031 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0 ^-1.502 ^-0.03 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0 ^-1.502 ^-0.029 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0 ^-1.502 ^-0.027 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0 ^-1.501 ^-0.014 ~ ~