#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 80 run tp @s ^0 ^-1.504 ^0 ~ ~
execute if score .this aj.frame matches 81 run tp @s ^0 ^-1.505 ^0 ~ ~
execute if score .this aj.frame matches 82 run tp @s ^0 ^-1.505 ^0 ~ ~
execute if score .this aj.frame matches 83 run tp @s ^0 ^-1.506 ^0 ~ ~
execute if score .this aj.frame matches 84 run tp @s ^0 ^-1.506 ^0 ~ ~
execute if score .this aj.frame matches 85 run tp @s ^0 ^-1.507 ^0 ~ ~
execute if score .this aj.frame matches 86 run tp @s ^0 ^-1.507 ^0 ~ ~
execute if score .this aj.frame matches 87 run tp @s ^0 ^-1.508 ^0 ~ ~