#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-23.657f,-76.6755f,23.0877f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [-14.1486f,-66.8692f,13.0518f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [-9.0368f,-51.4918f,7.0943f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [-6.7614f,-33.8348f,3.7768f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [-5.7689f,-17.1977f,1.711f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [-5.3252f,-4.8391f,0.4505f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [-5f,0f,0f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [-2.5f,0f,0f]