#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run tp @s ^0 ^-1.518 ^0.008 ~ ~
execute if score .this aj.frame matches 145 run tp @s ^0 ^-1.524 ^0 ~ ~
execute if score .this aj.frame matches 146 run tp @s ^0 ^-1.534 ^-0.007 ~ ~
execute if score .this aj.frame matches 147 run tp @s ^0 ^-1.547 ^-0.004 ~ ~
execute if score .this aj.frame matches 148 run tp @s ^0 ^-1.563 ^0 ~ ~
execute if score .this aj.frame matches 149 run tp @s ^0 ^-1.578 ^0 ~ ~
execute if score .this aj.frame matches 150 run tp @s ^0 ^-1.597 ^0 ~ ~
execute if score .this aj.frame matches 151 run tp @s ^0 ^-1.618 ^0 ~ ~