#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run data modify entity @s Pose.Head set value [0.1733f,0f,0f]
execute if score .this aj.frame matches 129 run data modify entity @s Pose.Head set value [0.1673f,0f,0f]
execute if score .this aj.frame matches 130 run data modify entity @s Pose.Head set value [0.16f,0f,0f]
execute if score .this aj.frame matches 131 run data modify entity @s Pose.Head set value [0.1513f,0f,0f]
execute if score .this aj.frame matches 132 run data modify entity @s Pose.Head set value [0.1411f,0f,0f]
execute if score .this aj.frame matches 133 run data modify entity @s Pose.Head set value [0.1294f,0f,0f]
execute if score .this aj.frame matches 134 run data modify entity @s Pose.Head set value [0.1162f,0f,0f]
execute if score .this aj.frame matches 135 run data modify entity @s Pose.Head set value [0.1013f,0f,0f]