#Project generated by Animated Java (https://animated-java.dev/)

schedule function cob:animation_loop 1t
scoreboard players set .aj.anim_loop aj.cob.animating 1
scoreboard players set .aj.animation aj.cob.animating 0
execute as @e[type=minecraft:marker,tag=aj.cob.root] run function cob:zzz/execute/11
execute if score .aj.animation aj.cob.animating matches 0 run function cob:zzz/execute/12