#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#amirkaka:bone_entities,tag=aj.amirkaka.bone] if score @s aj.id = .this aj.id run function amirkaka:zzz/execute/11