#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.amirkaka.bone.leftarm] Pose.Head set value [0f,0f,22.5f]
data modify entity @s[tag=aj.amirkaka.bone.rightarm] Pose.Head set value [0f,0f,-22.5f]
data modify entity @s[tag=aj.amirkaka.bone.leftleg] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.amirkaka.bone.rightleg] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.amirkaka.bone.head] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.amirkaka.bone.body] Pose.Head set value [0f,0f,0f]
tp @s ~ ~ ~ ~ ~