#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.glare.idle.loopMode matches 0 run function glare:animations/idle/stop
execute if score @s aj.glare.idle.loopMode matches 1 run function glare:animations/idle/pause
execute if score @s aj.glare.idle.loopMode matches 2 run function glare:animations/idle/zzz/execute/13