#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#glare:bone_entities,tag=aj.glare.bone,distance=..2.059] if score @s aj.id = .this aj.id run function glare:animations/idle/tree/trunk
scoreboard players operation @s aj.frame += .aj.glare.framerate aj.i
scoreboard players set .aj.animation aj.glare.animating 1
execute unless score @s aj.frame matches 0..40 run function glare:animations/idle/edge