#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.glare.root] at @s run function glare:animations/idle/zzz/conditional/10
execute if score #execute aj.i matches 0 run function glare:animations/idle/zzz/conditional/11