#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.glare.root] run function glare:animations/idle/zzz/conditional/12
execute if score #execute aj.i matches 0 run function glare:animations/idle/zzz/conditional/13