#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.bee.normal.loopMode matches 0 run function bee:animations/normal/stop
execute if score @s aj.bee.normal.loopMode matches 1 run function bee:animations/normal/pause
execute if score @s aj.bee.normal.loopMode matches 2 run function bee:animations/normal/zzz/execute/13