#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#bee:bone_entities,tag=aj.bee.bone,distance=..2.431] if score @s aj.id = .this aj.id run function bee:animations/normal/tree/trunk
scoreboard players operation @s aj.frame += .aj.bee.framerate aj.i
scoreboard players set .aj.animation aj.bee.animating 1
execute unless score @s aj.frame matches 0..20 run function bee:animations/normal/edge