#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.amirkaka.anim.idle4
execute if score .aj.anim_loop aj.amirkaka.animating matches 0 run function amirkaka:animation_loop
scoreboard players set #execute aj.i 1