#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.cobblestone.bone.head] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.cobblestone.bone.face] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.cobblestone.bone.bone] Pose.Head set value [0f,0f,0f]
tp @s ~ ~ ~ ~ ~