#Project generated by Animated Java (https://animated-java.dev/)

schedule function glare:animation_loop 1t
scoreboard players set .aj.anim_loop aj.glare.animating 1
scoreboard players set .aj.animation aj.glare.animating 0
execute as @e[type=minecraft:marker,tag=aj.glare.root] run function glare:zzz/execute/11
execute if score .aj.animation aj.glare.animating matches 0 run function glare:zzz/execute/12