#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if score @s aj.frame matches ..1 run function amirkaka:animations/idle4/zzz/conditional/44
execute if score #execute aj.i matches 0 run function amirkaka:animations/idle4/zzz/conditional/45