#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.cobblestone.loop.loopMode matches 0 run function cobblestone:animations/loop/stop
execute if score @s aj.cobblestone.loop.loopMode matches 1 run function cobblestone:animations/loop/pause
execute if score @s aj.cobblestone.loop.loopMode matches 2 run function cobblestone:animations/loop/zzz/execute/13