#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#cobblestone:bone_entities,tag=aj.cobblestone.bone,distance=..1.4360000000000002] if score @s aj.id = .this aj.id run function cobblestone:animations/loop/tree/trunk
scoreboard players operation @s aj.frame += .aj.cobblestone.framerate aj.i
scoreboard players set .aj.animation aj.cobblestone.animating 1
execute unless score @s aj.frame matches 0..200 run function cobblestone:animations/loop/edge