#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-10.0757f,-5.0422f,1.5042f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-11.6318f,-5.8553f,1.7498f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-13.1183f,-6.673f,2.0002f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-14.4948f,-7.4846f,2.2532f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-15.7205f,-8.2793f,2.5062f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-16.7549f,-9.0463f,2.757f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-17.5574f,-9.7749f,3.0031f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-18.0873f,-10.4543f,3.2422f]