#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-18.3041f,-11.0736f,3.4719f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-18.167f,-11.6221f,3.6898f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-17.4331f,-12.204f,3.9469f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-15.4246f,-12.9485f,4.323f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-12.4022f,-13.6951f,4.7445f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-8.6094f,-14.4166f,5.1903f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-4.2897f,-15.0859f,5.639f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [0.3134f,-15.6758f,6.0696f]