#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [18.0175f,-12.5458f,5.64f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [15.9448f,-10.8729f,4.9025f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [13.4866f,-9.0739f,4.0992f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [10.8102f,-7.2268f,3.2678f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [8.0824f,-5.4097f,2.4457f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [5.4704f,-3.7004f,1.6704f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [3.1413f,-2.1771f,0.9794f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [1.2622f,-0.9176f,0.4101f]