#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-0.6497f,-0.3875f,0.1211f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-1.5549f,-0.8659f,0.266f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-2.6749f,-1.4245f,0.4325f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-3.9691f,-2.0524f,0.6181f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-5.3969f,-2.739f,0.8205f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-6.9177f,-3.4733f,1.0372f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-8.4908f,-4.2446f,1.2659f]