#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,-22.5f]
execute if score .this aj.frame matches 8..15 run function amirkaka:animations/idle1/tree/rightarm_display_8-15
execute if score .this aj.frame matches 16..23 run function amirkaka:animations/idle1/tree/rightarm_display_16-23
execute if score .this aj.frame matches 24..31 run function amirkaka:animations/idle1/tree/rightarm_display_24-31
execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [0f,0f,-22.5f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [0f,0f,-22.5f]