#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-2.5822f,0f,-19.9178f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-3.1522f,0f,-19.3478f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-3.6892f,0f,-18.8108f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-4.1671f,0f,-18.3329f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-4.56f,0f,-17.94f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-4.8418f,0f,-17.6582f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-4.9864f,0f,-17.5136f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-4.9443f,0f,-17.5557f]