#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^-0.17 ^-0.624 ^0.51 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.198 ^-0.614 ^0.594 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.227 ^-0.603 ^0.68 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.256 ^-0.592 ^0.767 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.285 ^-0.581 ^0.854 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^-0.313 ^-0.571 ^0.939 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^-0.341 ^-0.56 ^1.023 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^-0.368 ^-0.55 ^1.103 ~ ~