#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.059 ^-0.652 ^-0.073 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.054 ^-0.655 ^-0.067 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0.033 ^-0.667 ^-0.041 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0.011 ^-0.681 ^-0.013 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0 ^-0.688 ^0 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0 ^-0.688 ^0 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0 ^-0.688 ^0 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^0 ^-0.688 ^0 ~ ~