#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-136.4367f,-38.8197f,69.8862f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-138.0507f,-39.3766f,70.1758f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-139.0801f,-39.7869f,70.058f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-139.5919f,-40.0617f,69.6103f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-139.6535f,-40.2124f,68.9099f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-139.3319f,-40.2503f,68.0343f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-138.6944f,-40.1866f,67.0609f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-137.8082f,-40.0327f,66.0669f]