#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-136.7404f,-39.7999f,65.1298f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-135.5582f,-39.4995f,64.3269f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [-134.3289f,-39.1427f,63.7357f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-133.1196f,-38.7409f,63.4335f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-131.9975f,-38.3054f,63.4976f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-131.0298f,-37.8474f,64.0055f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [-130.2836f,-37.3783f,65.0345f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [-129.8263f,-36.9094f,66.6619f]