#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-44.1419f,-12.5229f,22.8119f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-51.4445f,-14.5946f,26.5858f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-58.8862f,-16.7057f,30.4315f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-66.3896f,-18.8344f,34.3092f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-73.8776f,-20.9587f,38.1789f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-81.2729f,-23.0567f,42.0007f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-88.4982f,-25.1065f,45.7346f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-95.4762f,-27.0861f,49.3408f]