#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-129.716f,-35.9244f,70.0346f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-130.0669f,-33.8791f,75.4086f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-130.7476f,-31.0569f,82.2466f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-131.6055f,-27.7324f,90.137f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-132.4877f,-24.1803f,98.6684f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-133.2417f,-20.6753f,107.4291f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-133.7147f,-17.4922f,116.0076f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-133.754f,-14.9056f,123.9924f]