#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.502 ^-0.442 ^1.61 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.497 ^-0.442 ^1.597 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.492 ^-0.444 ^1.582 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.489 ^-0.449 ^1.567 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.488 ^-0.456 ^1.55 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.488 ^-0.466 ^1.534 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.492 ^-0.48 ^1.518 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.498 ^-0.497 ^1.503 ~ ~