#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-102.1298f,-28.9737f,52.7792f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-108.3815f,-30.7473f,56.01f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-114.1542f,-32.385f,58.9933f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-119.3707f,-33.8649f,61.6891f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-123.9535f,-35.165f,64.0574f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-127.8255f,-36.2635f,66.0584f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-131.1857f,-37.2203f,67.7754f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-134.1707f,-38.1046f,69.1118f]