#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^0.712 ^0.161 ^0.993 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^0.677 ^0.127 ^0.957 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^0.638 ^0.096 ^0.914 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^0.597 ^0.067 ^0.864 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^0.555 ^0.04 ^0.808 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^0.51 ^0.015 ^0.748 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^0.465 ^-0.008 ^0.684 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.419 ^-0.03 ^0.617 ~ ~