#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.978 ^0.674 ^1.034 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.948 ^0.595 ^1.048 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.917 ^0.518 ^1.059 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.884 ^0.443 ^1.064 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.851 ^0.373 ^1.064 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.817 ^0.308 ^1.058 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.781 ^0.25 ^1.043 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.745 ^0.2 ^1.021 ~ ~