#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [-1.4796f,-1.0123f,0.1974f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [0f,0f,0f]