#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0.048 ^-0.16 ^0.043 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0.02 ^-0.171 ^0 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-0.004 ^-0.181 ^-0.035 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~