#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-108.039f,-12.4371f,33.9764f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-137.7918f,-5.8972f,56.8876f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-161.0453f,0.1395f,74.1845f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-174.0011f,4.9916f,82.4266f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-175.516f,6.9703f,81.9987f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-174.2838f,8.5208f,79.3357f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-171.2011f,10.0936f,74.8881f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-166.4868f,11.6681f,68.8921f]