#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^1.139 ^1.209 ^0.862 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^1.183 ^1.263 ^0.897 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^1.219 ^1.307 ^0.923 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^1.245 ^1.343 ^0.941 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^1.264 ^1.371 ^0.951 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^1.276 ^1.391 ^0.955 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^1.281 ^1.404 ^0.954 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^1.281 ^1.41 ^0.949 ~ ~