#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run tp @s ^0.465 ^0.393 ^0.329 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.562 ^0.511 ^0.406 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.66 ^0.629 ^0.483 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.755 ^0.745 ^0.559 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.848 ^0.856 ^0.632 ~ ~
execute if score .this aj.frame matches 13 run tp @s ^0.934 ^0.961 ^0.7 ~ ~
execute if score .this aj.frame matches 14 run tp @s ^1.013 ^1.056 ^0.762 ~ ~
execute if score .this aj.frame matches 15 run tp @s ^1.082 ^1.14 ^0.817 ~ ~