#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.012 ^-0.185 ^-0.047 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.005 ^-0.164 ^-0.034 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.057 ^-0.101 ^0.007 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.121 ^-0.023 ^0.058 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.196 ^0.068 ^0.117 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.28 ^0.169 ^0.184 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.37 ^0.278 ^0.255 ~ ~