#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [-42.7607f,18.2338f,-46.7207f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [-40.7382f,16.1303f,-45.3629f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [-39.1118f,13.7545f,-43.2867f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [-37.8297f,11.161f,-40.5983f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [-36.8399f,8.4045f,-37.404f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [-36.0905f,5.5394f,-33.8101f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [-35.5295f,2.6205f,-29.9227f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [-35.105f,-0.2977f,-25.8483f]