#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^1.094 ^0.513 ^-0.448 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^1.095 ^0.528 ^-0.46 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^1.097 ^0.542 ^-0.471 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^1.099 ^0.555 ^-0.481 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^1.102 ^0.566 ^-0.489 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^1.105 ^0.576 ^-0.496 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^1.109 ^0.585 ^-0.502 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^1.113 ^0.593 ^-0.507 ~ ~