#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [0.6704f,46.6154f,-125.883f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [-24.7594f,48.5108f,-126.5907f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [-52.031f,49.8041f,-126.1835f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [-75.9147f,50.3431f,-124.387f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [-91.1809f,49.9753f,-120.9266f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [-92.8185f,48.4951f,-115.3723f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [-86.2229f,45.1112f,-105.9112f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [-76.4587f,40.0411f,-93.1366f]