#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-44.8453f,16.0368f,-96.4918f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [33.1227f,17.8526f,-98.6102f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [110.3124f,19.6692f,-100.7098f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [-174.029f,21.4726f,-102.7704f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [-100.6541f,23.2484f,-104.772f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [-30.3157f,24.9827f,-106.6946f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [36.2336f,26.6613f,-108.518f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [98.241f,28.2702f,-110.2224f]