#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.912 ^0.288 ^-0.332 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.834 ^0.197 ^-0.287 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.752 ^0.101 ^-0.239 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.669 ^0.004 ^-0.19 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.587 ^-0.092 ^-0.142 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.51 ^-0.181 ^-0.098 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.442 ^-0.26 ^-0.058 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.386 ^-0.327 ^-0.025 ~ ~