#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64..71 run function amirkaka:animations/idle4/tree/leftarm_display_64-71
execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [0f,0f,22.5f]