#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [95.4466f,45.9693f,93.2458f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [85.2389f,43.4767f,83.3203f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [75.9578f,40.9675f,73.9405f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [67.7701f,38.4831f,65.2053f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [60.8424f,36.0647f,57.2132f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [55.1868f,33.6668f,49.8361f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [50.5551f,30.6365f,42.1836f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [47.4939f,27.1104f,34.9846f]