#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^-0.138 ^-0.547 ^0 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^-0.139 ^-0.544 ^0 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^-0.14 ^-0.541 ^0 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^-0.141 ^-0.538 ^0 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^-0.142 ^-0.535 ^0 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^-0.143 ^-0.532 ^0 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^-0.143 ^-0.53 ^0 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^-0.143 ^-0.529 ^0 ~ ~