#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.128 ^-0.568 ^0 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.129 ^-0.566 ^0 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.13 ^-0.565 ^0 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.131 ^-0.563 ^0 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-0.132 ^-0.56 ^0 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-0.134 ^-0.557 ^0 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-0.135 ^-0.554 ^0 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-0.137 ^-0.551 ^0 ~ ~