#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run data modify entity @s Pose.Head set value [45.7988f,23.1812f,28.2403f]
execute if score .this aj.frame matches 49 run data modify entity @s Pose.Head set value [45.2654f,18.9421f,21.9522f]
execute if score .this aj.frame matches 50 run data modify entity @s Pose.Head set value [45.6895f,14.4859f,16.1214f]
execute if score .this aj.frame matches 51 run data modify entity @s Pose.Head set value [46.8667f,9.9057f,10.7493f]
execute if score .this aj.frame matches 52 run data modify entity @s Pose.Head set value [48.5925f,5.2944f,5.8371f]
execute if score .this aj.frame matches 53 run data modify entity @s Pose.Head set value [50.6627f,0.7451f,1.3861f]
execute if score .this aj.frame matches 54 run data modify entity @s Pose.Head set value [52.8729f,-3.6494f,-2.6025f]
execute if score .this aj.frame matches 55 run data modify entity @s Pose.Head set value [55.0187f,-7.796f,-6.1272f]