#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-64.4642f,33.7814f,-78.0814f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-51.1775f,26.8291f,-61.779f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-37.5369f,19.6806f,-45.2625f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-24.4804f,12.8328f,-29.5652f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-12.9463f,6.7824f,-15.7202f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-3.8728f,2.026f,-4.7608f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [0f,0f,0f]