#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-169.543f,60.3659f,-179.5378f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [178.8392f,59.4903f,169.7214f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [166.814f,58.2682f,158.7373f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [154.5483f,56.7409f,147.6084f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [142.2087f,54.9496f,136.4334f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [129.962f,52.9355f,125.311f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [117.9749f,50.74f,114.3399f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [106.4142f,48.4041f,103.6186f]