#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^1.146 ^0.614 ^-0.511 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^1.148 ^0.61 ^-0.508 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^1.149 ^0.606 ^-0.504 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^1.149 ^0.601 ^-0.5 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^1.149 ^0.595 ^-0.495 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^1.147 ^0.588 ^-0.49 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^1.145 ^0.579 ^-0.484 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^1.141 ^0.57 ^-0.478 ~ ~