#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-0.131 ^-0.55 ^0 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-0.127 ^-0.558 ^0 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-0.12 ^-0.573 ^0 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-0.106 ^-0.606 ^0 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-0.087 ^-0.648 ^0 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-0.065 ^-0.698 ^0 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-0.041 ^-0.752 ^0 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-0.016 ^-0.809 ^0 ~ ~