#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^0.01 ^-0.868 ^0 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^0.036 ^-0.925 ^0 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^0.061 ^-0.98 ^0 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^0.083 ^-1.031 ^0 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^0.102 ^-1.074 ^0 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^0.118 ^-1.109 ^0 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^0.125 ^-1.125 ^0 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^0.125 ^-1.125 ^0 ~ ~