#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.141 ^-0.356 ^0 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.142 ^-0.407 ^0 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.133 ^-0.491 ^0 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.125 ^-0.557 ^0 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.125 ^-0.565 ^0 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.125 ^-0.567 ^0 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.126 ^-0.568 ^0 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.127 ^-0.568 ^0 ~ ~