#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.344 ^-0.375 ^0 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.407 ^-0.393 ^0.037 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.522 ^-0.434 ^0.112 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.66 ^-0.482 ^0.202 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.806 ^-0.524 ^0.289 ~ ~