#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [113.7123f,3.2339f,-81.2693f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [170.8103f,4.5349f,-82.8173f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-126.8485f,5.9496f,-84.5068f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-60.0168f,7.464f,-86.3176f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [10.5527f,9.064f,-88.2299f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [84.1073f,10.7354f,-90.2235f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [159.8943f,12.464f,-92.2784f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-122.839f,14.2359f,-94.3745f]