#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [0f,0f,22.5f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-1.316f,-0.5199f,21.4525f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-10.3637f,-5.4376f,14.9706f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-22.5139f,-12.5925f,6.5613f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-36.3878f,-19.7668f,-3.5746f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-50.607f,-24.7429f,-15.2364f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-63.7929f,-25.3029f,-28.2233f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-71.2372f,-22.0848f,-37.4421f]