#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^1.136 ^0.56 ^-0.472 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^1.13 ^0.549 ^-0.465 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^1.123 ^0.537 ^-0.458 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^1.114 ^0.525 ^-0.451 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^1.103 ^0.511 ^-0.444 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^1.087 ^0.491 ^-0.434 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^1.042 ^0.439 ^-0.407 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^0.982 ^0.37 ^-0.373 ~ ~