#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^1.117 ^0.6 ^-0.511 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^1.121 ^0.606 ^-0.514 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^1.125 ^0.61 ^-0.516 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^1.13 ^0.613 ^-0.517 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^1.134 ^0.616 ^-0.518 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^1.137 ^0.617 ^-0.517 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^1.141 ^0.617 ^-0.516 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^1.144 ^0.616 ^-0.514 ~ ~