#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.838 ^-0.622 ^0.143 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.893 ^-0.644 ^0.161 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.944 ^-0.662 ^0.18 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.992 ^-0.677 ^0.199 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-1.036 ^-0.686 ^0.219 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-1.074 ^-0.689 ^0.238 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-1.105 ^-0.686 ^0.258 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-1.132 ^-0.677 ^0.281 ~ ~