#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-1.696 ^-0.82 ^-1.326 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-1.687 ^-0.958 ^-1.455 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-1.659 ^-1.063 ^-1.539 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-1.607 ^-1.121 ^-1.566 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-1.562 ^-1.128 ^-1.547 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-1.512 ^-1.12 ^-1.509 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-1.452 ^-1.1 ^-1.452 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-1.384 ^-1.07 ^-1.379 ~ ~