#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,-22.5f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [0f,0f,-22.5f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-0.4195f,-0.3038f,-22.1857f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-1.9742f,-1.118f,-21.0237f]