#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 48 run tp @s ^-1.56 ^-0.016 ^-0.141 ~ ~
execute if score .this aj.frame matches 49 run tp @s ^-1.576 ^-0.026 ^-0.242 ~ ~
execute if score .this aj.frame matches 50 run tp @s ^-1.589 ^-0.05 ^-0.338 ~ ~
execute if score .this aj.frame matches 51 run tp @s ^-1.604 ^-0.102 ^-0.457 ~ ~
execute if score .this aj.frame matches 52 run tp @s ^-1.626 ^-0.205 ^-0.617 ~ ~
execute if score .this aj.frame matches 53 run tp @s ^-1.651 ^-0.341 ^-0.797 ~ ~
execute if score .this aj.frame matches 54 run tp @s ^-1.673 ^-0.498 ^-0.984 ~ ~
execute if score .this aj.frame matches 55 run tp @s ^-1.69 ^-0.662 ^-1.164 ~ ~