#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run data modify entity @s Pose.Head set value [-159.4428f,74.7336f,-131.8735f]
execute if score .this aj.frame matches 33 run data modify entity @s Pose.Head set value [-173.9928f,74.8432f,-137.111f]
execute if score .this aj.frame matches 34 run data modify entity @s Pose.Head set value [172.217f,74.9101f,-141.8561f]
execute if score .this aj.frame matches 35 run data modify entity @s Pose.Head set value [159.4534f,74.9666f,-146.2163f]
execute if score .this aj.frame matches 36 run data modify entity @s Pose.Head set value [147.9835f,75.0453f,-150.2991f]
execute if score .this aj.frame matches 37 run data modify entity @s Pose.Head set value [138.0741f,75.1785f,-154.2122f]
execute if score .this aj.frame matches 38 run data modify entity @s Pose.Head set value [129.9921f,75.3988f,-158.0632f]
execute if score .this aj.frame matches 39 run data modify entity @s Pose.Head set value [119.1756f,76.0569f,-164.6607f]