#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^0.572 ^-0.574 ^-0.688 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^0.536 ^-0.624 ^-0.662 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^0.492 ^-0.676 ^-0.633 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^0.441 ^-0.73 ^-0.602 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^0.386 ^-0.785 ^-0.569 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^0.326 ^-0.841 ^-0.534 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^0.264 ^-0.896 ^-0.499 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^0.2 ^-0.951 ^-0.463 ~ ~