#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [-8.9185f,45.0534f,90.9801f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [-11.1954f,48.9275f,67.3707f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [-13.9769f,52.6024f,44.7793f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [-17.3188f,56.0273f,23.4884f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [-21.2771f,59.1514f,3.7805f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [-25.9075f,61.9239f,-14.0619f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [-31.2659f,64.294f,-29.7564f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [-38.3512f,66.4655f,-44.8221f]