#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run data modify entity @s Pose.Head set value [-119.4033f,43.7872f,-98.108f]
execute if score .this aj.frame matches 57 run data modify entity @s Pose.Head set value [-112.3114f,41.8005f,-94.2572f]
execute if score .this aj.frame matches 58 run data modify entity @s Pose.Head set value [-106.3581f,40.1449f,-91.0641f]
execute if score .this aj.frame matches 59 run data modify entity @s Pose.Head set value [-103.0318f,39.3314f,-89.6388f]
execute if score .this aj.frame matches 60 run data modify entity @s Pose.Head set value [-103.3643f,39.6195f,-90.4471f]
execute if score .this aj.frame matches 61 run data modify entity @s Pose.Head set value [-105.9924f,40.567f,-92.5539f]
execute if score .this aj.frame matches 62 run data modify entity @s Pose.Head set value [-109.5528f,41.7312f,-95.024f]
execute if score .this aj.frame matches 63 run data modify entity @s Pose.Head set value [-112.6822f,42.6697f,-96.9221f]