#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run data modify entity @s Pose.Head set value [-7.9259f,2.9719f,-6.7227f]
execute if score .this aj.frame matches 73 run data modify entity @s Pose.Head set value [0f,0f,0f]