#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run data modify entity @s Pose.Head set value [97.765f,-75.6284f,-94.5419f]
execute if score .this aj.frame matches 41 run data modify entity @s Pose.Head set value [102.4896f,-77.3963f,-98.0388f]
execute if score .this aj.frame matches 42 run data modify entity @s Pose.Head set value [107.2195f,-79.2745f,-101.485f]
execute if score .this aj.frame matches 43 run data modify entity @s Pose.Head set value [111.8101f,-81.347f,-104.342f]
execute if score .this aj.frame matches 44 run data modify entity @s Pose.Head set value [114.5604f,-82.8911f,-105.4196f]
execute if score .this aj.frame matches 45 run data modify entity @s Pose.Head set value [115.7576f,-83.9239f,-105.1325f]
execute if score .this aj.frame matches 46 run data modify entity @s Pose.Head set value [115.6893f,-84.4629f,-103.8955f]
execute if score .this aj.frame matches 47 run data modify entity @s Pose.Head set value [114.643f,-84.5253f,-102.1234f]