#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-2.1651f,12.9833f,-77.3975f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-2.4163f,16.6227f,-98.9808f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-2.7252f,20.4692f,-121.8061f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [-3.1477f,24.4721f,-145.5908f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-3.7396f,28.5804f,-170.0526f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [-4.5567f,32.7435f,165.0911f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [-5.655f,36.9106f,140.1228f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [-7.0904f,41.0308f,115.3249f]