#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^-1.309 ^-1.031 ^-1.293 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^-1.229 ^-0.985 ^-1.195 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^-1.144 ^-0.933 ^-1.088 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^-1.057 ^-0.877 ^-0.974 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^-0.969 ^-0.817 ^-0.856 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^-0.88 ^-0.755 ^-0.736 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^-0.793 ^-0.694 ^-0.616 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.709 ^-0.633 ^-0.5 ~ ~