#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [-47.7263f,68.4209f,-59.3333f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [-58.7441f,70.0414f,-72.3838f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [-71.1378f,71.3594f,-84.0811f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [-84.6403f,72.4075f,-94.5329f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [-98.9847f,73.2179f,-103.8466f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [-113.9041f,73.8233f,-112.13f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [-129.1316f,74.2561f,-119.4905f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [-144.4001f,74.5487f,-126.0358f]