#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.573 ^0.951 ^-0.302 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.534 ^0.745 ^-0.398 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^-0.486 ^0.532 ^-0.492 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^-0.43 ^0.331 ^-0.576 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^-0.367 ^0.161 ^-0.646 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^-0.304 ^0.051 ^-0.692 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^-0.258 ^0.001 ^-0.714 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.201 ^-0.042 ^-0.733 ~ ~