#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 56 run tp @s ^-0.25 ^-1.313 ^-0.188 ~ ~
execute if score .this aj.frame matches 57 run tp @s ^-0.281 ^-1.339 ^-0.145 ~ ~
execute if score .this aj.frame matches 58 run tp @s ^-0.286 ^-1.336 ^-0.11 ~ ~
execute if score .this aj.frame matches 59 run tp @s ^-0.271 ^-1.312 ^-0.082 ~ ~
execute if score .this aj.frame matches 60 run tp @s ^-0.242 ^-1.274 ^-0.059 ~ ~
execute if score .this aj.frame matches 61 run tp @s ^-0.207 ^-1.229 ^-0.04 ~ ~
execute if score .this aj.frame matches 62 run tp @s ^-0.171 ^-1.184 ^-0.025 ~ ~
execute if score .this aj.frame matches 63 run tp @s ^-0.141 ^-1.147 ^-0.012 ~ ~