#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-1.156 ^-0.663 ^0.309 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-1.177 ^-0.644 ^0.34 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-1.195 ^-0.621 ^0.374 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-1.211 ^-0.594 ^0.409 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^-1.225 ^-0.565 ^0.445 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^-1.238 ^-0.533 ^0.481 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^-1.25 ^-0.5 ^0.515 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^-1.261 ^-0.467 ^0.548 ~ ~