#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 40 run tp @s ^-1.379 ^-0.203 ^0.562 ~ ~
execute if score .this aj.frame matches 41 run tp @s ^-1.403 ^-0.17 ^0.503 ~ ~
execute if score .this aj.frame matches 42 run tp @s ^-1.427 ^-0.136 ^0.432 ~ ~
execute if score .this aj.frame matches 43 run tp @s ^-1.451 ^-0.104 ^0.35 ~ ~
execute if score .this aj.frame matches 44 run tp @s ^-1.475 ^-0.074 ^0.26 ~ ~
execute if score .this aj.frame matches 45 run tp @s ^-1.498 ^-0.048 ^0.164 ~ ~
execute if score .this aj.frame matches 46 run tp @s ^-1.52 ^-0.029 ^0.064 ~ ~
execute if score .this aj.frame matches 47 run tp @s ^-1.541 ^-0.018 ^-0.039 ~ ~