#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run data modify entity @s Pose.Head set value [70.4932f,-26.8861f,-147.6932f]
execute if score .this aj.frame matches 65 run data modify entity @s Pose.Head set value [64.9482f,-24.0414f,-139.9187f]
execute if score .this aj.frame matches 66 run data modify entity @s Pose.Head set value [58.8321f,-21.2424f,-130.3817f]
execute if score .this aj.frame matches 67 run data modify entity @s Pose.Head set value [52.2983f,-18.5083f,-119.4659f]
execute if score .this aj.frame matches 68 run data modify entity @s Pose.Head set value [45.5002f,-15.8583f,-107.5551f]
execute if score .this aj.frame matches 69 run data modify entity @s Pose.Head set value [38.591f,-13.3117f,-95.0331f]
execute if score .this aj.frame matches 70 run data modify entity @s Pose.Head set value [31.7242f,-10.8878f,-82.2836f]
execute if score .this aj.frame matches 71 run data modify entity @s Pose.Head set value [25.053f,-8.6059f,-69.6904f]