#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run data modify entity @s Pose.Head set value [0f,64.0233f,0f]
execute if score .this aj.frame matches 97 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 98 run data modify entity @s Pose.Head set value [0f,-64.0233f,0f]
execute if score .this aj.frame matches 99 run data modify entity @s Pose.Head set value [-180f,-53.5277f,180f]
execute if score .this aj.frame matches 100 run data modify entity @s Pose.Head set value [-180f,5.7726f,180f]
execute if score .this aj.frame matches 101 run data modify entity @s Pose.Head set value [-180f,60.3499f,180f]
execute if score .this aj.frame matches 102 run data modify entity @s Pose.Head set value [0f,71.3703f,0f]
execute if score .this aj.frame matches 103 run data modify entity @s Pose.Head set value [0f,30.9621f,0f]