#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 64 run tp @s ^0 ^-1.504 ^0.083 ~ ~
execute if score .this aj.frame matches 65 run tp @s ^0 ^-1.506 ^0.083 ~ ~
execute if score .this aj.frame matches 66 run tp @s ^0 ^-1.507 ^0.083 ~ ~
execute if score .this aj.frame matches 67 run tp @s ^0 ^-1.508 ^0.083 ~ ~
execute if score .this aj.frame matches 68 run tp @s ^0 ^-1.509 ^0.083 ~ ~
execute if score .this aj.frame matches 69 run tp @s ^0 ^-1.509 ^0.083 ~ ~
execute if score .this aj.frame matches 70 run tp @s ^0 ^-1.509 ^0.083 ~ ~
execute if score .this aj.frame matches 71 run tp @s ^-0.001 ^-1.509 ^0.083 ~ ~