#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [0f,0f,-5f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [0f,0f,-3.4375f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [0f,0f,3.4375f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [0f,0f,5f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [0f,0f,3.5547f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [0f,0f,0.3125f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [0f,0f,-3.0859f]