#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^0 ^-1.479 ^0.083 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^0 ^-1.479 ^0.083 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^0 ^-1.479 ^0.083 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^0.001 ^-1.479 ^0.083 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^0.001 ^-1.48 ^0.083 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^0.001 ^-1.481 ^0.083 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^0.001 ^-1.483 ^0.083 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^0.001 ^-1.485 ^0.083 ~ ~