#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 152 run tp @s ^0.002 ^-1.514 ^0.083 ~ ~
execute if score .this aj.frame matches 153 run tp @s ^0.002 ^-1.513 ^0.083 ~ ~
execute if score .this aj.frame matches 154 run tp @s ^0.002 ^-1.512 ^0.083 ~ ~
execute if score .this aj.frame matches 155 run tp @s ^0.002 ^-1.511 ^0.083 ~ ~
execute if score .this aj.frame matches 156 run tp @s ^0.002 ^-1.51 ^0.083 ~ ~
execute if score .this aj.frame matches 157 run tp @s ^0.002 ^-1.508 ^0.083 ~ ~
execute if score .this aj.frame matches 158 run tp @s ^0.002 ^-1.507 ^0.083 ~ ~
execute if score .this aj.frame matches 159 run tp @s ^0.002 ^-1.505 ^0.083 ~ ~