#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run tp @s ^0 ^-1.493 ^0.083 ~ ~
execute if score .this aj.frame matches 121 run tp @s ^0 ^-1.491 ^0.083 ~ ~
execute if score .this aj.frame matches 122 run tp @s ^0 ^-1.489 ^0.083 ~ ~
execute if score .this aj.frame matches 123 run tp @s ^0 ^-1.487 ^0.083 ~ ~
execute if score .this aj.frame matches 124 run tp @s ^0 ^-1.485 ^0.083 ~ ~
execute if score .this aj.frame matches 125 run tp @s ^0 ^-1.483 ^0.083 ~ ~
execute if score .this aj.frame matches 126 run tp @s ^0 ^-1.482 ^0.083 ~ ~
execute if score .this aj.frame matches 127 run tp @s ^0 ^-1.48 ^0.083 ~ ~