#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run tp @s ^0.001 ^-1.49 ^0.083 ~ ~
execute if score .this aj.frame matches 169 run tp @s ^0 ^-1.489 ^0.083 ~ ~
execute if score .this aj.frame matches 170 run tp @s ^0 ^-1.489 ^0.083 ~ ~
execute if score .this aj.frame matches 171 run tp @s ^-0.01 ^-1.489 ^0.083 ~ ~
execute if score .this aj.frame matches 172 run tp @s ^-0.024 ^-1.49 ^0.083 ~ ~
execute if score .this aj.frame matches 173 run tp @s ^-0.028 ^-1.491 ^0.083 ~ ~
execute if score .this aj.frame matches 174 run tp @s ^-0.011 ^-1.49 ^0.083 ~ ~
execute if score .this aj.frame matches 175 run tp @s ^0.014 ^-1.495 ^0.083 ~ ~