#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.001 ^-1.486 ^0.083 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.001 ^-1.485 ^0.083 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.002 ^-1.485 ^0.083 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.002 ^-1.484 ^0.083 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.002 ^-1.484 ^0.083 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.002 ^-1.483 ^0.083 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.002 ^-1.483 ^0.083 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.002 ^-1.482 ^0.083 ~ ~