#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 136 run tp @s ^0.001 ^-1.487 ^0.083 ~ ~
execute if score .this aj.frame matches 137 run tp @s ^0.001 ^-1.489 ^0.083 ~ ~
execute if score .this aj.frame matches 138 run tp @s ^0.001 ^-1.491 ^0.083 ~ ~
execute if score .this aj.frame matches 139 run tp @s ^0.001 ^-1.494 ^0.083 ~ ~
execute if score .this aj.frame matches 140 run tp @s ^0.001 ^-1.496 ^0.083 ~ ~
execute if score .this aj.frame matches 141 run tp @s ^0.001 ^-1.499 ^0.083 ~ ~
execute if score .this aj.frame matches 142 run tp @s ^0.002 ^-1.501 ^0.083 ~ ~
execute if score .this aj.frame matches 143 run tp @s ^0.002 ^-1.504 ^0.083 ~ ~