#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0 ^-1.501 ^0.083 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.035 ^-1.504 ^0.078 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.062 ^-1.508 ^0.069 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.08 ^-1.512 ^0.059 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.087 ^-1.514 ^0.053 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.09 ^-1.515 ^0.05 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.089 ^-1.515 ^0.05 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.085 ^-1.514 ^0.054 ~ ~