#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 72 run tp @s ^-0.005 ^-1.508 ^0.083 ~ ~
execute if score .this aj.frame matches 73 run tp @s ^-0.01 ^-1.507 ^0.083 ~ ~
execute if score .this aj.frame matches 74 run tp @s ^-0.017 ^-1.506 ^0.082 ~ ~
execute if score .this aj.frame matches 75 run tp @s ^-0.024 ^-1.504 ^0.08 ~ ~
execute if score .this aj.frame matches 76 run tp @s ^-0.032 ^-1.502 ^0.077 ~ ~
execute if score .this aj.frame matches 77 run tp @s ^-0.04 ^-1.5 ^0.073 ~ ~
execute if score .this aj.frame matches 78 run tp @s ^-0.047 ^-1.497 ^0.069 ~ ~
execute if score .this aj.frame matches 79 run tp @s ^-0.054 ^-1.495 ^0.064 ~ ~