#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^-0.075 ^-1.483 ^0.037 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0 ^-1.485 ^0.083 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0.075 ^-1.487 ^0.037 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0.067 ^-1.49 ^-0.05 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^-0.008 ^-1.492 ^-0.083 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^-0.072 ^-1.494 ^-0.041 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^-0.079 ^-1.497 ^0.027 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^-0.043 ^-1.499 ^0.071 ~ ~