#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run tp @s ^-0.027 ^-1.508 ^0.083 ~ ~
execute if score .this aj.frame matches 17 run tp @s ^-0.019 ^-1.502 ^0.083 ~ ~
execute if score .this aj.frame matches 18 run tp @s ^0 ^-1.497 ^0.083 ~ ~
execute if score .this aj.frame matches 19 run tp @s ^0.019 ^-1.494 ^0.083 ~ ~
execute if score .this aj.frame matches 20 run tp @s ^0.028 ^-1.491 ^0.083 ~ ~
execute if score .this aj.frame matches 21 run tp @s ^0.02 ^-1.49 ^0.083 ~ ~
execute if score .this aj.frame matches 22 run tp @s ^0.002 ^-1.489 ^0.083 ~ ~
execute if score .this aj.frame matches 23 run tp @s ^-0.017 ^-1.49 ^0.083 ~ ~