#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 105 run data modify entity @s Pose.Head set value [0f,0f,1.4815f]
execute if score .this aj.frame matches 106 run data modify entity @s Pose.Head set value [0f,0f,3.5185f]
execute if score .this aj.frame matches 107 run data modify entity @s Pose.Head set value [0f,0f,5f]
execute if score .this aj.frame matches 108 run data modify entity @s Pose.Head set value [0f,0f,5.4687f]
execute if score .this aj.frame matches 109 run data modify entity @s Pose.Head set value [0f,0f,5.625f]
execute if score .this aj.frame matches 110 run data modify entity @s Pose.Head set value [0f,0f,5.4688f]
execute if score .this aj.frame matches 111 run data modify entity @s Pose.Head set value [0f,0f,5f]