#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104..111 run function cob:animations/loop/tree/group_display_104-111
execute if score .this aj.frame matches 112 run data modify entity @s Pose.Head set value [0f,0f,0f]