#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 96 run tp @s ^0 ^-1.156 ^0 ~ ~
execute if score .this aj.frame matches 97 run tp @s ^0 ^-1.158 ^0 ~ ~
execute if score .this aj.frame matches 98 run tp @s ^0 ^-1.16 ^0 ~ ~
execute if score .this aj.frame matches 99 run tp @s ^0 ^-1.162 ^0 ~ ~
execute if score .this aj.frame matches 100 run tp @s ^0 ^-1.165 ^0 ~ ~
execute if score .this aj.frame matches 101 run tp @s ^0 ^-1.167 ^0 ~ ~
execute if score .this aj.frame matches 102 run tp @s ^0 ^-1.169 ^0 ~ ~
execute if score .this aj.frame matches 103 run tp @s ^0 ^-1.172 ^0 ~ ~