#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 184 run tp @s ^0 ^-1.425 ^0 ~ ~
execute if score .this aj.frame matches 185 run tp @s ^0 ^-1.449 ^0 ~ ~
execute if score .this aj.frame matches 186 run tp @s ^0 ^-1.47 ^0 ~ ~
execute if score .this aj.frame matches 187 run tp @s ^0 ^-1.487 ^0 ~ ~
execute if score .this aj.frame matches 188 run tp @s ^0 ^-1.5 ^0 ~ ~
execute if score .this aj.frame matches 189 run tp @s ^0 ^-1.5 ^0 ~ ~
execute if score .this aj.frame matches 190 run tp @s ^0 ^-1.5 ^0 ~ ~
execute if score .this aj.frame matches 191 run tp @s ^0 ^-1.5 ^0 ~ ~