#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 120 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 121 run data modify entity @s Pose.Head set value [0f,0f,0.001f]
execute if score .this aj.frame matches 122 run data modify entity @s Pose.Head set value [0f,0f,0.0038f]
execute if score .this aj.frame matches 123 run data modify entity @s Pose.Head set value [0f,0f,0.0085f]
execute if score .this aj.frame matches 124 run data modify entity @s Pose.Head set value [0f,0f,0.0147f]
execute if score .this aj.frame matches 125 run data modify entity @s Pose.Head set value [0f,0f,0.0225f]
execute if score .this aj.frame matches 126 run data modify entity @s Pose.Head set value [0f,0f,0.0317f]
execute if score .this aj.frame matches 127 run data modify entity @s Pose.Head set value [0f,0f,0.0421f]