#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 88 run data modify entity @s Pose.Head set value [0f,29.16f,0f]
execute if score .this aj.frame matches 89 run data modify entity @s Pose.Head set value [0f,16.245f,0f]
execute if score .this aj.frame matches 90 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 91 run data modify entity @s Pose.Head set value [0f,-30.9621f,0f]
execute if score .this aj.frame matches 92 run data modify entity @s Pose.Head set value [0f,-71.3703f,0f]
execute if score .this aj.frame matches 93 run data modify entity @s Pose.Head set value [-180f,-60.3499f,180f]
execute if score .this aj.frame matches 94 run data modify entity @s Pose.Head set value [-180f,-5.7726f,180f]
execute if score .this aj.frame matches 95 run data modify entity @s Pose.Head set value [-180f,53.5277f,180f]