#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 144 run data modify entity @s Pose.Head set value [0f,0f,0.2995f]
execute if score .this aj.frame matches 145 run data modify entity @s Pose.Head set value [0f,0f,0.3125f]
execute if score .this aj.frame matches 146 run data modify entity @s Pose.Head set value [0f,0f,0.3245f]
execute if score .this aj.frame matches 147 run data modify entity @s Pose.Head set value [0f,0f,0.3353f]
execute if score .this aj.frame matches 148 run data modify entity @s Pose.Head set value [0f,0f,0.345f]
execute if score .this aj.frame matches 149 run data modify entity @s Pose.Head set value [0f,0f,0.3532f]
execute if score .this aj.frame matches 150 run data modify entity @s Pose.Head set value [0f,0f,0.36f]
execute if score .this aj.frame matches 151 run data modify entity @s Pose.Head set value [0f,0f,0.3652f]