#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run tp @s ^-0.055 ^-1.186 ^0 ~ ~
execute if score .this aj.frame matches 25 run tp @s ^-0.051 ^-1.185 ^0 ~ ~
execute if score .this aj.frame matches 26 run tp @s ^-0.034 ^-1.183 ^0 ~ ~
execute if score .this aj.frame matches 27 run tp @s ^-0.014 ^-1.181 ^0 ~ ~
execute if score .this aj.frame matches 28 run tp @s ^0 ^-1.18 ^0 ~ ~
execute if score .this aj.frame matches 29 run tp @s ^0.001 ^-1.179 ^0 ~ ~
execute if score .this aj.frame matches 30 run tp @s ^0.001 ^-1.178 ^0 ~ ~
execute if score .this aj.frame matches 31 run tp @s ^0.002 ^-1.177 ^0 ~ ~