#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 168 run tp @s ^0.001 ^-1.184 ^0 ~ ~
execute if score .this aj.frame matches 169 run tp @s ^0.001 ^-1.184 ^0 ~ ~
execute if score .this aj.frame matches 170 run tp @s ^0 ^-1.184 ^0 ~ ~
execute if score .this aj.frame matches 171 run tp @s ^-0.02 ^-1.185 ^0 ~ ~
execute if score .this aj.frame matches 172 run tp @s ^-0.047 ^-1.188 ^0 ~ ~
execute if score .this aj.frame matches 173 run tp @s ^-0.055 ^-1.189 ^0 ~ ~
execute if score .this aj.frame matches 174 run tp @s ^-0.022 ^-1.188 ^0 ~ ~
execute if score .this aj.frame matches 175 run tp @s ^0.028 ^-1.202 ^0 ~ ~