#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 32 run tp @s ^0.002 ^-1.176 ^0 ~ ~
execute if score .this aj.frame matches 33 run tp @s ^0.003 ^-1.175 ^0 ~ ~
execute if score .this aj.frame matches 34 run tp @s ^0.003 ^-1.174 ^0 ~ ~
execute if score .this aj.frame matches 35 run tp @s ^0.003 ^-1.173 ^0 ~ ~
execute if score .this aj.frame matches 36 run tp @s ^0.003 ^-1.172 ^0 ~ ~
execute if score .this aj.frame matches 37 run tp @s ^0.004 ^-1.171 ^0 ~ ~
execute if score .this aj.frame matches 38 run tp @s ^0.004 ^-1.17 ^0 ~ ~
execute if score .this aj.frame matches 39 run tp @s ^0.004 ^-1.169 ^0 ~ ~