#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 176 run tp @s ^0.052 ^-1.221 ^0 ~ ~
execute if score .this aj.frame matches 177 run tp @s ^0.026 ^-1.241 ^0 ~ ~
execute if score .this aj.frame matches 178 run tp @s ^-0.02 ^-1.264 ^0 ~ ~
execute if score .this aj.frame matches 179 run tp @s ^-0.046 ^-1.291 ^0 ~ ~
execute if score .this aj.frame matches 180 run tp @s ^-0.037 ^-1.318 ^0 ~ ~
execute if score .this aj.frame matches 181 run tp @s ^-0.015 ^-1.344 ^0 ~ ~
execute if score .this aj.frame matches 182 run tp @s ^0 ^-1.372 ^0 ~ ~
execute if score .this aj.frame matches 183 run tp @s ^0 ^-1.399 ^0 ~ ~