#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 104 run tp @s ^0 ^-1.174 ^0 ~ ~
execute if score .this aj.frame matches 105 run tp @s ^0.015 ^-1.176 ^0 ~ ~
execute if score .this aj.frame matches 106 run tp @s ^0.035 ^-1.179 ^0 ~ ~
execute if score .this aj.frame matches 107 run tp @s ^0.05 ^-1.181 ^0 ~ ~
execute if score .this aj.frame matches 108 run tp @s ^0.054 ^-1.183 ^0 ~ ~
execute if score .this aj.frame matches 109 run tp @s ^0.056 ^-1.184 ^0 ~ ~
execute if score .this aj.frame matches 110 run tp @s ^0.054 ^-1.184 ^0 ~ ~
execute if score .this aj.frame matches 111 run tp @s ^0.05 ^-1.183 ^0 ~ ~