#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 24 run data modify entity @s Pose.Head set value [0f,0f,-5f]
execute if score .this aj.frame matches 25 run data modify entity @s Pose.Head set value [0f,0f,-4.6875f]
execute if score .this aj.frame matches 26 run data modify entity @s Pose.Head set value [0f,0f,-3.125f]
execute if score .this aj.frame matches 27 run data modify entity @s Pose.Head set value [0f,0f,-1.25f]
execute if score .this aj.frame matches 28 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 29 run data modify entity @s Pose.Head set value [0f,0f,0.0567f]
execute if score .this aj.frame matches 30 run data modify entity @s Pose.Head set value [0f,0f,0.108f]
execute if score .this aj.frame matches 31 run data modify entity @s Pose.Head set value [0f,0f,0.154f]