#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 128 run tp @s ^0.001 ^-1.156 ^0 ~ ~
execute if score .this aj.frame matches 129 run tp @s ^0.001 ^-1.156 ^0 ~ ~
execute if score .this aj.frame matches 130 run tp @s ^0.001 ^-1.156 ^0 ~ ~
execute if score .this aj.frame matches 131 run tp @s ^0.001 ^-1.157 ^0 ~ ~
execute if score .this aj.frame matches 132 run tp @s ^0.001 ^-1.158 ^0 ~ ~
execute if score .this aj.frame matches 133 run tp @s ^0.001 ^-1.159 ^0 ~ ~
execute if score .this aj.frame matches 134 run tp @s ^0.002 ^-1.161 ^0 ~ ~
execute if score .this aj.frame matches 135 run tp @s ^0.002 ^-1.163 ^0 ~ ~