#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.cob.bone.group] run function cob:animations/loop/tree/group_root_top
execute if entity @s[tag=aj.cob.bone.face] run function cob:animations/loop/tree/face_root_top
execute if entity @s[tag=aj.cob.bone.head] run function cob:animations/loop/tree/head_root_top
execute store result entity @s Air short 1 run scoreboard players get .this aj.frame