#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-0.0108f,-0.5224f,0.8446f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-0.0386f,-1.3145f,2.0975f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-0.0765f,-2.2949f,3.6399f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-0.1176f,-3.3826f,5.3532f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-0.155f,-4.4963f,7.1189f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-0.1819f,-5.5548f,8.8182f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-0.1913f,-6.4771f,10.3325f]