#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 16 run data modify entity @s Pose.Head set value [1.9158f,3.0815f,-0.5029f]
execute if score .this aj.frame matches 17 run data modify entity @s Pose.Head set value [2.2403f,5.1859f,-3.2255f]
execute if score .this aj.frame matches 18 run data modify entity @s Pose.Head set value [2.4732f,6.839f,-5.4175f]
execute if score .this aj.frame matches 19 run data modify entity @s Pose.Head set value [2.5802f,7.8367f,-6.8216f]
execute if score .this aj.frame matches 20 run data modify entity @s Pose.Head set value [2.533f,8.0663f,-7.3183f]
execute if score .this aj.frame matches 21 run data modify entity @s Pose.Head set value [2.3464f,7.6964f,-7.1532f]
execute if score .this aj.frame matches 22 run data modify entity @s Pose.Head set value [2.0544f,6.8684f,-6.4792f]
execute if score .this aj.frame matches 23 run data modify entity @s Pose.Head set value [1.6912f,5.7201f,-5.4439f]