#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-0.1764f,-7.1818f,11.5431f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-0.1302f,-7.5879f,12.3315f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-0.0459f,-7.6141f,12.579f]
execute if score .this aj.frame matches 11 run data modify entity @s Pose.Head set value [0.1109f,-7.0757f,12.0609f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [0.3824f,-5.7726f,10.5458f]
execute if score .this aj.frame matches 13 run data modify entity @s Pose.Head set value [0.7327f,-3.9015f,8.2745f]
execute if score .this aj.frame matches 14 run data modify entity @s Pose.Head set value [1.1278f,-1.6662f,5.5044f]
execute if score .this aj.frame matches 15 run data modify entity @s Pose.Head set value [1.5336f,0.7295f,2.4928f]