#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#cob:bone_entities,tag=aj.cob.bone] if score @s aj.id = .this aj.id run function cob:zzz/execute/8