#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
scoreboard players set # aj.i 0
execute if entity @s[tag=aj.amirkaka.anim.idle1] run function amirkaka:zzz/execute/7
execute if entity @s[tag=aj.amirkaka.anim.idle2] run function amirkaka:zzz/execute/10
execute if entity @s[tag=aj.amirkaka.anim.idle3] run function amirkaka:zzz/execute/13
execute if entity @s[tag=aj.amirkaka.anim.idle4] run function amirkaka:zzz/execute/16
execute if entity @s[tag=aj.amirkaka.anim.idle5] run function amirkaka:zzz/execute/19
execute if entity @s[tag=aj.amirkaka.anim.fall] run function amirkaka:zzz/execute/22
execute if score # aj.i matches 0 run function amirkaka:zzz/execute/25
scoreboard players set #execute aj.i 1